
package funcionarios;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import principal.Class_Consumir_Letras;
import principal.Class_Manipular_Data;
import principal.Class_Verifica_Menu_Aberto;

public class Painel_Funcionarios extends javax.swing.JPanel {
    
    protected ArrayList arrayList = new ArrayList();
    protected JTabbedPane painel_principal;
    protected String nome_usuario;
    protected int id_usuario;

    public Painel_Funcionarios() {
        initComponents();
    }
    
    public Painel_Funcionarios(JTabbedPane painel_principal, int id_usuario, String nome_usuario) {
        initComponents();
        
        this.painel_principal = painel_principal;
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
    }
    
    public void refreshFuncionarios() {
        Class_Funcionarios funcionarios = new Class_Funcionarios();
        listFuncionarios.setModel(funcionarios.carregaFuncionario(""));
        arrayList = funcionarios.getListaIdFuncionario();
    }
    
    public void limpaCamposNovoCadastro() {
        txtNomeCadastrar.setText("");
        txtNascimentoCadastrar.setText("");
        txtRgCadastrar.setText("");
        txtCPFCadastrar.setText("");
        txtTelefoneCadastrar.setText("");
        txtCelularCadastrar.setText("");
        txtEmailNovoCadastro.setText("");
        txtCEPCadastrar.setText("");
        txtEnderecoCadastrar.setText("");
        txtBairroCadastrar.setText("");
        txtCidadeCadastrar.setText("");
        txtEstadoCadastrar.setText("");
        txtPaisCadastrar.setText("");
        comboFuncaoNovoCadastro.setSelectedIndex(0);
        
        lblIdadeFuncionarioCadastrar.setText("");
        txtNomeCadastrar.grabFocus();
    }
    
    public void carregaFuncoes(JComboBox combo) {
        Class_Funcionarios funcionarios = new Class_Funcionarios();
        funcionarios.carregaFuncoesComboBox(combo);
    }
    
    public void calcularIdadeNovoCadastro() {
        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        String a = cons.retiraLetrasEPontos(txtNascimentoCadastrar.getText());
        if (a.length() == 8) {
            try {
                Class_Manipular_Data data = new Class_Manipular_Data();
                int diasVividos = data.retornaQntAnos(txtNascimentoCadastrar.getText());
                if (diasVividos <= 0) {
                    lblIdadeFuncionarioCadastrar.setText("");
                } else if (diasVividos == 1) {
                    lblIdadeFuncionarioCadastrar.setText("O funcionário possui "+diasVividos+" ano");
                } else {
                    lblIdadeFuncionarioCadastrar.setText("O funcionário possui "+diasVividos+" anos");
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            lblIdadeFuncionarioCadastrar.setText("");
        }
    }
    
    public void calcularIdadeEditarCadastro() {
        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        String a = cons.retiraLetrasEPontos(txtNascimentoEditar.getText());
        if (a.length() == 8) {
            try {
                Class_Manipular_Data data = new Class_Manipular_Data();
                int diasVividos = data.retornaQntAnos(txtNascimentoEditar.getText());
                if (diasVividos <= 0) {
                    lblIdadeFuncionarioEditar.setText("");
                } else if (diasVividos == 1) {
                    lblIdadeFuncionarioEditar.setText("O funcionário possui "+diasVividos+" ano");
                } else {
                    lblIdadeFuncionarioEditar.setText("O funcionário possui "+diasVividos+" anos");
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            lblIdadeFuncionarioEditar.setText("");
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novo_funcionario = new javax.swing.JDialog();
        jLabel54 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtNomeCadastrar = new javax.swing.JTextField();
        txtNascimentoCadastrar = new javax.swing.JFormattedTextField();
        txtRgCadastrar = new javax.swing.JTextField();
        txtCPFCadastrar = new javax.swing.JFormattedTextField();
        txtTelefoneCadastrar = new javax.swing.JTextField();
        txtCelularCadastrar = new javax.swing.JTextField();
        txtCEPCadastrar = new javax.swing.JFormattedTextField();
        txtEnderecoCadastrar = new javax.swing.JTextField();
        txtBairroCadastrar = new javax.swing.JTextField();
        txtCidadeCadastrar = new javax.swing.JTextField();
        txtEstadoCadastrar = new javax.swing.JTextField();
        txtPaisCadastrar = new javax.swing.JTextField();
        lblIdadeFuncionarioCadastrar = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        btnSalvarCadastro = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSairCadastro = new javax.swing.JButton();
        comboFuncaoNovoCadastro = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        txtEmailNovoCadastro = new javax.swing.JTextField();
        editar_funcionario = new javax.swing.JDialog();
        jLabel55 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txtNomeEditar = new javax.swing.JTextField();
        txtNascimentoEditar = new javax.swing.JFormattedTextField();
        txtRGEditar = new javax.swing.JTextField();
        txtCPFEditar = new javax.swing.JFormattedTextField();
        txtTelefoneEditar = new javax.swing.JTextField();
        txtCelularEditar = new javax.swing.JTextField();
        txtCEPEditar = new javax.swing.JFormattedTextField();
        txtEnderecoEditar = new javax.swing.JTextField();
        txtBairroEditar = new javax.swing.JTextField();
        txtCidadeEditar = new javax.swing.JTextField();
        txtEstadoEditar = new javax.swing.JTextField();
        txtPaisEditar = new javax.swing.JTextField();
        lblIdadeFuncionarioEditar = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        btnSalvarEditar = new javax.swing.JButton();
        btnSairEditar = new javax.swing.JButton();
        comboFuncaoEditar = new javax.swing.JComboBox();
        jLabel64 = new javax.swing.JLabel();
        txtEmailEditar = new javax.swing.JTextField();
        funcoes = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFuncoes = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        btnCadastrarFuncao = new javax.swing.JButton();
        btnEditarFuncao = new javax.swing.JButton();
        btnExcluirFuncao = new javax.swing.JButton();
        btnSairFuncao = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnPesquisarFuncionarios = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFuncionarios = new javax.swing.JList();
        btnNovo = new javax.swing.JButton();
        btnDados = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFuncoes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtFuncao = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();

        novo_funcionario.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        novo_funcionario.setTitle("Novo cadastro");
        novo_funcionario.setModal(true);
        novo_funcionario.setResizable(false);
        novo_funcionario.getContentPane().setLayout(null);

        jLabel54.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel54.setText("Função");
        novo_funcionario.getContentPane().add(jLabel54);
        jLabel54.setBounds(110, 490, 48, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trabalhador 24px.png"))); // NOI18N
        jLabel35.setText("Novo cadastro");
        novo_funcionario.getContentPane().add(jLabel35);
        jLabel35.setBounds(0, 30, 680, 30);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setText("Nome");
        novo_funcionario.getContentPane().add(jLabel37);
        jLabel37.setBounds(120, 100, 50, 17);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel39.setText(" Nascimento");
        novo_funcionario.getContentPane().add(jLabel39);
        jLabel39.setBounds(80, 140, 80, 17);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel40.setText(" RG");
        novo_funcionario.getContentPane().add(jLabel40);
        jLabel40.setBounds(130, 180, 30, 17);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel42.setText("CPF");
        novo_funcionario.getContentPane().add(jLabel42);
        jLabel42.setBounds(350, 180, 28, 17);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel44.setText("Telefone");
        novo_funcionario.getContentPane().add(jLabel44);
        jLabel44.setBounds(100, 220, 56, 17);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel45.setText("Celular");
        novo_funcionario.getContentPane().add(jLabel45);
        jLabel45.setBounds(340, 220, 45, 17);

        jLabel46.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel46.setText("CEP");
        novo_funcionario.getContentPane().add(jLabel46);
        jLabel46.setBounds(130, 300, 28, 17);

        jLabel47.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel47.setText(" Endereço");
        novo_funcionario.getContentPane().add(jLabel47);
        jLabel47.setBounds(90, 340, 70, 17);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel48.setText(" Cidade");
        novo_funcionario.getContentPane().add(jLabel48);
        jLabel48.setBounds(110, 420, 50, 17);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel49.setText(" Estado");
        novo_funcionario.getContentPane().add(jLabel49);
        jLabel49.setBounds(110, 460, 50, 17);

        jLabel50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel50.setText("País");
        novo_funcionario.getContentPane().add(jLabel50);
        jLabel50.setBounds(260, 460, 27, 17);

        txtNomeCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtNomeCadastrar);
        txtNomeCadastrar.setBounds(180, 90, 350, 30);

        try {
            txtNascimentoCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimentoCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNascimentoCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNascimentoCadastrarKeyReleased(evt);
            }
        });
        novo_funcionario.getContentPane().add(txtNascimentoCadastrar);
        txtNascimentoCadastrar.setBounds(180, 130, 140, 30);

        txtRgCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtRgCadastrar);
        txtRgCadastrar.setBounds(180, 170, 140, 30);

        try {
            txtCPFCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtCPFCadastrar);
        txtCPFCadastrar.setBounds(400, 170, 130, 30);

        txtTelefoneCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtTelefoneCadastrar);
        txtTelefoneCadastrar.setBounds(180, 210, 140, 30);

        txtCelularCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtCelularCadastrar);
        txtCelularCadastrar.setBounds(400, 210, 130, 30);

        try {
            txtCEPCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEPCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtCEPCadastrar);
        txtCEPCadastrar.setBounds(180, 290, 110, 30);

        txtEnderecoCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtEnderecoCadastrar);
        txtEnderecoCadastrar.setBounds(180, 330, 350, 30);

        txtBairroCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtBairroCadastrar);
        txtBairroCadastrar.setBounds(180, 370, 350, 30);

        txtCidadeCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtCidadeCadastrar);
        txtCidadeCadastrar.setBounds(180, 410, 350, 30);

        txtEstadoCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEstadoCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoCadastrarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoCadastrarKeyTyped(evt);
            }
        });
        novo_funcionario.getContentPane().add(txtEstadoCadastrar);
        txtEstadoCadastrar.setBounds(180, 450, 50, 30);

        txtPaisCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtPaisCadastrar);
        txtPaisCadastrar.setBounds(310, 450, 220, 30);

        lblIdadeFuncionarioCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIdadeFuncionarioCadastrar.setForeground(new java.awt.Color(255, 0, 0));
        lblIdadeFuncionarioCadastrar.setText("O funcionário possui 18 anos");
        novo_funcionario.getContentPane().add(lblIdadeFuncionarioCadastrar);
        lblIdadeFuncionarioCadastrar.setBounds(330, 140, 220, 17);

        jLabel62.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel62.setText("Bairro");
        novo_funcionario.getContentPane().add(jLabel62);
        jLabel62.setBounds(120, 380, 50, 17);

        btnSalvarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarCadastro.setText("Salvar");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });
        novo_funcionario.getContentPane().add(btnSalvarCadastro);
        btnSalvarCadastro.setBounds(190, 560, 100, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Limpar 16px.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        novo_funcionario.getContentPane().add(btnLimpar);
        btnLimpar.setBounds(300, 560, 100, 30);

        btnSairCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairCadastro.setText("Sair");
        btnSairCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroActionPerformed(evt);
            }
        });
        novo_funcionario.getContentPane().add(btnSairCadastro);
        btnSairCadastro.setBounds(410, 560, 100, 30);

        comboFuncaoNovoCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(comboFuncaoNovoCadastro);
        comboFuncaoNovoCadastro.setBounds(180, 490, 350, 30);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setText("Email");
        novo_funcionario.getContentPane().add(jLabel36);
        jLabel36.setBounds(120, 260, 34, 17);

        txtEmailNovoCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        novo_funcionario.getContentPane().add(txtEmailNovoCadastro);
        txtEmailNovoCadastro.setBounds(180, 250, 350, 30);

        editar_funcionario.getContentPane().setLayout(null);

        jLabel55.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel55.setText("Função");
        editar_funcionario.getContentPane().add(jLabel55);
        jLabel55.setBounds(110, 490, 48, 30);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trabalhador 24px.png"))); // NOI18N
        jLabel38.setText("Novo cadastro");
        editar_funcionario.getContentPane().add(jLabel38);
        jLabel38.setBounds(0, 30, 680, 30);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setText("Nome");
        editar_funcionario.getContentPane().add(jLabel41);
        jLabel41.setBounds(120, 100, 50, 17);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setText(" Nascimento");
        editar_funcionario.getContentPane().add(jLabel43);
        jLabel43.setBounds(80, 140, 80, 17);

        jLabel51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel51.setText(" RG");
        editar_funcionario.getContentPane().add(jLabel51);
        jLabel51.setBounds(130, 180, 30, 17);

        jLabel52.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel52.setText("CPF");
        editar_funcionario.getContentPane().add(jLabel52);
        jLabel52.setBounds(350, 180, 28, 17);

        jLabel53.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel53.setText("Telefone");
        editar_funcionario.getContentPane().add(jLabel53);
        jLabel53.setBounds(100, 220, 56, 17);

        jLabel56.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel56.setText("Celular");
        editar_funcionario.getContentPane().add(jLabel56);
        jLabel56.setBounds(340, 220, 45, 17);

        jLabel57.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel57.setText("CEP");
        editar_funcionario.getContentPane().add(jLabel57);
        jLabel57.setBounds(130, 300, 28, 17);

        jLabel58.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel58.setText(" Endereço");
        editar_funcionario.getContentPane().add(jLabel58);
        jLabel58.setBounds(90, 340, 70, 17);

        jLabel59.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel59.setText(" Cidade");
        editar_funcionario.getContentPane().add(jLabel59);
        jLabel59.setBounds(110, 420, 50, 17);

        jLabel60.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel60.setText(" Estado");
        editar_funcionario.getContentPane().add(jLabel60);
        jLabel60.setBounds(110, 460, 50, 17);

        jLabel61.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel61.setText("País");
        editar_funcionario.getContentPane().add(jLabel61);
        jLabel61.setBounds(260, 460, 27, 17);

        txtNomeEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtNomeEditar);
        txtNomeEditar.setBounds(180, 90, 350, 30);

        try {
            txtNascimentoEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimentoEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNascimentoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNascimentoEditarKeyReleased(evt);
            }
        });
        editar_funcionario.getContentPane().add(txtNascimentoEditar);
        txtNascimentoEditar.setBounds(180, 130, 140, 30);

        txtRGEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtRGEditar);
        txtRGEditar.setBounds(180, 170, 140, 30);

        try {
            txtCPFEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtCPFEditar);
        txtCPFEditar.setBounds(400, 170, 130, 30);

        txtTelefoneEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtTelefoneEditar);
        txtTelefoneEditar.setBounds(180, 210, 140, 30);

        txtCelularEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtCelularEditar);
        txtCelularEditar.setBounds(400, 210, 130, 30);

        try {
            txtCEPEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEPEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtCEPEditar);
        txtCEPEditar.setBounds(180, 290, 110, 30);

        txtEnderecoEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtEnderecoEditar);
        txtEnderecoEditar.setBounds(180, 330, 350, 30);

        txtBairroEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtBairroEditar);
        txtBairroEditar.setBounds(180, 370, 350, 30);

        txtCidadeEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtCidadeEditar);
        txtCidadeEditar.setBounds(180, 410, 350, 30);

        txtEstadoEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEstadoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoEditarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoEditarKeyTyped(evt);
            }
        });
        editar_funcionario.getContentPane().add(txtEstadoEditar);
        txtEstadoEditar.setBounds(180, 450, 50, 30);

        txtPaisEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtPaisEditar);
        txtPaisEditar.setBounds(310, 450, 220, 30);

        lblIdadeFuncionarioEditar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIdadeFuncionarioEditar.setForeground(new java.awt.Color(255, 0, 0));
        lblIdadeFuncionarioEditar.setText("O funcionário possui 18 anos");
        editar_funcionario.getContentPane().add(lblIdadeFuncionarioEditar);
        lblIdadeFuncionarioEditar.setBounds(330, 140, 230, 17);

        jLabel63.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel63.setText("Bairro");
        editar_funcionario.getContentPane().add(jLabel63);
        jLabel63.setBounds(120, 380, 50, 17);

        btnSalvarEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarEditar.setText("Salvar");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });
        editar_funcionario.getContentPane().add(btnSalvarEditar);
        btnSalvarEditar.setBounds(250, 560, 100, 30);

        btnSairEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairEditar.setText("Sair");
        btnSairEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEditarActionPerformed(evt);
            }
        });
        editar_funcionario.getContentPane().add(btnSairEditar);
        btnSairEditar.setBounds(360, 560, 100, 30);

        comboFuncaoEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(comboFuncaoEditar);
        comboFuncaoEditar.setBounds(180, 490, 350, 30);

        jLabel64.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel64.setText("Email");
        editar_funcionario.getContentPane().add(jLabel64);
        jLabel64.setBounds(120, 260, 34, 17);

        txtEmailEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_funcionario.getContentPane().add(txtEmailEditar);
        txtEmailEditar.setBounds(180, 250, 350, 30);

        funcoes.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        funcoes.setTitle("Funções");
        funcoes.setModal(true);
        funcoes.setResizable(false);
        funcoes.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciamento de funções");
        funcoes.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 560, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Funções cadastradas");
        funcoes.getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 150, 17);

        listFuncoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listFuncoes.setSelectionBackground(new java.awt.Color(204, 255, 255));
        listFuncoes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(listFuncoes);

        funcoes.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 230, 210);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        funcoes.getContentPane().add(jButton2);
        jButton2.setBounds(210, 90, 40, 30);

        btnCadastrarFuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrarFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnCadastrarFuncao.setText("Cadastrar função");
        btnCadastrarFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncaoActionPerformed(evt);
            }
        });
        funcoes.getContentPane().add(btnCadastrarFuncao);
        btnCadastrarFuncao.setBounds(330, 120, 210, 30);

        btnEditarFuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnEditarFuncao.setText("Editar função");
        btnEditarFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncaoActionPerformed(evt);
            }
        });
        funcoes.getContentPane().add(btnEditarFuncao);
        btnEditarFuncao.setBounds(330, 160, 210, 30);

        btnExcluirFuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirFuncao.setText("Excluir função");
        btnExcluirFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncaoActionPerformed(evt);
            }
        });
        funcoes.getContentPane().add(btnExcluirFuncao);
        btnExcluirFuncao.setBounds(330, 200, 210, 30);

        btnSairFuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairFuncao.setText("Sair");
        btnSairFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairFuncaoActionPerformed(evt);
            }
        });
        funcoes.getContentPane().add(btnSairFuncao);
        btnSairFuncao.setBounds(330, 240, 210, 30);

        setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trabalhador 24px.png"))); // NOI18N
        jLabel19.setText("Gerenciamento do cadastro de funcionários");
        add(jLabel19);
        jLabel19.setBounds(0, 30, 810, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Funcionários cadastrados");
        add(jLabel20);
        jLabel20.setBounds(20, 100, 180, 17);

        btnPesquisarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        add(btnPesquisarFuncionarios);
        btnPesquisarFuncionarios.setBounds(250, 90, 40, 30);

        listFuncionarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listFuncionarios.setSelectionBackground(new java.awt.Color(204, 255, 255));
        listFuncionarios.setSelectionForeground(new java.awt.Color(0, 0, 0));
        listFuncionarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFuncionariosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listFuncionarios);

        add(jScrollPane3);
        jScrollPane3.setBounds(20, 120, 270, 390);

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        add(btnNovo);
        btnNovo.setBounds(190, 590, 100, 30);

        btnDados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnDados.setText("Editar");
        btnDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        add(btnDados);
        btnDados.setBounds(300, 590, 100, 30);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        add(btnExcluir);
        btnExcluir.setBounds(410, 590, 100, 30);

        btnFuncoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFuncoes.setText("Gerenciar funções");
        btnFuncoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFuncoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncoesActionPerformed(evt);
            }
        });
        add(btnFuncoes);
        btnFuncoes.setBounds(20, 520, 270, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(520, 590, 100, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Nome");
        add(jLabel21);
        jLabel21.setBounds(380, 130, 40, 17);

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.setEnabled(false);
        add(txtNome);
        txtNome.setBounds(440, 120, 350, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText(" Nascimento");
        add(jLabel22);
        jLabel22.setBounds(340, 170, 80, 17);

        txtNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNascimento.setEnabled(false);
        add(txtNascimento);
        txtNascimento.setBounds(440, 160, 130, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("CPF");
        add(jLabel23);
        jLabel23.setBounds(620, 210, 28, 17);

        txtCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCPF.setEnabled(false);
        add(txtCPF);
        txtCPF.setBounds(660, 200, 130, 30);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText(" RG");
        add(jLabel24);
        jLabel24.setBounds(390, 210, 30, 17);

        txtRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRG.setEnabled(false);
        add(txtRG);
        txtRG.setBounds(440, 200, 130, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Email");
        add(jLabel25);
        jLabel25.setBounds(380, 250, 40, 17);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setEnabled(false);
        add(txtEmail);
        txtEmail.setBounds(440, 240, 350, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Telefone");
        add(jLabel26);
        jLabel26.setBounds(360, 290, 60, 17);

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefone.setEnabled(false);
        add(txtTelefone);
        txtTelefone.setBounds(440, 280, 130, 30);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Celular");
        add(jLabel27);
        jLabel27.setBounds(600, 290, 45, 17);

        txtCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCelular.setEnabled(false);
        add(txtCelular);
        txtCelular.setBounds(660, 280, 130, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Função");
        add(jLabel28);
        jLabel28.setBounds(370, 330, 50, 17);

        txtFuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFuncao.setEnabled(false);
        add(txtFuncao);
        txtFuncao.setBounds(440, 320, 350, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText(" CEP");
        add(jLabel29);
        jLabel29.setBounds(380, 370, 40, 17);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText(" Endereço");
        add(jLabel30);
        jLabel30.setBounds(350, 410, 70, 17);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Cidade");
        add(jLabel31);
        jLabel31.setBounds(370, 490, 50, 17);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Estado");
        add(jLabel32);
        jLabel32.setBounds(370, 530, 50, 17);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("País");
        add(jLabel33);
        jLabel33.setBounds(520, 530, 27, 17);

        txtCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCEP.setEnabled(false);
        add(txtCEP);
        txtCEP.setBounds(440, 360, 100, 30);

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEndereco.setEnabled(false);
        add(txtEndereco);
        txtEndereco.setBounds(440, 400, 350, 30);

        txtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro.setEnabled(false);
        add(txtBairro);
        txtBairro.setBounds(440, 440, 350, 30);

        txtCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCidade.setEnabled(false);
        add(txtCidade);
        txtCidade.setBounds(440, 480, 350, 30);

        txtEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEstado.setEnabled(false);
        add(txtEstado);
        txtEstado.setBounds(440, 520, 50, 30);

        txtPais.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPais.setEnabled(false);
        add(txtPais);
        txtPais.setBounds(570, 520, 220, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText(" Bairro");
        add(jLabel34);
        jLabel34.setBounds(370, 450, 50, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        carregaFuncoes(comboFuncaoNovoCadastro);
        limpaCamposNovoCadastro();

        novo_funcionario.setBounds(0, 0, 680, 650);
        novo_funcionario.setLocationRelativeTo(null);
        novo_funcionario.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed

        Object funcionario = listFuncionarios.getSelectedValue();
        if (funcionario == null) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionário para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            carregaFuncoes(comboFuncaoEditar);

            txtNascimentoEditar.setValue(null);
            txtCPFEditar.setValue(null);

            txtNomeEditar.setText(txtNome.getText());
            txtNascimentoEditar.setText(txtNascimento.getText());
            txtRGEditar.setText(txtRG.getText());
            txtCPFEditar.setText(txtCPF.getText());
            txtEmailEditar.setText(txtEmail.getText());
            txtTelefoneEditar.setText(txtTelefone.getText());
            txtCelularEditar.setText(txtCelular.getText());
            comboFuncaoEditar.setSelectedItem(txtFuncao.getText());
            txtCEPEditar.setText(txtCEP.getText());
            txtEnderecoEditar.setText(txtEndereco.getText());
            txtBairroEditar.setText(txtBairro.getText());
            txtCidadeEditar.setText(txtCidade.getText());
            txtEstadoEditar.setText(txtEstado.getText());
            txtPaisEditar.setText(txtPais.getText());

            calcularIdadeEditarCadastro();

            txtNomeEditar.grabFocus();

            editar_funcionario.setBounds(0, 0, 680, 620);
            editar_funcionario.setLocationRelativeTo(null);
            editar_funcionario.setVisible(true);
        }
    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        Object funcionario = listFuncionarios.getSelectedValue();
        if (funcionario == null) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionário para excluir", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                int id_funcionario = Integer.valueOf(arrayList.get(listFuncionarios.getSelectedIndex()).toString());

                Class_Funcionarios funcionarios = new Class_Funcionarios();
                funcionarios.excluirFuncionario(id_funcionario);

                refreshFuncionarios();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFuncoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncoesActionPerformed

        Class_Funcionarios funcionarios = new Class_Funcionarios();
        listFuncoes.setModel(funcionarios.refreshFuncoes());

        funcoes.setBounds(0, 0, 580, 400);
        funcoes.setLocationRelativeTo(null);
        funcoes.setVisible(true);
        
    }//GEN-LAST:event_btnFuncoesActionPerformed

    private void txtNascimentoCadastrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascimentoCadastrarKeyReleased

        calcularIdadeNovoCadastro();
        
    }//GEN-LAST:event_txtNascimentoCadastrarKeyReleased

    private void txtEstadoCadastrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCadastrarKeyReleased

        int index = txtEstadoCadastrar.getCaretPosition();
        txtEstadoCadastrar.setText(txtEstadoCadastrar.getText().toUpperCase());
        txtEstadoCadastrar.setCaretPosition(index);
        
    }//GEN-LAST:event_txtEstadoCadastrarKeyReleased

    private void txtEstadoCadastrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCadastrarKeyTyped

        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        cons.consomeQntDeCaracteres(txtEstadoCadastrar, 1, evt);
        cons.consome("qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNMçÇ", evt);
        
    }//GEN-LAST:event_txtEstadoCadastrarKeyTyped

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed

        if (txtNomeCadastrar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo nome não pode ficar vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeCadastrar.grabFocus();
        } else if (txtNomeCadastrar.getText().length() >45) {
            JOptionPane.showMessageDialog(null, "O campo nome ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeCadastrar.grabFocus();
        } else if (txtRgCadastrar.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "O campo RG ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtRgCadastrar.grabFocus();
        } else if (txtTelefoneCadastrar.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "O campo telefone ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtTelefoneCadastrar.grabFocus();
        } else if (txtCelularCadastrar.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "O campo celular ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtCelularCadastrar.grabFocus();
        } else if (txtEmailNovoCadastro.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo email ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtEnderecoCadastrar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo endereço ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtEnderecoCadastrar.grabFocus();
        } else if (txtBairroCadastrar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo bairro ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtBairroCadastrar.grabFocus();
        } else if (txtCidadeCadastrar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo cidade ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtCidadeCadastrar.grabFocus();
        } else if (txtPaisCadastrar.getText().length() > 30) {
            JOptionPane.showMessageDialog(null, "O campo país ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtPaisCadastrar.grabFocus();
        } else {
            Class_Funcionarios funcionarios = new Class_Funcionarios();
            int id_funcao = funcionarios.retornaIdFuncao(comboFuncaoNovoCadastro.getSelectedItem().toString());

            funcionarios.cadastrarFuncionario(txtNomeCadastrar.getText(), txtNascimentoCadastrar.getText(), txtRgCadastrar.getText(),
                txtCPFCadastrar.getText(), txtEmailNovoCadastro.getText(), txtTelefoneCadastrar.getText(), txtCelularCadastrar.getText(),
                id_funcao, txtCEPCadastrar.getText(), txtEnderecoCadastrar.getText(), txtBairroCadastrar.getText(),
                txtCidadeCadastrar.getText(), txtEstadoCadastrar.getText(), txtPaisCadastrar.getText());

            novo_funcionario.dispose();
            refreshFuncionarios();
        }
        
    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        limpaCamposNovoCadastro();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroActionPerformed

        novo_funcionario.dispose();
        
    }//GEN-LAST:event_btnSairCadastroActionPerformed

    private void txtNascimentoEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascimentoEditarKeyReleased

        calcularIdadeEditarCadastro();

    }//GEN-LAST:event_txtNascimentoEditarKeyReleased

    private void txtEstadoEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoEditarKeyReleased

        int index = txtEstadoEditar.getCaretPosition();
        txtEstadoEditar.setText(txtEstadoEditar.getText().toUpperCase());
        txtEstadoEditar.setCaretPosition(index);

    }//GEN-LAST:event_txtEstadoEditarKeyReleased

    private void txtEstadoEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoEditarKeyTyped

        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        cons.consomeQntDeCaracteres(txtEstadoEditar, 1, evt);
        cons.consome("qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNMçÇ", evt);

    }//GEN-LAST:event_txtEstadoEditarKeyTyped

    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed

        if (txtNomeEditar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo nome não pode ficar vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeEditar.grabFocus();
        } else if (txtNomeEditar.getText().length() >45) {
            JOptionPane.showMessageDialog(null, "O campo nome ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeEditar.grabFocus();
        } else if (txtRGEditar.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "O campo RG ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtRGEditar.grabFocus();
        } else if (txtTelefoneEditar.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "O campo telefone ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtTelefoneEditar.grabFocus();
        } else if (txtCelularEditar.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "O campo celular ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtCelularEditar.grabFocus();
        } else if (txtEmailEditar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo email ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtEnderecoEditar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo endereço ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtEnderecoEditar.grabFocus();
        } else if (txtBairroEditar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo bairro ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtBairroEditar.grabFocus();
        } else if (txtCidadeEditar.getText().length() > 45) {
            JOptionPane.showMessageDialog(null, "O campo cidade ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtCidadeEditar.grabFocus();
        } else if (txtPaisEditar.getText().length() > 30) {
            JOptionPane.showMessageDialog(null, "O campo país ultrapassou o limite de caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtPaisEditar.grabFocus();
        } else {
            Class_Funcionarios funcionarios = new Class_Funcionarios();
            int id_funcao = funcionarios.retornaIdFuncao(comboFuncaoEditar.getSelectedItem().toString());

            int id_funcionario = Integer.valueOf(arrayList.get(listFuncionarios.getSelectedIndex()).toString());

            funcionarios.alterarFuncionario(txtNomeEditar.getText(), txtNascimentoEditar.getText(), txtRGEditar.getText(),
                txtCPFEditar.getText(), txtEmailEditar.getText(), txtTelefoneEditar.getText(), txtCelularEditar.getText(),
                id_funcao, txtCEPEditar.getText(), txtEnderecoEditar.getText(), txtBairroEditar.getText(),
                txtCidadeEditar.getText(), txtEstadoEditar.getText(), txtPaisEditar.getText(), id_funcionario);

            editar_funcionario.dispose();
            refreshFuncionarios();
        }

    }//GEN-LAST:event_btnSalvarEditarActionPerformed

    private void btnSairEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEditarActionPerformed

        editar_funcionario.dispose();

    }//GEN-LAST:event_btnSairEditarActionPerformed

    private void btnCadastrarFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncaoActionPerformed

        String funcao = null;
        funcao = JOptionPane.showInputDialog(null, "Digite o nome da função a ser cadastrada", "Atenção", JOptionPane.PLAIN_MESSAGE);
        if (funcao == null || funcao.equals("")) {
        } else {
            Class_Funcionarios funcionarios = new Class_Funcionarios();
            if (funcionarios.verificaFuncaoRepetida(funcao) == true) {
                JOptionPane.showMessageDialog(null, "Esta função já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                funcionarios.cadastrarFuncao(funcao);
                listFuncoes.setModel(funcionarios.refreshFuncoes());
            }
        }

    }//GEN-LAST:event_btnCadastrarFuncaoActionPerformed

    private void btnEditarFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncaoActionPerformed

        Object funcao = listFuncoes.getSelectedValue();
        if (funcao == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma função para editar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            String nova_funcao = null;
            nova_funcao = JOptionPane.showInputDialog(null, "Digite o novo nome da função", "Atenção", JOptionPane.PLAIN_MESSAGE);
            if (nova_funcao == null || nova_funcao.equals("")) {
            } else {
                Class_Funcionarios funcionarios = new Class_Funcionarios();
                if (funcionarios.verificaFuncaoRepetida(nova_funcao) == true && !nova_funcao.equals(funcao.toString())) {
                    JOptionPane.showMessageDialog(null, "Esta função já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    funcionarios.alterarFuncao(funcao.toString(), nova_funcao);
                    listFuncoes.setModel(funcionarios.refreshFuncoes());
                }
            }
        }

    }//GEN-LAST:event_btnEditarFuncaoActionPerformed

    private void btnExcluirFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncaoActionPerformed

        Object funcao = listFuncoes.getSelectedValue();
        if (funcao == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma função para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_Funcionarios funcionarios = new Class_Funcionarios();
            if (funcionarios.verificaFuncaoPadrao(funcao.toString()) == true) {
                JOptionPane.showMessageDialog(null, "Esta é uma função padrão e não poderá ser excluída!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else if (funcionarios.verificaFuncaoVinculadaAoFuncionario(funcionarios.retornaIdFuncao(funcao.toString())) == true) {
                JOptionPane.showMessageDialog(null, "Esta função está vinculada a um funcionário e não poderá ser excluída!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                funcionarios.excluirFuncao(funcao.toString());
            }
        }

    }//GEN-LAST:event_btnExcluirFuncaoActionPerformed

    private void btnSairFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairFuncaoActionPerformed

        funcoes.dispose();

    }//GEN-LAST:event_btnSairFuncaoActionPerformed

    private void listFuncionariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFuncionariosValueChanged
        
        if (listFuncionarios.getSelectedValue() != null) {
            int id_funcionario = Integer.valueOf(arrayList.get(listFuncionarios.getSelectedIndex()).toString());
            Class_Funcionarios funcionarios = new Class_Funcionarios();
            ArrayList array = funcionarios.carregaDadosFuncionario(id_funcionario);
            txtNome.setText(array.get(0).toString());
            txtNascimento.setText(array.get(1).toString());
            txtRG.setText(array.get(2).toString());
            txtCPF.setText(array.get(3).toString());
            txtEmail.setText(array.get(4).toString());
            txtTelefone.setText(array.get(5).toString());
            txtCelular.setText(array.get(6).toString());
            txtFuncao.setText(array.get(7).toString());
            txtCEP.setText(array.get(8).toString());
            txtEndereco.setText(array.get(9).toString());
            txtBairro.setText(array.get(10).toString());
            txtCidade.setText(array.get(11).toString());
            txtEstado.setText(array.get(12).toString());
            txtPais.setText(array.get(13).toString());
        } else {
            txtNome.setText("");
            txtNascimento.setText("");
            txtRG.setText("");
            txtCPF.setText("");
            txtEmail.setText("");
            txtTelefone.setText("");
            txtCelular.setText("");
            txtFuncao.setText("");
            txtCEP.setText("");
            txtEndereco.setText("");
            txtBairro.setText("");
            txtCidade.setText("");
            txtEstado.setText("");
            txtPais.setText("");
        }
        
    }//GEN-LAST:event_listFuncionariosValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Funcionários   ");
        painel_principal.remove(index);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFuncao;
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnEditarFuncao;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirFuncao;
    private javax.swing.JButton btnFuncoes;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarFuncionarios;
    private javax.swing.JButton btnSairCadastro;
    private javax.swing.JButton btnSairEditar;
    private javax.swing.JButton btnSairFuncao;
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JComboBox comboFuncaoEditar;
    private javax.swing.JComboBox comboFuncaoNovoCadastro;
    private javax.swing.JDialog editar_funcionario;
    private javax.swing.JDialog funcoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblIdadeFuncionarioCadastrar;
    private javax.swing.JLabel lblIdadeFuncionarioEditar;
    private javax.swing.JList listFuncionarios;
    private javax.swing.JList listFuncoes;
    private javax.swing.JDialog novo_funcionario;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairroCadastrar;
    private javax.swing.JTextField txtBairroEditar;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCEPCadastrar;
    private javax.swing.JFormattedTextField txtCEPEditar;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JFormattedTextField txtCPFCadastrar;
    private javax.swing.JFormattedTextField txtCPFEditar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCelularCadastrar;
    private javax.swing.JTextField txtCelularEditar;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeCadastrar;
    private javax.swing.JTextField txtCidadeEditar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailEditar;
    private javax.swing.JTextField txtEmailNovoCadastro;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnderecoCadastrar;
    private javax.swing.JTextField txtEnderecoEditar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoCadastrar;
    private javax.swing.JTextField txtEstadoEditar;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JFormattedTextField txtNascimentoCadastrar;
    private javax.swing.JFormattedTextField txtNascimentoEditar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCadastrar;
    private javax.swing.JTextField txtNomeEditar;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPaisCadastrar;
    private javax.swing.JTextField txtPaisEditar;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRGEditar;
    private javax.swing.JTextField txtRgCadastrar;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneCadastrar;
    private javax.swing.JTextField txtTelefoneEditar;
    // End of variables declaration//GEN-END:variables
}
