
package centros_custo;

import formas_pagamento.Class_Formas_Pagto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.ListModel;
import principal.Class_Consumir_Letras;
import principal.Class_Troca_Virgula_Por_Ponto;
import principal.Class_Verifica_Menu_Aberto;
import usuarios.Class_Usuarios;

public class Painel_Gerenciar_Centros_Custo extends javax.swing.JPanel {
    
    JTabbedPane painel_principal;
    int id_usuario;
    String nome_usuario, id_centro_custo;

    public Painel_Gerenciar_Centros_Custo(JTabbedPane painel_principal, int id_usuario, String nome_usuario) {
        initComponents();
        
        this.painel_principal = painel_principal;
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
    }
    
    public void refreshCentros() {
        Class_Centros_Custo centro_custo = new Class_Centros_Custo();
        lista_centros_custo.setModel(centro_custo.carregaLista());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo_Centro_Custo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeCentro1 = new javax.swing.JTextField();
        btnSalvarCentroCusto = new javax.swing.JButton();
        btnSairCadastroCentroCusto = new javax.swing.JButton();
        btnLimparDadosCentroCusto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        radioCaixa = new javax.swing.JRadioButton();
        radioContaBancaria = new javax.swing.JRadioButton();
        Alterar_Centro_Custo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeCentro2 = new javax.swing.JTextField();
        btnSalvarCentroCusto2 = new javax.swing.JButton();
        btnSairCadastroCentroCusto2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblTipoCentroCusto = new javax.swing.JLabel();
        Configurar_Responsaveis_Caixa = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_caixas = new javax.swing.JList();
        jLabel19 = new javax.swing.JLabel();
        comboUsuario = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        lblCaixaSelecionado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_responsaveis = new javax.swing.JList();
        btnSairConfiguracaoResponsaveis = new javax.swing.JButton();
        btnRetirarResponsavelCaixa = new javax.swing.JButton();
        btnAdicionarResponsavelCaixa = new javax.swing.JButton();
        Transferir_Saldo = new javax.swing.JDialog();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        lblCentroCustoTransferirSaldo = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        lblSaldoDisponivelTransferirSaldo = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtSaldoTransferirSaldo = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        comboCentroDestinoTransferirSaldo = new javax.swing.JComboBox();
        btnSalvarTransferirSaldo = new javax.swing.JButton();
        btnSairTransferirSaldo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_centros_custo = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNomeCentro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSaldoCentro = new javax.swing.JTextField();
        btnNovoCentroCusto = new javax.swing.JButton();
        btnAlterarCentrosCusto = new javax.swing.JButton();
        btnExcluirCentrosCusto = new javax.swing.JButton();
        btnSairCentrosCusto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTipoCentroCusto = new javax.swing.JTextField();
        btnTransferirSaldoCentroCusto = new javax.swing.JButton();
        btnGerenciarSetores = new javax.swing.JButton();

        Novo_Centro_Custo.setTitle("Novo cadastro");
        Novo_Centro_Custo.setModal(true);
        Novo_Centro_Custo.setResizable(false);
        Novo_Centro_Custo.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caixa registradora 24px.png"))); // NOI18N
        jLabel8.setText("Cadastrar centro de custo");
        Novo_Centro_Custo.getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 20, 420, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Nome");
        Novo_Centro_Custo.getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 90, 40, 17);

        txtNomeCentro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_Centro_Custo.getContentPane().add(txtNomeCentro1);
        txtNomeCentro1.setBounds(100, 80, 240, 30);

        btnSalvarCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarCentroCusto.setText("Salvar");
        btnSalvarCentroCusto.setToolTipText("Salvar o cadastro do centro de custo");
        btnSalvarCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCentroCustoActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(btnSalvarCentroCusto);
        btnSalvarCentroCusto.setBounds(50, 190, 100, 30);

        btnSairCadastroCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastroCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairCadastroCentroCusto.setText("Sair");
        btnSairCadastroCentroCusto.setToolTipText("Cancelar cadastro");
        btnSairCadastroCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroCentroCustoActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(btnSairCadastroCentroCusto);
        btnSairCadastroCentroCusto.setBounds(270, 190, 100, 30);

        btnLimparDadosCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimparDadosCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Limpar 16px.png"))); // NOI18N
        btnLimparDadosCentroCusto.setText("Limpar");
        btnLimparDadosCentroCusto.setToolTipText("Limpar dados e recomeçar cadastro");
        btnLimparDadosCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDadosCentroCustoActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(btnLimparDadosCentroCusto);
        btnLimparDadosCentroCusto.setBounds(160, 190, 100, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("  Tipo");
        Novo_Centro_Custo.getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 130, 40, 20);

        radioCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioCaixa.setText("Caixa");
        radioCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCaixaActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(radioCaixa);
        radioCaixa.setBounds(120, 120, 70, 40);

        radioContaBancaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioContaBancaria.setText("Conta bancária");
        radioContaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioContaBancariaActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(radioContaBancaria);
        radioContaBancaria.setBounds(200, 120, 130, 40);

        Alterar_Centro_Custo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Alterar_Centro_Custo.setTitle("Alteração de dados");
        Alterar_Centro_Custo.setModal(true);
        Alterar_Centro_Custo.setResizable(false);
        Alterar_Centro_Custo.getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caixa registradora 24px.png"))); // NOI18N
        jLabel12.setText("Alterar centro de custo");
        Alterar_Centro_Custo.getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 20, 420, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Nome");
        Alterar_Centro_Custo.getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 90, 40, 17);

        txtNomeCentro2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Alterar_Centro_Custo.getContentPane().add(txtNomeCentro2);
        txtNomeCentro2.setBounds(100, 80, 240, 30);

        btnSalvarCentroCusto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCentroCusto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarCentroCusto2.setText("Salvar");
        btnSalvarCentroCusto2.setToolTipText("Salvar alterações");
        btnSalvarCentroCusto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCentroCusto2ActionPerformed(evt);
            }
        });
        Alterar_Centro_Custo.getContentPane().add(btnSalvarCentroCusto2);
        btnSalvarCentroCusto2.setBounds(100, 170, 100, 30);

        btnSairCadastroCentroCusto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastroCentroCusto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairCadastroCentroCusto2.setText("Sair");
        btnSairCadastroCentroCusto2.setToolTipText("Cancelar alterações");
        btnSairCadastroCentroCusto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroCentroCusto2ActionPerformed(evt);
            }
        });
        Alterar_Centro_Custo.getContentPane().add(btnSairCadastroCentroCusto2);
        btnSairCadastroCentroCusto2.setBounds(210, 170, 100, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Tipo do centro de custo:");
        Alterar_Centro_Custo.getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 130, 160, 20);

        lblTipoCentroCusto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoCentroCusto.setForeground(new java.awt.Color(255, 0, 0));
        lblTipoCentroCusto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoCentroCusto.setText("Conta bancária");
        Alterar_Centro_Custo.getContentPane().add(lblTipoCentroCusto);
        lblTipoCentroCusto.setBounds(220, 130, 110, 20);

        Configurar_Responsaveis_Caixa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Configurar_Responsaveis_Caixa.setTitle("Configurar responsáveis pelo caixa");
        Configurar_Responsaveis_Caixa.setModal(true);
        Configurar_Responsaveis_Caixa.setResizable(false);
        Configurar_Responsaveis_Caixa.getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trocar usuário 24px.png"))); // NOI18N
        jLabel17.setText("Configuração dos responsáveis pelos caixas");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 30, 650, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Caixas disponíveis");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 90, 120, 17);

        lista_caixas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_caixas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista_caixas.setToolTipText("");
        lista_caixas.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_caixas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_caixas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_caixasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lista_caixas);

        Configurar_Responsaveis_Caixa.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 110, 200, 250);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Selecione um usuário para adicionar aos responsáveis");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel19);
        jLabel19.setBounds(280, 90, 350, 17);

        comboUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        comboUsuario.setToolTipText("Selecione um usuário para adicionar como responsável");
        Configurar_Responsaveis_Caixa.getContentPane().add(comboUsuario);
        comboUsuario.setBounds(280, 110, 350, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Responsáveis pelo caixa");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel20);
        jLabel20.setBounds(280, 190, 170, 17);

        lblCaixaSelecionado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCaixaSelecionado.setForeground(new java.awt.Color(255, 0, 0));
        lblCaixaSelecionado.setText("Caixa selecionado");
        Configurar_Responsaveis_Caixa.getContentPane().add(lblCaixaSelecionado);
        lblCaixaSelecionado.setBounds(450, 190, 180, 17);

        lista_responsaveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_responsaveis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista_responsaveis.setToolTipText("Responsável pelo caixa selecionado");
        lista_responsaveis.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_responsaveis.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(lista_responsaveis);

        Configurar_Responsaveis_Caixa.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(280, 210, 350, 150);

        btnSairConfiguracaoResponsaveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairConfiguracaoResponsaveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairConfiguracaoResponsaveis.setText("Sair");
        btnSairConfiguracaoResponsaveis.setToolTipText("Fechar a tela de configuração dos responsáveis pelos caixas");
        btnSairConfiguracaoResponsaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairConfiguracaoResponsaveisActionPerformed(evt);
            }
        });
        Configurar_Responsaveis_Caixa.getContentPane().add(btnSairConfiguracaoResponsaveis);
        btnSairConfiguracaoResponsaveis.setBounds(280, 410, 100, 30);

        btnRetirarResponsavelCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRetirarResponsavelCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnRetirarResponsavelCaixa.setText("Retirar");
        btnRetirarResponsavelCaixa.setToolTipText("Retirar responsáveis do caixa");
        btnRetirarResponsavelCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarResponsavelCaixaActionPerformed(evt);
            }
        });
        Configurar_Responsaveis_Caixa.getContentPane().add(btnRetirarResponsavelCaixa);
        btnRetirarResponsavelCaixa.setBounds(510, 140, 120, 30);

        btnAdicionarResponsavelCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdicionarResponsavelCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnAdicionarResponsavelCaixa.setText("Adicionar");
        btnAdicionarResponsavelCaixa.setToolTipText("Adicionar responsáveis ao caixa selecionado");
        btnAdicionarResponsavelCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarResponsavelCaixaActionPerformed(evt);
            }
        });
        Configurar_Responsaveis_Caixa.getContentPane().add(btnAdicionarResponsavelCaixa);
        btnAdicionarResponsavelCaixa.setBounds(380, 140, 120, 30);

        Transferir_Saldo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Transferir_Saldo.setTitle("Transferir saldo");
        Transferir_Saldo.setModal(true);
        Transferir_Saldo.setResizable(false);
        Transferir_Saldo.getContentPane().setLayout(null);

        jLabel64.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Transferir saldo 24px.png"))); // NOI18N
        jLabel64.setText("Transferir saldo");
        Transferir_Saldo.getContentPane().add(jLabel64);
        jLabel64.setBounds(0, 30, 540, 30);

        jLabel66.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel66.setText("O saldo sairá do centro de custo");
        Transferir_Saldo.getContentPane().add(jLabel66);
        jLabel66.setBounds(50, 90, 210, 17);

        lblCentroCustoTransferirSaldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCentroCustoTransferirSaldo.setForeground(new java.awt.Color(255, 0, 0));
        lblCentroCustoTransferirSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCentroCustoTransferirSaldo.setText("lblCentroCusto");
        Transferir_Saldo.getContentPane().add(lblCentroCustoTransferirSaldo);
        lblCentroCustoTransferirSaldo.setBounds(280, 90, 230, 17);

        jLabel68.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel68.setText("Saldo disponível do centro de custo");
        Transferir_Saldo.getContentPane().add(jLabel68);
        jLabel68.setBounds(30, 130, 240, 17);

        lblSaldoDisponivelTransferirSaldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSaldoDisponivelTransferirSaldo.setForeground(new java.awt.Color(255, 0, 0));
        lblSaldoDisponivelTransferirSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoDisponivelTransferirSaldo.setText("lblSaldoDisponivel");
        Transferir_Saldo.getContentPane().add(lblSaldoDisponivelTransferirSaldo);
        lblSaldoDisponivelTransferirSaldo.setBounds(280, 130, 230, 17);

        jLabel70.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel70.setText("Saldo a transferir em R$");
        Transferir_Saldo.getContentPane().add(jLabel70);
        jLabel70.setBounds(100, 170, 160, 17);

        txtSaldoTransferirSaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSaldoTransferirSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoTransferirSaldoKeyTyped(evt);
            }
        });
        Transferir_Saldo.getContentPane().add(txtSaldoTransferirSaldo);
        txtSaldoTransferirSaldo.setBounds(280, 160, 230, 30);

        jLabel71.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel71.setText(" Centro de custo de destino");
        Transferir_Saldo.getContentPane().add(jLabel71);
        jLabel71.setBounds(80, 210, 180, 17);

        comboCentroDestinoTransferirSaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Transferir_Saldo.getContentPane().add(comboCentroDestinoTransferirSaldo);
        comboCentroDestinoTransferirSaldo.setBounds(280, 200, 230, 30);

        btnSalvarTransferirSaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarTransferirSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarTransferirSaldo.setText("Salvar");
        btnSalvarTransferirSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTransferirSaldoActionPerformed(evt);
            }
        });
        Transferir_Saldo.getContentPane().add(btnSalvarTransferirSaldo);
        btnSalvarTransferirSaldo.setBounds(170, 280, 100, 30);

        btnSairTransferirSaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairTransferirSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairTransferirSaldo.setText("Sair");
        btnSairTransferirSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairTransferirSaldoActionPerformed(evt);
            }
        });
        Transferir_Saldo.getContentPane().add(btnSairTransferirSaldo);
        btnSairTransferirSaldo.setBounds(280, 280, 100, 30);

        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caixa registradora 24px.png"))); // NOI18N
        jLabel4.setText("Manutenção do cadastro de centros de custo");
        add(jLabel4);
        jLabel4.setBounds(0, 30, 610, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Centros de custo");
        add(jLabel5);
        jLabel5.setBounds(20, 90, 110, 17);

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lista_centros_custo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_centros_custo.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_centros_custo.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_centros_custo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_centros_custoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_centros_custo);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 220, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(200, 80, 40, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Nome");
        add(jLabel6);
        jLabel6.setBounds(300, 120, 40, 17);

        txtNomeCentro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeCentro.setEnabled(false);
        add(txtNomeCentro);
        txtNomeCentro.setBounds(350, 110, 240, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Saldo");
        add(jLabel7);
        jLabel7.setBounds(300, 200, 40, 17);

        txtSaldoCentro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSaldoCentro.setEnabled(false);
        add(txtSaldoCentro);
        txtSaldoCentro.setBounds(350, 190, 240, 30);

        btnNovoCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnNovoCentroCusto.setText("Novo");
        btnNovoCentroCusto.setToolTipText("Cadastrar novo centro de custo");
        btnNovoCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCentroCustoActionPerformed(evt);
            }
        });
        add(btnNovoCentroCusto);
        btnNovoCentroCusto.setBounds(90, 390, 100, 30);

        btnAlterarCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlterarCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnAlterarCentrosCusto.setText("Editar");
        btnAlterarCentrosCusto.setToolTipText("Alterar centro de custo existente");
        btnAlterarCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCentrosCustoActionPerformed(evt);
            }
        });
        add(btnAlterarCentrosCusto);
        btnAlterarCentrosCusto.setBounds(200, 390, 100, 30);

        btnExcluirCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirCentrosCusto.setText("Excluir");
        btnExcluirCentrosCusto.setToolTipText("Excluir centro de custo");
        btnExcluirCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCentrosCustoActionPerformed(evt);
            }
        });
        add(btnExcluirCentrosCusto);
        btnExcluirCentrosCusto.setBounds(310, 390, 100, 30);

        btnSairCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairCentrosCusto.setText("Sair");
        btnSairCentrosCusto.setToolTipText("Fechar a tela de centros de custo");
        btnSairCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCentrosCustoActionPerformed(evt);
            }
        });
        add(btnSairCentrosCusto);
        btnSairCentrosCusto.setBounds(420, 390, 100, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("  Tipo");
        add(jLabel14);
        jLabel14.setBounds(300, 160, 40, 20);

        txtTipoCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTipoCentroCusto.setEnabled(false);
        add(txtTipoCentroCusto);
        txtTipoCentroCusto.setBounds(350, 150, 240, 30);

        btnTransferirSaldoCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTransferirSaldoCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Transferir saldo 16px.png"))); // NOI18N
        btnTransferirSaldoCentroCusto.setText("Transferir saldo");
        btnTransferirSaldoCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirSaldoCentroCustoActionPerformed(evt);
            }
        });
        add(btnTransferirSaldoCentroCusto);
        btnTransferirSaldoCentroCusto.setBounds(350, 310, 240, 30);

        btnGerenciarSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGerenciarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trocar usuário 16px.png"))); // NOI18N
        btnGerenciarSetores.setText("Responsáveis por caixa");
        btnGerenciarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarSetoresActionPerformed(evt);
            }
        });
        add(btnGerenciarSetores);
        btnGerenciarSetores.setBounds(350, 270, 240, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lista_centros_custoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_centros_custoValueChanged

        Object centroCusto = lista_centros_custo.getSelectedValue();
        if (centroCusto != null) {
            Class_Centros_Custo centros_custo = new Class_Centros_Custo();
            centros_custo.carregaCentroCusto(centroCusto.toString());
            id_centro_custo = centros_custo.getIdCentroCusto();
            txtNomeCentro.setText(centros_custo.getNomeCentroCusto());
            txtTipoCentroCusto.setText(centros_custo.getTipoCentroCusto());
            txtSaldoCentro.setText(centros_custo.getSaldoCentroCusto());
        } else {
            txtNomeCentro.setText("");
            txtTipoCentroCusto.setText("");
            txtSaldoCentro.setText("");
        }

    }//GEN-LAST:event_lista_centros_custoValueChanged

    private void btnNovoCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCentroCustoActionPerformed

        txtNomeCentro1.setText("");
        Novo_Centro_Custo.setBounds(0, 0, 430, 290);
        Novo_Centro_Custo.setLocationRelativeTo(null);
        Novo_Centro_Custo.setVisible(true);
        txtNomeCentro1.grabFocus();

    }//GEN-LAST:event_btnNovoCentroCustoActionPerformed

    private void btnAlterarCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCentrosCustoActionPerformed

        Object centro_custo = lista_centros_custo.getSelectedValue();
        if (centro_custo == null) {
            JOptionPane.showMessageDialog(null, "Selecione um centro de custo para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            txtNomeCentro2.setText(txtNomeCentro.getText());
            lblTipoCentroCusto.setText(txtTipoCentroCusto.getText());
            Alterar_Centro_Custo.setBounds(0, 0, 420, 250);
            Alterar_Centro_Custo.setLocationRelativeTo(null);
            Alterar_Centro_Custo.setVisible(true);
            txtNomeCentro2.grabFocus();
        }

    }//GEN-LAST:event_btnAlterarCentrosCustoActionPerformed

    private void btnExcluirCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCentrosCustoActionPerformed

        Object centro_custo = lista_centros_custo.getSelectedValue();
        if (centro_custo == null) {
            JOptionPane.showMessageDialog(null, "Selecione um centro de custo para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if (txtTipoCentroCusto.getText().equals("Caixa")) {
                Class_Caixa caixa = new Class_Caixa();
                int id_caixa = caixa.getIdCaixa(Integer.valueOf(id_centro_custo));
                if (caixa.verificaCaixaAberto(id_caixa) == true) {
                    JOptionPane.showMessageDialog(null, "Este centro de estoque é um caixa e se encontra aberto!\nFeche o caixa antes de excluí-lo!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    Class_Troca_Virgula_Por_Ponto troca = new Class_Troca_Virgula_Por_Ponto();
                    if (troca.trocaVirgulaPorPonto(txtSaldoCentro.getText().replace("R$ ", "")) > 0) {
                        JOptionPane.showMessageDialog(null, "Este centro de custo possui saldo! Retire o saldo antes de excluí-lo!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    } else if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                        Class_Centros_Custo centros_custo = new Class_Centros_Custo();
                        centros_custo.exclui(id_centro_custo);
                        lista_centros_custo.setModel(centros_custo.carregaLista());

                    }
                }
            } else {
                Class_Troca_Virgula_Por_Ponto troca = new Class_Troca_Virgula_Por_Ponto();
                if (troca.trocaVirgulaPorPonto(txtSaldoCentro.getText()) > 0) {
                    JOptionPane.showMessageDialog(null, "Este centro de custo possui saldo! Retire o saldo antes de excluí-lo!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    Class_Centros_Custo centros_custo = new Class_Centros_Custo();
                    centros_custo.exclui(id_centro_custo);
                    lista_centros_custo.setModel(centros_custo.carregaLista());

                }
            }
        }

    }//GEN-LAST:event_btnExcluirCentrosCustoActionPerformed

    private void btnSairCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCentrosCustoActionPerformed

        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Gestão dos centros de custo   ");
        painel_principal.remove(index);

    }//GEN-LAST:event_btnSairCentrosCustoActionPerformed

    private void btnTransferirSaldoCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirSaldoCentroCustoActionPerformed

        Object centro = lista_centros_custo.getSelectedValue();
        if (centro == null) {
            JOptionPane.showMessageDialog(null, "Selecione um centro de estoque para transferir o saldo!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            lblCentroCustoTransferirSaldo.setText(centro.toString());
            lblSaldoDisponivelTransferirSaldo.setText(txtSaldoCentro.getText());
            txtSaldoTransferirSaldo.setText("");
            Class_Centros_Custo centros = new Class_Centros_Custo();
            centros.retornaCentrosCustoComboBoxComExcessao(comboCentroDestinoTransferirSaldo, centro.toString());

            Transferir_Saldo.setBounds(0, 0, 540, 360);
            Transferir_Saldo.setLocationRelativeTo(null);
            Transferir_Saldo.setVisible(true);
        }

    }//GEN-LAST:event_btnTransferirSaldoCentroCustoActionPerformed

    private void btnSalvarCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCentroCustoActionPerformed

        if (txtNomeCentro1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeCentro1.grabFocus();
        } else if (!radioCaixa.isSelected() && !radioContaBancaria.isSelected()) {
            JOptionPane.showMessageDialog(null, "Selecione o tipo do centro de custo!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            String tipo;
            if (radioCaixa.isSelected()) {
                tipo = "Caixa";
            } else {
                tipo = "Conta bancária";
            }
            Class_Centros_Custo centro_custo = new Class_Centros_Custo();
            centro_custo.Cadastra(txtNomeCentro1.getText(), tipo);
            Novo_Centro_Custo.dispose();
            lista_centros_custo.setModel(centro_custo.carregaLista());
            txtNomeCentro.setText("");
            txtTipoCentroCusto.setText("");
            txtSaldoCentro.setText("");
        }

    }//GEN-LAST:event_btnSalvarCentroCustoActionPerformed

    private void btnSairCadastroCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroCentroCustoActionPerformed

        Novo_Centro_Custo.dispose();

    }//GEN-LAST:event_btnSairCadastroCentroCustoActionPerformed

    private void btnLimparDadosCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDadosCentroCustoActionPerformed

        txtNomeCentro1.setText("");
        radioCaixa.setSelected(false);
        radioContaBancaria.setSelected(false);
        txtNomeCentro1.grabFocus();

    }//GEN-LAST:event_btnLimparDadosCentroCustoActionPerformed

    private void radioCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCaixaActionPerformed

        radioContaBancaria.setSelected(false);

    }//GEN-LAST:event_radioCaixaActionPerformed

    private void radioContaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioContaBancariaActionPerformed

        radioCaixa.setSelected(false);

    }//GEN-LAST:event_radioContaBancariaActionPerformed

    private void btnSalvarCentroCusto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCentroCusto2ActionPerformed

        if (txtNomeCentro2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeCentro2.grabFocus();
        } else {
            Class_Centros_Custo centro_custo = new Class_Centros_Custo();
            centro_custo.edita(id_centro_custo, txtNomeCentro2.getText());
            Alterar_Centro_Custo.dispose();
            lista_centros_custo.setModel(centro_custo.carregaLista());
            txtNomeCentro.setText("");
            txtTipoCentroCusto.setText("");
            txtSaldoCentro.setText("");
        }

    }//GEN-LAST:event_btnSalvarCentroCusto2ActionPerformed

    private void btnSairCadastroCentroCusto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroCentroCusto2ActionPerformed

        Alterar_Centro_Custo.dispose();

    }//GEN-LAST:event_btnSairCadastroCentroCusto2ActionPerformed

    private void txtSaldoTransferirSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoTransferirSaldoKeyTyped

        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        cons.consome("1234567890,.", evt);

    }//GEN-LAST:event_txtSaldoTransferirSaldoKeyTyped

    private void btnSalvarTransferirSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTransferirSaldoActionPerformed

        if (txtSaldoTransferirSaldo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o saldo a ser transferido!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtSaldoTransferirSaldo.grabFocus();
        } else {
            Class_Troca_Virgula_Por_Ponto troca = new Class_Troca_Virgula_Por_Ponto();
            float inicial = troca.trocaVirgulaPorPonto(lblSaldoDisponivelTransferirSaldo.getText().replace("R$ ", ""));
            float transferir = troca.trocaVirgulaPorPonto(txtSaldoTransferirSaldo.getText());
            if (inicial < transferir) {
                JOptionPane.showMessageDialog(null, "O valor a transferir não pode ser maior que o valor disponível!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                Class_Centros_Custo centros = new Class_Centros_Custo();
                Class_Caixa caixa = new Class_Caixa();
                Class_Conta_Bancaria conta = new Class_Conta_Bancaria();
                Class_Formas_Pagto formas = new Class_Formas_Pagto();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");

                int id_caixa, id_forma = formas.retornaIdFormaPagamento("Dinheiro");
                float valor_transferir = troca.trocaVirgulaPorPonto(txtSaldoTransferirSaldo.getText());
                String data_transferencia = sdf.format(new Date());

                String centro_sair = lblCentroCustoTransferirSaldo.getText();
                String centro_entrar = comboCentroDestinoTransferirSaldo.getSelectedItem().toString();

                //debitamos do centro inicial
                int id_centro = centros.retornaIdCentroCusto(centro_sair);
                centros.alteraSaldoCentroCusto("Despesa", "0,00", txtSaldoTransferirSaldo.getText(), id_centro);

                //agora devemos adicionar a movimentacao no centro de custo
                if (centros.retornaTipoCentroCusto(centro_sair).equals("Caixa")) {
                    id_caixa = caixa.getIdCaixa(id_centro);
                    caixa.registraMovimentacaoCaixa(id_caixa, "Sangria", id_forma, 1, valor_transferir, "Transferência", id_usuario,
                        data_transferencia);
                } else {
                    conta.registraMovimentacaoContaBancaria(id_centro, "Sangria", id_forma, 1, valor_transferir, "Transferência",
                        id_usuario, data_transferencia);
                }

                //acrescentamos no centro de destino
                id_centro = centros.retornaIdCentroCusto(centro_entrar);
                centros.alteraSaldoCentroCusto("Receita", "0,00", txtSaldoTransferirSaldo.getText(), id_centro);

                //acrescentamos a movimentacao no centro de custo
                if (centros.retornaTipoCentroCusto(centro_entrar).equals("Caixa")) {
                    id_caixa = caixa.getIdCaixa(id_centro);
                    caixa.registraMovimentacaoCaixa(id_caixa, "Saldo vindo do centro de custo "+centro_sair, id_forma, 1,
                        valor_transferir, "Transferência", id_usuario, data_transferencia);
                } else {
                    conta.registraMovimentacaoContaBancaria(id_centro, "Saldo vindo do centro de custo "+centro_sair, id_forma,
                        1, valor_transferir, "Transferência", id_usuario, data_transferencia);
                }

                JOptionPane.showMessageDialog(null, "Saldo transferido com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                Transferir_Saldo.dispose();
                Class_Centros_Custo centro_custo = new Class_Centros_Custo();
                lista_centros_custo.setModel(centro_custo.carregaLista());
            }
        }

    }//GEN-LAST:event_btnSalvarTransferirSaldoActionPerformed

    private void btnSairTransferirSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTransferirSaldoActionPerformed

        Transferir_Saldo.dispose();

    }//GEN-LAST:event_btnSairTransferirSaldoActionPerformed

    private void btnGerenciarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarSetoresActionPerformed
        
        Class_Centros_Custo centros = new Class_Centros_Custo();
        lista_caixas.setModel(centros.refreshCaixas());
        comboUsuario.removeAllItems();
        comboUsuario.addItem("<Selecione>");
        Class_Usuarios usuarios = new Class_Usuarios();
        usuarios.carregaUsuariosNormaisComboBox(comboUsuario);
        comboUsuario.setSelectedIndex(0);
        lblCaixaSelecionado.setVisible(false);
        Configurar_Responsaveis_Caixa.setBounds(0, 0, 660, 490);
        Configurar_Responsaveis_Caixa.setLocationRelativeTo(null);
        Configurar_Responsaveis_Caixa.setVisible(true);
        
    }//GEN-LAST:event_btnGerenciarSetoresActionPerformed

    private void lista_caixasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_caixasValueChanged

        Object caixa1 = lista_caixas.getSelectedValue();
        if (caixa1 == null) {
            lista_caixas.setSelectedIndex(0);
        }
        lblCaixaSelecionado.setVisible(true);
        String nome_caixa = lista_caixas.getSelectedValue().toString();
        lblCaixaSelecionado.setText(nome_caixa);
        Class_Caixa caixa = new Class_Caixa();
        lista_responsaveis.setModel(caixa.carregaResponsaveisCaixa(nome_caixa));

    }//GEN-LAST:event_lista_caixasValueChanged

    private void btnSairConfiguracaoResponsaveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairConfiguracaoResponsaveisActionPerformed

        Configurar_Responsaveis_Caixa.dispose();

    }//GEN-LAST:event_btnSairConfiguracaoResponsaveisActionPerformed

    private void btnRetirarResponsavelCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarResponsavelCaixaActionPerformed

        Object responsavel = lista_responsaveis.getSelectedValue();
        if (responsavel == null) {
            JOptionPane.showMessageDialog(null, "Selecione o responsável na lista abaixo para retirar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_Usuarios usuarios = new Class_Usuarios();
            int id_usuario = usuarios.getIdUsuario(responsavel.toString());
            Class_Centros_Custo centros = new Class_Centros_Custo();
            int id_centro_custo = centros.retornaIdCentroCusto(lista_caixas.getSelectedValue().toString());
            Class_Caixa caixa = new Class_Caixa();
            caixa.retiraResponsavelCaixa(id_centro_custo, id_usuario);
            lista_responsaveis.setModel(caixa.carregaResponsaveisCaixa(lista_caixas.getSelectedValue().toString()));
        }

    }//GEN-LAST:event_btnRetirarResponsavelCaixaActionPerformed

    private void btnAdicionarResponsavelCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarResponsavelCaixaActionPerformed

        if (lista_caixas.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o caixa desejado para adicionar os responsáveis!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if (comboUsuario.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Selecione o usuário para adicionar aos responsáveis!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                ListModel lista = lista_responsaveis.getModel();
                String responsavel = comboUsuario.getSelectedItem().toString();
                boolean flag = false;
                for (int i = 0; i < lista.getSize(); i++) {
                    if (responsavel.equals(lista.getElementAt(i).toString())) {
                        flag = true;
                    }
                }
                if (flag == true) {
                    JOptionPane.showMessageDialog(null, "Este usuário já é responsável por este caixa!\nNão é preciso definí-lo novamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    Class_Usuarios usuarios = new Class_Usuarios();
                    int id_usuario = usuarios.getIdUsuario(responsavel);
                    Class_Centros_Custo centros = new Class_Centros_Custo();
                    int id_centro_custo = centros.retornaIdCentroCusto(lista_caixas.getSelectedValue().toString());
                    Class_Caixa caixa = new Class_Caixa();
                    caixa.adicionaResponsavelCaixa(id_centro_custo, id_usuario);
                    lista_responsaveis.setModel(caixa.carregaResponsaveisCaixa(lista_caixas.getSelectedValue().toString()));
                }
            }
        }

    }//GEN-LAST:event_btnAdicionarResponsavelCaixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Alterar_Centro_Custo;
    private javax.swing.JDialog Configurar_Responsaveis_Caixa;
    private javax.swing.JDialog Novo_Centro_Custo;
    private javax.swing.JDialog Transferir_Saldo;
    private javax.swing.JButton btnAdicionarResponsavelCaixa;
    private javax.swing.JButton btnAlterarCentrosCusto;
    private javax.swing.JButton btnExcluirCentrosCusto;
    private javax.swing.JButton btnGerenciarSetores;
    private javax.swing.JButton btnLimparDadosCentroCusto;
    private javax.swing.JButton btnNovoCentroCusto;
    private javax.swing.JButton btnRetirarResponsavelCaixa;
    private javax.swing.JButton btnSairCadastroCentroCusto;
    private javax.swing.JButton btnSairCadastroCentroCusto2;
    private javax.swing.JButton btnSairCentrosCusto;
    private javax.swing.JButton btnSairConfiguracaoResponsaveis;
    private javax.swing.JButton btnSairTransferirSaldo;
    private javax.swing.JButton btnSalvarCentroCusto;
    private javax.swing.JButton btnSalvarCentroCusto2;
    private javax.swing.JButton btnSalvarTransferirSaldo;
    private javax.swing.JButton btnTransferirSaldoCentroCusto;
    private javax.swing.JComboBox comboCentroDestinoTransferirSaldo;
    private javax.swing.JComboBox comboUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCaixaSelecionado;
    private javax.swing.JLabel lblCentroCustoTransferirSaldo;
    private javax.swing.JLabel lblSaldoDisponivelTransferirSaldo;
    private javax.swing.JLabel lblTipoCentroCusto;
    private javax.swing.JList lista_caixas;
    private javax.swing.JList lista_centros_custo;
    private javax.swing.JList lista_responsaveis;
    private javax.swing.JRadioButton radioCaixa;
    private javax.swing.JRadioButton radioContaBancaria;
    private javax.swing.JTextField txtNomeCentro;
    private javax.swing.JTextField txtNomeCentro1;
    private javax.swing.JTextField txtNomeCentro2;
    private javax.swing.JTextField txtSaldoCentro;
    private javax.swing.JTextField txtSaldoTransferirSaldo;
    private javax.swing.JTextField txtTipoCentroCusto;
    // End of variables declaration//GEN-END:variables
}
