
package compras;

import java.awt.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Painel_compra extends javax.swing.JPanel {

    /**
     * Creates new form Painel_compra
     */
    public Painel_compra() {
        initComponents();
    }
    
    public void refreshTable(){
        Class_compra resolve = new Class_compra();
        resolve.carregaTabela((DefaultTableModel) tabela_compra.getModel());
    }
    
    public void refreshTotalCompra(){

        float total = 0;

        for(int i =0; i<tabela_produtos_compra.getRowCount();i++){
            total = ( (float) tabela_produtos_compra.getValueAt(i,3) ) + total;      
        }
        
        lbl_total_compra.setText(String.valueOf(total));
        
    }
    
    public void refreshCampos(String codigo){
        Class_compra carrega = new Class_compra();
        carrega.carregaDados(codigo);
        codigo_compra.setText(carrega.getId_compra());
        descricao_compra.setText(carrega.getDescricao());
        fornecedor_compra.setText(carrega.getFornecedor());
        data_compra.setText(carrega.getData());
        numero_nota_compra.setText(carrega.getNumero_nota());
        valor_total_compra.setText(carrega.getValor());
        responsavel_compra.setText(carrega.getResponsavel());
    }
    
    public void refreshListTipo(){
        Class_compra carrega = new Class_compra();
        lista_tipo.setModel(carrega.carregaTipo());
    }
    
    public void refreshListProdutos(String tipo){
        Class_compra carrega = new Class_compra();
        lista_produto.setModel(carrega.carregaListaProduto(tipo));
    }
    
    public void refreshCombo_Fornecedor(){
        combo_fornecedor.removeAllItems();
        List lista;
         Class_compra resolve = new Class_compra();
        lista = resolve.carrega_Fornecedor();
        
        for(int i=0;i<lista.getItemCount();i++){
            combo_fornecedor.addItem(lista.getItem(i));
        }
    }
    
    public void refreshCombo_num_parcelas(){
        combo_num_parcelas.removeAllItems();
        for(int i=1;i<12;i++){
            combo_num_parcelas.addItem(i);
        }
    }
    
    public void refreshCombo_formas_pagamento(){
        combo_forma_pagamento.removeAllItems();
        List lista;
         Class_compra resolve = new Class_compra();
        lista = resolve.carrega_Formas_pagamento();
        
        for(int i=0;i<lista.getItemCount();i++){
            combo_forma_pagamento.addItem(lista.getItem(i));
        }
    }
    
    public void refreshCombo_centros_estoque(){
        combo_centro.removeAllItems();
        List lista;
         Class_compra resolve = new Class_compra();
        lista = resolve.carrega_Centros_estoque();
        
        for(int i=0;i<lista.getItemCount();i++){
            combo_centro.addItem(lista.getItem(i));
        }
    }
    
    public void refreshFormaPagamento(){
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("A vista");
        listModel.addElement("Cartao");
        listModel.addElement("Parcelado");
        listModel.addElement("Boleto");
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nova_compra = new javax.swing.JDialog();
        descricao_nova = new javax.swing.JTextField();
        combo_fornecedor = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        data_comprado = new javax.swing.JTextField();
        n_nota = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_tipo = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista_produto = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produtos_compra = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_total_compra = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        qtd_unit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        valor_unitario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_centro = new javax.swing.JComboBox();
        formas_pagamento = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        lbl_total_parcelas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combo_forma_pagamento = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_parcelas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pago_primeira = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        combo_num_parcelas = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        lblProdutosCadastrados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        codigo_compra = new javax.swing.JTextField();
        descricao_compra = new javax.swing.JTextField();
        fornecedor_compra = new javax.swing.JTextField();
        numero_nota_compra = new javax.swing.JTextField();
        data_compra = new javax.swing.JTextField();
        responsavel_compra = new javax.swing.JTextField();
        valor_total_compra = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_compra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_produtos_comprado = new javax.swing.JTable();

        nova_compra.setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        nova_compra.setMinimumSize(new java.awt.Dimension(600, 600));
        nova_compra.setModal(true);
        nova_compra.setResizable(false);
        nova_compra.getContentPane().setLayout(null);

        descricao_nova.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descricao_novaFocusGained(evt);
            }
        });
        descricao_nova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descricao_novaMouseClicked(evt);
            }
        });
        descricao_nova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricao_novaActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(descricao_nova);
        descricao_nova.setBounds(20, 30, 790, 30);

        combo_fornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_fornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_fornecedorItemStateChanged(evt);
            }
        });
        combo_fornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_fornecedorMouseClicked(evt);
            }
        });
        nova_compra.getContentPane().add(combo_fornecedor);
        combo_fornecedor.setBounds(20, 80, 380, 30);

        jLabel4.setText("Fornecedor");
        nova_compra.getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 60, 70, 14);

        data_comprado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_compradoMouseClicked(evt);
            }
        });
        data_comprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_compradoActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(data_comprado);
        data_comprado.setBounds(420, 80, 120, 30);

        n_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n_notaMouseClicked(evt);
            }
        });
        n_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_notaActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(n_nota);
        n_nota.setBounds(580, 80, 230, 30);

        lista_tipo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista_tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_tipoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lista_tipo);

        nova_compra.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(20, 150, 220, 50);

        lista_produto.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_produtoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(lista_produto);

        nova_compra.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(250, 150, 250, 50);

        jLabel10.setText("Tipo");
        nova_compra.getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 130, 20, 14);

        jLabel11.setText("Produto");
        nova_compra.getContentPane().add(jLabel11);
        jLabel11.setBounds(250, 130, 38, 14);

        jLabel3.setText("Descrição da compra");
        nova_compra.getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 4, 150, 20);

        jLabel5.setText("Data");
        nova_compra.getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 60, 50, 20);

        jLabel6.setText("Nº da nota");
        nova_compra.getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 60, 80, 20);

        jButton5.setText("Adcionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(jButton5);
        jButton5.setBounds(730, 150, 80, 50);

        tabela_produtos_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Valor unitario", "Total", "Centro de Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_produtos_compra);
        if (tabela_produtos_compra.getColumnModel().getColumnCount() > 0) {
            tabela_produtos_compra.getColumnModel().getColumn(0).setMaxWidth(500);
            tabela_produtos_compra.getColumnModel().getColumn(1).setMaxWidth(100);
            tabela_produtos_compra.getColumnModel().getColumn(2).setMaxWidth(100);
            tabela_produtos_compra.getColumnModel().getColumn(3).setMaxWidth(100);
            tabela_produtos_compra.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        nova_compra.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 790, 130);

        jButton6.setText("Remover produto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(jButton6);
        jButton6.setBounds(20, 430, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Total: R$");
        nova_compra.getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 430, 80, 22);

        lbl_total_compra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_total_compra.setText("0,00");
        nova_compra.getContentPane().add(lbl_total_compra);
        lbl_total_compra.setBounds(710, 430, 100, 22);

        jButton7.setText("Avançar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(jButton7);
        jButton7.setBounds(20, 480, 120, 50);

        jButton8.setText("Fechar");
        nova_compra.getContentPane().add(jButton8);
        jButton8.setBounds(690, 480, 120, 50);

        jLabel16.setText("Quantidade");
        nova_compra.getContentPane().add(jLabel16);
        jLabel16.setBounds(510, 130, 70, 14);

        qtd_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtd_unitActionPerformed(evt);
            }
        });
        nova_compra.getContentPane().add(qtd_unit);
        qtd_unit.setBounds(510, 150, 100, 30);

        jLabel17.setText("Valor unitario");
        nova_compra.getContentPane().add(jLabel17);
        jLabel17.setBounds(620, 130, 70, 14);
        nova_compra.getContentPane().add(valor_unitario);
        valor_unitario.setBounds(620, 150, 90, 30);

        jLabel8.setText("Centro de estoque");
        nova_compra.getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 210, 110, 20);

        combo_centro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nova_compra.getContentPane().add(combo_centro);
        combo_centro.setBounds(20, 230, 220, 30);

        formas_pagamento.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Valor da compra:  R$");
        formas_pagamento.getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 10, 170, 40);

        lbl_total_parcelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_total_parcelas.setText("0,00");
        formas_pagamento.getContentPane().add(lbl_total_parcelas);
        lbl_total_parcelas.setBounds(190, 10, 50, 40);

        jLabel13.setText("Forma de pagamento");
        formas_pagamento.getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 50, 130, 20);

        combo_forma_pagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        formas_pagamento.getContentPane().add(combo_forma_pagamento);
        combo_forma_pagamento.setBounds(10, 80, 370, 20);

        table_parcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Parcela", "Valor", "Liquidada", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table_parcelas);

        formas_pagamento.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 180, 370, 290);

        jLabel14.setText("Nº parcelas");
        formas_pagamento.getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 120, 90, 14);

        jLabel15.setText("Pago na primeira parcela");
        formas_pagamento.getContentPane().add(jLabel15);
        jLabel15.setBounds(120, 120, 118, 14);
        formas_pagamento.getContentPane().add(pago_primeira);
        pago_primeira.setBounds(120, 140, 120, 30);

        jButton9.setText("Voltar");
        formas_pagamento.getContentPane().add(jButton9);
        jButton9.setBounds(290, 490, 90, 40);

        jButton10.setText("Finalizar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        formas_pagamento.getContentPane().add(jButton10);
        jButton10.setBounds(10, 490, 90, 40);

        jButton11.setText("Confirma");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        formas_pagamento.getContentPane().add(jButton11);
        jButton11.setBounds(250, 140, 90, 30);

        combo_num_parcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_num_parcelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_num_parcelasItemStateChanged(evt);
            }
        });
        formas_pagamento.getContentPane().add(combo_num_parcelas);
        combo_num_parcelas.setBounds(10, 140, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setLayout(null);

        lblProdutosCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProdutosCadastrados.setText("Compras cadastradas");
        add(lblProdutosCadastrados);
        lblProdutosCadastrados.setBounds(20, 100, 160, 17);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manutenção do cadastro de compras");
        add(jLabel1);
        jLabel1.setBounds(0, 30, 600, 29);

        codigo_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigo_compra.setEnabled(false);
        codigo_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_compraActionPerformed(evt);
            }
        });
        add(codigo_compra);
        codigo_compra.setBounds(430, 130, 160, 30);

        descricao_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descricao_compra.setEnabled(false);
        add(descricao_compra);
        descricao_compra.setBounds(430, 170, 160, 30);

        fornecedor_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fornecedor_compra.setEnabled(false);
        add(fornecedor_compra);
        fornecedor_compra.setBounds(430, 210, 160, 30);

        numero_nota_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        numero_nota_compra.setEnabled(false);
        add(numero_nota_compra);
        numero_nota_compra.setBounds(430, 250, 160, 30);

        data_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        data_compra.setEnabled(false);
        add(data_compra);
        data_compra.setBounds(430, 370, 160, 30);

        responsavel_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        responsavel_compra.setEnabled(false);
        add(responsavel_compra);
        responsavel_compra.setBounds(430, 330, 160, 30);

        valor_total_compra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valor_total_compra.setEnabled(false);
        add(valor_total_compra);
        valor_total_compra.setBounds(430, 290, 160, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Novo");
        jButton2.setToolTipText("Cadastrar um novo produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(240, 440, 100, 30);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Alterar");
        jButton3.setToolTipText("Alterar as informações de um produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(350, 440, 100, 30);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Excluir");
        jButton4.setToolTipText("Excluir um produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(460, 440, 100, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Sair");
        jButton1.setToolTipText("Fechar a tela de cadastro de produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(570, 440, 100, 30);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Data:");
        add(jLabel24);
        jLabel24.setBounds(370, 380, 50, 17);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Numero da nota");
        add(jLabel23);
        jLabel23.setBounds(310, 260, 110, 17);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Fornecedor");
        add(jLabel22);
        jLabel22.setBounds(340, 220, 80, 17);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Descricacao");
        add(jLabel20);
        jLabel20.setBounds(340, 180, 78, 17);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Codigo ");
        add(jLabel19);
        jLabel19.setBounds(370, 140, 50, 17);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Responsavel");
        add(jLabel25);
        jLabel25.setBounds(330, 340, 90, 17);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Valor Total");
        add(jLabel26);
        jLabel26.setBounds(350, 300, 80, 17);

        jLabel2.setText("Produtos comprados nessa compra");
        add(jLabel2);
        jLabel2.setBounds(620, 110, 180, 14);

        tabela_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descricao", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_compraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela_compra);
        if (tabela_compra.getColumnModel().getColumnCount() > 0) {
            tabela_compra.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabela_compra.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabela_compra.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        add(jScrollPane3);
        jScrollPane3.setBounds(20, 130, 280, 270);

        tabela_produtos_comprado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_produtos_comprado);
        if (tabela_produtos_comprado.getColumnModel().getColumnCount() > 0) {
            tabela_produtos_comprado.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabela_produtos_comprado.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(620, 130, 320, 270);
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_compraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DefaultListModel listModel = new DefaultListModel();
        refreshListTipo();
        refreshCombo_Fornecedor();
        refreshCombo_centros_estoque();
        refreshListProdutos("Cerveja");
        nova_compra.setBounds(0, 0, 1180, 600);
        nova_compra.setLocationRelativeTo(null);
        nova_compra.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabela_compraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_compraMouseClicked
         int linha;
        linha = tabela_compra.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tabela_compra.getModel();
        refreshCampos((String) modelo.getValueAt(linha,0));
        Class_compra amostra = new Class_compra();
        amostra.carregaProdutos_Compra((String) modelo.getValueAt(linha,0), (DefaultTableModel) tabela_produtos_comprado.getModel());
    }//GEN-LAST:event_tabela_compraMouseClicked

    private void descricao_novaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricao_novaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricao_novaActionPerformed

    private void n_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_notaActionPerformed

    private void data_compradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_compradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_compradoActionPerformed

    private void descricao_novaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricao_novaFocusGained
        
    }//GEN-LAST:event_descricao_novaFocusGained

    private void descricao_novaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descricao_novaMouseClicked
    }//GEN-LAST:event_descricao_novaMouseClicked

    private void lista_tipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_tipoMouseClicked
        refreshListProdutos((String) lista_tipo.getSelectedValue());
    }//GEN-LAST:event_lista_tipoMouseClicked

    private void data_compradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_compradoMouseClicked

    }//GEN-LAST:event_data_compradoMouseClicked

    private void n_notaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n_notaMouseClicked

    }//GEN-LAST:event_n_notaMouseClicked

    private void lista_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_produtoMouseClicked

    }//GEN-LAST:event_lista_produtoMouseClicked

    private void combo_fornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_fornecedorItemStateChanged

        
    }//GEN-LAST:event_combo_fornecedorItemStateChanged

    private void combo_fornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_fornecedorMouseClicked
       
    }//GEN-LAST:event_combo_fornecedorMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       float total;
       total = Integer.parseInt(qtd_unit.getText()) * Float.parseFloat(valor_unitario.getText());
       DefaultTableModel model = (DefaultTableModel) tabela_produtos_compra.getModel();
       model.addRow(new Object[]{lista_produto.getSelectedValue(), qtd_unit.getText(), valor_unitario.getText(), total, combo_centro.getSelectedItem()});
       refreshTotalCompra();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void qtd_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtd_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtd_unitActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabela_produtos_compra.getModel();
        model.removeRow(tabela_produtos_compra.getSelectedRow());
        refreshTotalCompra();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        lbl_total_parcelas.setText(lbl_total_compra.getText());
        refreshCombo_formas_pagamento();
        refreshCombo_num_parcelas();
        nova_compra.setVisible(false);
        formas_pagamento.setBounds(0, 0, 400, 600);
        formas_pagamento.setLocationRelativeTo(null);
        formas_pagamento.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int num_parcelas = (int) combo_num_parcelas.getSelectedItem();
        float pp_parcela = Float.parseFloat(pago_primeira.getText());
        float total = Float.parseFloat(lbl_total_parcelas.getText());;
        float parcial = 0;
        float restante = 0;
        String combo_forma_pagamento_string = (String) combo_forma_pagamento.getSelectedItem();
        
        DefaultTableModel modelo = (DefaultTableModel) table_parcelas.getModel();
        modelo.setNumRows(0);
       if(pp_parcela >= total && num_parcelas > 1){
           JOptionPane.showMessageDialog(null,"Primeira parcela Maior ou igual o valor total");
       }else{
            /*** compra com dinheiro seta a primera como true as outras nao ***/
            if(combo_forma_pagamento_string.equals("Dinheiro")){
                if(num_parcelas == 1){

                    modelo.addRow(new Object[]{1, total, true, data_comprado.getText()});
                }else{
                    parcial = total - pp_parcela;
                    modelo.addRow(new Object[]{1, pp_parcela, true, data_comprado.getText()});
                    restante = parcial/(num_parcelas-1);

                    for(int i=0;i<num_parcelas-1;i++){

                        modelo.addRow(new Object[]{i+2, restante, false, data_comprado.getText()});

                    }
                }
            } 
            /*** compra com cartao de debito só pode ser em uma parcela! ***/
            else if(combo_forma_pagamento_string.equals("Cartão de débito")){
                modelo.addRow(new Object[]{1, total, true, data_comprado.getText()});
            }
            /*** cartao de credito todas as parcelas iguais e tudo como true ***/
            else if(combo_forma_pagamento_string.contains("Cartão de crédito")){
                restante = total/num_parcelas;

                for(int i =0; i<num_parcelas;i++){
                    modelo.addRow(new Object[]{i+1, restante, true, data_comprado.getText()});
                }  
            } 
            else if(combo_forma_pagamento_string.contains("Boleto")){
                restante = total/num_parcelas;
                    modelo.addRow(new Object[]{1, restante, true, data_comprado.getText()});
                for(int i =0; i<num_parcelas-1;i++){
                    modelo.addRow(new Object[]{i+2, restante, false, data_comprado.getText()});
                } 
            }
       }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Class_compra finaliza = new Class_compra();
        finaliza.realiza_Compra(descricao_nova.getText(), 
                (String) combo_fornecedor.getSelectedItem(), 
                n_nota.getText(), data_comprado.getText(), 
                lbl_total_compra.getText(),
                (String)combo_num_parcelas.getSelectedItem().toString(), 
                (DefaultTableModel) tabela_produtos_compra.getModel(),
                (String)combo_forma_pagamento.getSelectedItem(),
                (DefaultTableModel) table_parcelas.getModel());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void combo_num_parcelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_num_parcelasItemStateChanged
        try{
        int val = (int) combo_num_parcelas.getSelectedItem();
        if(val == 1) {
            pago_primeira.setText(lbl_total_parcelas.getText());    
            pago_primeira.setEditable(false);
        }
        else{
            pago_primeira.setEditable(true);
        }
        }catch(Exception ex){
            
        }
        
    }//GEN-LAST:event_combo_num_parcelasItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo_compra;
    private javax.swing.JComboBox combo_centro;
    private javax.swing.JComboBox combo_forma_pagamento;
    private javax.swing.JComboBox combo_fornecedor;
    private javax.swing.JComboBox combo_num_parcelas;
    private javax.swing.JTextField data_compra;
    private javax.swing.JTextField data_comprado;
    private javax.swing.JTextField descricao_compra;
    private javax.swing.JTextField descricao_nova;
    private javax.swing.JDialog formas_pagamento;
    private javax.swing.JTextField fornecedor_compra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblProdutosCadastrados;
    private javax.swing.JLabel lbl_total_compra;
    private javax.swing.JLabel lbl_total_parcelas;
    private javax.swing.JList lista_produto;
    private javax.swing.JList lista_tipo;
    private javax.swing.JTextField n_nota;
    private javax.swing.JDialog nova_compra;
    private javax.swing.JTextField numero_nota_compra;
    private javax.swing.JTextField pago_primeira;
    private javax.swing.JTextField qtd_unit;
    private javax.swing.JTextField responsavel_compra;
    private javax.swing.JTable tabela_compra;
    private javax.swing.JTable tabela_produtos_compra;
    private javax.swing.JTable tabela_produtos_comprado;
    private javax.swing.JTable table_parcelas;
    private javax.swing.JTextField valor_total_compra;
    private javax.swing.JTextField valor_unitario;
    // End of variables declaration//GEN-END:variables
}
