
package produtos;

import java.text.DecimalFormat;
import principal.Class_Consumir_Letras;
import principal.Class_Verifica_Menu_Aberto;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import principal.Class_Troca_Virgula_Por_Ponto;

public class Painel_Produtos extends javax.swing.JPanel {

    protected JTabbedPane painel_principal;
    
    public Painel_Produtos(JTabbedPane painelPrincipal) {
        initComponents();
        
        this.painel_principal = painelPrincipal;
    }
    
    public void refreshList(){
        Class_produtos carrega = new Class_produtos();
        lista_produtos.setModel(carrega.carregaLista());
    }
    
    public void refreshCampos() {
        Class_produtos produtos = new Class_produtos();
        produtos.carregaProduto((String) lista_produtos.getSelectedValue());
        txtCodigoProduto.setText(produtos.getCodigo());
        txtNomeProduto.setText(produtos.getDescricao());
        txtTipoProduto.setText(produtos.getTipo());
        txtValorCompra.setText(produtos.getValor_Compra());
        txtPorcentagemVenda.setText(produtos.getPorcentagem());
        txtValorVenda.setText(produtos.getValor_Venda());
    }
    
    public void carregaEditar() {
        txtCodigoProdutoEditarCadastro.setText(txtCodigoProduto.getText());
        txtNomeProdutoEditarCadastro.setText(txtNomeProduto.getText());
        Class_produtos produtos = new Class_produtos();
        produtos.carregaSetoresComboBox(comboTipoEditarCadastro);
        comboTipoEditarCadastro.setSelectedItem(txtTipoProduto.getText());
        txtValorCompraEditarCadastro.setText(txtValorCompra.getText().replace("R$ ", ""));
        txtPorcentagemEditarCadastro.setText(txtPorcentagemVenda.getText().replace(" %", ""));
        txtValorVendaEditarCadastro.setText(txtValorVenda.getText().replace("R$ ", ""));
        txtCodigoProdutoEditarCadastro.grabFocus();
    }
    
    public void refreshPesquisa(String nome){
        Class_produtos carrega = new Class_produtos();
        DefaultListModel lista = carrega.pesquisa(nome);
        lista_produtos.setModel(lista);
    }
    
    public void limparCamposNovoCadastro() {
        txtNovaProdutoNovoCadastro.setText("");
        comboTipoNovoCadastro.setSelectedIndex(0);
        txtPorcentagemVendaNovoCadastro.setText("");
        txtCodigoProdutoNovoCadastro.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastro_produtos = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        txtCodigoProdutoNovoCadastro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNovaProdutoNovoCadastro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnSalvarCadastro = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSairCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboTipoNovoCadastro = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtPorcentagemVendaNovoCadastro = new javax.swing.JTextField();
        editar_produtos = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        txtCodigoProdutoEditarCadastro = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNomeProdutoEditarCadastro = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtValorVendaEditarCadastro = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnSalvarEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSairEditar = new javax.swing.JButton();
        comboTipoEditarCadastro = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValorCompraEditarCadastro = new javax.swing.JTextField();
        txtPorcentagemEditarCadastro = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        setores_produtos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        lblSetoresCadastrados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_setores = new javax.swing.JList();
        btnCadastrarSetores = new javax.swing.JButton();
        btnEditarSetores = new javax.swing.JButton();
        btnExcluirSetores = new javax.swing.JButton();
        btnSairSetores = new javax.swing.JButton();
        btnPesquisarSetores = new javax.swing.JButton();
        txtPesquisaSetor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_produtos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        lblProdutosCadastrados = new javax.swing.JLabel();
        btnNovoProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTipoProduto = new javax.swing.JTextField();
        txtValorVenda = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSetores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPorcentagemVenda = new javax.swing.JTextField();

        cadastro_produtos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cadastro_produtos.setTitle("Novo cadastro");
        cadastro_produtos.setModal(true);
        cadastro_produtos.setResizable(false);
        cadastro_produtos.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Código do produto");
        cadastro_produtos.getContentPane().add(jLabel15);
        jLabel15.setBounds(95, 100, 120, 17);

        txtCodigoProdutoNovoCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigoProdutoNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoNovoCadastroActionPerformed(evt);
            }
        });
        txtCodigoProdutoNovoCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoNovoCadastroKeyTyped(evt);
            }
        });
        cadastro_produtos.getContentPane().add(txtCodigoProdutoNovoCadastro);
        txtCodigoProdutoNovoCadastro.setBounds(230, 90, 170, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Nome do produto");
        cadastro_produtos.getContentPane().add(jLabel17);
        jLabel17.setBounds(104, 140, 120, 17);

        txtNovaProdutoNovoCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cadastro_produtos.getContentPane().add(txtNovaProdutoNovoCadastro);
        txtNovaProdutoNovoCadastro.setBounds(230, 130, 170, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Tipo do produto (setor)");
        cadastro_produtos.getContentPane().add(jLabel18);
        jLabel18.setBounds(66, 180, 160, 17);

        btnSalvarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarCadastro.setText("Salvar");
        btnSalvarCadastro.setToolTipText("Salvar o cadastro do produto");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });
        cadastro_produtos.getContentPane().add(btnSalvarCadastro);
        btnSalvarCadastro.setBounds(70, 280, 100, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Limpar 16px.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar os dados e recomeçar o cadastro");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        cadastro_produtos.getContentPane().add(btnLimpar);
        btnLimpar.setBounds(180, 280, 100, 30);

        btnSairCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairCadastrar.setText("Sair");
        btnSairCadastrar.setToolTipText("Cancelar o cadastro do produto");
        btnSairCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastrarActionPerformed(evt);
            }
        });
        cadastro_produtos.getContentPane().add(btnSairCadastrar);
        btnSairCadastrar.setBounds(290, 280, 100, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 24px.png"))); // NOI18N
        jLabel3.setText("Cadastrar novo produto");
        cadastro_produtos.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 30, 450, 29);

        comboTipoNovoCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboTipoNovoCadastro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        cadastro_produtos.getContentPane().add(comboTipoNovoCadastro);
        comboTipoNovoCadastro.setBounds(230, 170, 170, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Porcentagem para venda");
        cadastro_produtos.getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 170, 17);

        txtPorcentagemVendaNovoCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPorcentagemVendaNovoCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentagemVendaNovoCadastroKeyTyped(evt);
            }
        });
        cadastro_produtos.getContentPane().add(txtPorcentagemVendaNovoCadastro);
        txtPorcentagemVendaNovoCadastro.setBounds(230, 210, 170, 30);

        editar_produtos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editar_produtos.setTitle("Alteração de dados");
        editar_produtos.setModal(true);
        editar_produtos.setResizable(false);
        editar_produtos.getContentPane().setLayout(null);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Código do produto");
        editar_produtos.getContentPane().add(jLabel25);
        jLabel25.setBounds(90, 100, 130, 17);

        txtCodigoProdutoEditarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_produtos.getContentPane().add(txtCodigoProdutoEditarCadastro);
        txtCodigoProdutoEditarCadastro.setBounds(230, 90, 190, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Nome do produto");
        editar_produtos.getContentPane().add(jLabel26);
        jLabel26.setBounds(100, 140, 120, 17);

        txtNomeProdutoEditarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_produtos.getContentPane().add(txtNomeProdutoEditarCadastro);
        txtNomeProdutoEditarCadastro.setBounds(230, 130, 190, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Tipo do produto");
        editar_produtos.getContentPane().add(jLabel28);
        jLabel28.setBounds(110, 180, 110, 17);

        txtValorVendaEditarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorVendaEditarCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorVendaEditarCadastroKeyTyped(evt);
            }
        });
        editar_produtos.getContentPane().add(txtValorVendaEditarCadastro);
        txtValorVendaEditarCadastro.setBounds(230, 290, 190, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Valor de venda");
        editar_produtos.getContentPane().add(jLabel30);
        jLabel30.setBounds(110, 300, 104, 17);

        btnSalvarEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarEditar.setText("Salvar");
        btnSalvarEditar.setToolTipText("Salvar alterações");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });
        editar_produtos.getContentPane().add(btnSalvarEditar);
        btnSalvarEditar.setBounds(140, 370, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 24px.png"))); // NOI18N
        jLabel4.setText("Editar produto");
        editar_produtos.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 30, 480, 29);

        btnSairEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairEditar.setText("Sair");
        btnSairEditar.setToolTipText("Cancelar alterações");
        btnSairEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEditarActionPerformed(evt);
            }
        });
        editar_produtos.getContentPane().add(btnSairEditar);
        btnSairEditar.setBounds(250, 370, 100, 30);

        comboTipoEditarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboTipoEditarCadastro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        editar_produtos.getContentPane().add(comboTipoEditarCadastro);
        comboTipoEditarCadastro.setBounds(230, 170, 190, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText(" Valor de compra atual");
        editar_produtos.getContentPane().add(jLabel6);
        jLabel6.setBounds(67, 220, 143, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Porcentagem para venda");
        editar_produtos.getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 260, 160, 17);

        txtValorCompraEditarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorCompraEditarCadastro.setEnabled(false);
        editar_produtos.getContentPane().add(txtValorCompraEditarCadastro);
        txtValorCompraEditarCadastro.setBounds(230, 210, 190, 30);

        txtPorcentagemEditarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPorcentagemEditarCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentagemEditarCadastroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentagemEditarCadastroKeyTyped(evt);
            }
        });
        editar_produtos.getContentPane().add(txtPorcentagemEditarCadastro);
        txtPorcentagemEditarCadastro.setBounds(230, 250, 190, 30);

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisa.setText("jTextField1");
        txtPesquisa.setToolTipText("Digite para procurar um produto específico");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        setores_produtos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setores_produtos.setTitle("Gerenciamento de setores de produtos");
        setores_produtos.setModal(true);
        setores_produtos.setResizable(false);
        setores_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setores_produtosMousePressed(evt);
            }
        });
        setores_produtos.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Categoria 24px.png"))); // NOI18N
        jLabel2.setText("Gerenciamento de setores de produtos");
        setores_produtos.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 500, 30);

        lblSetoresCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSetoresCadastrados.setText("Setores cadastrados");
        setores_produtos.getContentPane().add(lblSetoresCadastrados);
        lblSetoresCadastrados.setBounds(20, 90, 150, 17);

        list_setores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        list_setores.setSelectionBackground(new java.awt.Color(204, 255, 255));
        list_setores.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(list_setores);

        setores_produtos.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 110, 200, 210);

        btnCadastrarSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnCadastrarSetores.setText("Cadastrar setor");
        btnCadastrarSetores.setToolTipText("Cadastrar novo setor");
        btnCadastrarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnCadastrarSetores);
        btnCadastrarSetores.setBounds(270, 110, 210, 30);

        btnEditarSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnEditarSetores.setText("Editar setor");
        btnEditarSetores.setToolTipText("Editar o nome do setor");
        btnEditarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnEditarSetores);
        btnEditarSetores.setBounds(270, 150, 210, 30);

        btnExcluirSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirSetores.setText("Excluir setor");
        btnExcluirSetores.setToolTipText("Excluir um setor");
        btnExcluirSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnExcluirSetores);
        btnExcluirSetores.setBounds(270, 190, 210, 30);

        btnSairSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairSetores.setText("Sair");
        btnSairSetores.setToolTipText("Sair da tela de cadastro de setores");
        btnSairSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnSairSetores);
        btnSairSetores.setBounds(270, 230, 210, 30);

        btnPesquisarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        btnPesquisarSetores.setToolTipText("Clique para pesquisar um setor específico");
        btnPesquisarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnPesquisarSetores);
        btnPesquisarSetores.setBounds(180, 80, 40, 30);

        txtPesquisaSetor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisaSetor.setToolTipText("Digite para pesquisar um setor");
        txtPesquisaSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaSetorKeyReleased(evt);
            }
        });

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        lista_produtos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_produtos.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_produtos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_produtos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_produtosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_produtos);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 230, 300);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 24px.png"))); // NOI18N
        jLabel1.setText("Manutenção do cadastro de produtos");
        add(jLabel1);
        jLabel1.setBounds(0, 40, 670, 29);

        lblProdutosCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProdutosCadastrados.setText("Produtos cadastrados");
        add(lblProdutosCadastrados);
        lblProdutosCadastrados.setBounds(20, 100, 160, 17);

        btnNovoProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnNovoProduto.setText("Novo");
        btnNovoProduto.setToolTipText("Cadastrar um novo produto");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });
        add(btnNovoProduto);
        btnNovoProduto.setBounds(120, 470, 100, 30);

        btnEditarProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnEditarProduto.setText("Editar");
        btnEditarProduto.setToolTipText("Alterar as informações de um produto");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });
        add(btnEditarProduto);
        btnEditarProduto.setBounds(230, 470, 100, 30);

        btnExcluirProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.setToolTipText("Excluir um produto");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });
        add(btnExcluirProduto);
        btnExcluirProduto.setBounds(340, 470, 100, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Código do produto");
        add(jLabel19);
        jLabel19.setBounds(340, 130, 120, 17);

        txtCodigoProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigoProduto.setEnabled(false);
        add(txtCodigoProduto);
        txtCodigoProduto.setBounds(480, 120, 160, 30);

        txtNomeProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeProduto.setEnabled(false);
        add(txtNomeProduto);
        txtNomeProduto.setBounds(480, 160, 160, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Nome do produto");
        add(jLabel20);
        jLabel20.setBounds(350, 170, 110, 17);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("  Tipo do produto");
        add(jLabel22);
        jLabel22.setBounds(350, 210, 110, 17);

        txtTipoProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTipoProduto.setEnabled(false);
        add(txtTipoProduto);
        txtTipoProduto.setBounds(480, 200, 160, 30);

        txtValorVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorVenda.setEnabled(false);
        add(txtValorVenda);
        txtValorVenda.setBounds(480, 320, 160, 30);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Valor de venda");
        add(jLabel24);
        jLabel24.setBounds(360, 330, 104, 17);

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Fechar a tela de cadastro de produtos");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        add(btnSair);
        btnSair.setBounds(450, 470, 100, 30);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        btnPesquisa.setToolTipText("Clique para procurar um produto específico");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        add(btnPesquisa);
        btnPesquisa.setBounds(210, 90, 40, 30);

        btnSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Categoria 16px.png"))); // NOI18N
        btnSetores.setText("Gerenciar setores");
        btnSetores.setToolTipText("Clique para cadastrar os setores dos produtos");
        btnSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetoresActionPerformed(evt);
            }
        });
        add(btnSetores);
        btnSetores.setBounds(440, 390, 200, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText(" Valor de compra");
        add(jLabel7);
        jLabel7.setBounds(350, 250, 110, 14);

        txtValorCompra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorCompra.setEnabled(false);
        add(txtValorCompra);
        txtValorCompra.setBounds(480, 240, 160, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Porcentagem para venda");
        add(jLabel8);
        jLabel8.setBounds(296, 290, 170, 17);

        txtPorcentagemVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPorcentagemVenda.setEnabled(false);
        add(txtPorcentagemVenda);
        txtPorcentagemVenda.setBounds(480, 280, 160, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoProdutoNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoNovoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoNovoCadastroActionPerformed

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        
        if(txtCodigoProdutoNovoCadastro.getText().equals("") || txtNovaProdutoNovoCadastro.getText().equals("") ||
                txtPorcentagemVendaNovoCadastro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            int flagCodigo = 0, flagNome = 0;
            Class_produtos produtos = new Class_produtos();
            
            //aqui eu verifico se o produto que estou tentando adicionar está usando o mesmo código que outros produtos que estão ativos
            if (produtos.verificaCodigoProdutosAtivos(txtCodigoProdutoNovoCadastro.getText()) == false) 
            {
                flagCodigo = 1;
            }
            
            if (flagCodigo == 0) 
            {
                JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este código! Escolha outro código!", "Atenção", JOptionPane.WARNING_MESSAGE);
                txtCodigoProdutoNovoCadastro.grabFocus();
                txtCodigoProdutoNovoCadastro.selectAll();
            }
            else
            {
                if (produtos.verificaNomeProdutos(txtNovaProdutoNovoCadastro.getText()) == true) 
                {
                    JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este nome! Escolha outro nome!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    txtNovaProdutoNovoCadastro.grabFocus();
                    txtNovaProdutoNovoCadastro.selectAll();
                } 
                else 
                {
                    flagNome = 1;
                }

                if(flagCodigo == 1 && flagNome == 1)
                {
                    //aqui eu verifico se o produto que estou tentando adicionar está usando o mesmo código que outros produtos que já foram excluidos
                    //se o produto já foi excluido e tem o mesmo código, eu o excluo e crio outro
                    if (produtos.verificaCodigoProdutosExcluidos(txtCodigoProdutoNovoCadastro.getText()) == true)
                    {
                        produtos.excluiDefinitivo(txtCodigoProdutoNovoCadastro.getText());
                    }
                    
                    int id_setor = 0;
                    if (comboTipoNovoCadastro.getSelectedIndex() != 0) {
                        id_setor = produtos.retornaIdSetor(comboTipoNovoCadastro.getSelectedItem().toString());
                    }
                    
                    Class_Troca_Virgula_Por_Ponto troca = new Class_Troca_Virgula_Por_Ponto();
                    
                    produtos.Cadastra(Integer.valueOf(txtCodigoProdutoNovoCadastro.getText()), 
                            txtNovaProdutoNovoCadastro.getText(), id_setor, 
                            troca.trocaVirgulaPorPonto(txtPorcentagemVendaNovoCadastro.getText()));
                    
                    refreshList();
                    
                    cadastro_produtos.dispose();
                }
            }
            
        }
    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        
        Class_produtos produtos = new Class_produtos();
        produtos.carregaSetoresComboBox(comboTipoNovoCadastro);
        
        limparCamposNovoCadastro();
        
        txtCodigoProdutoNovoCadastro.setText(String.valueOf(produtos.retornaMaiorIdProduto()+1));
        
        cadastro_produtos.setBounds(0, 0, 450, 400);
        cadastro_produtos.setLocationRelativeTo(null);  
        cadastro_produtos.setVisible(true);
        txtCodigoProdutoNovoCadastro.grabFocus();
        
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void lista_produtosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_produtosValueChanged
        
        refreshCampos();
        
    }//GEN-LAST:event_lista_produtosValueChanged

    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed
        
        if(txtCodigoProdutoEditarCadastro.getText().equals("") || txtNomeProdutoEditarCadastro.getText().equals("") ||
                txtValorVendaEditarCadastro.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nao pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        else {
            int flagCodigo = 0, flagNome = 0;
            Class_produtos produtos = new Class_produtos();
            if (txtCodigoProduto.getText().equals(txtCodigoProdutoEditarCadastro.getText()) == false) 
            {
                if (produtos.verificaCodigoProdutosAtivos(txtCodigoProdutoEditarCadastro.getText()) == true) 
                {
                    JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este código! Escolha outro código!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    txtCodigoProdutoEditarCadastro.grabFocus();
                    txtCodigoProdutoEditarCadastro.selectAll();
                }
                else
                {
                    flagCodigo = 1;
                }
            }
            else
            {
                flagCodigo = 1;
            }
            
            if (txtNomeProduto.getText().equals(txtNomeProdutoEditarCadastro.getText()) == false)
            {
                if (produtos.verificaNomeProdutos(txtNomeProdutoEditarCadastro.getText()) == true) 
                {
                    JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este nome! Escolha outro nome!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    txtNomeProdutoEditarCadastro.grabFocus();
                    txtNomeProdutoEditarCadastro.selectAll();
                } 
                else 
                {
                    flagNome = 1;
                }
            }
            else
            {
                flagNome = 1;
            }
            
            if (flagCodigo == 1 && flagNome == 1) 
            {
                
                int id_setor = 0;
                if (comboTipoEditarCadastro.getSelectedIndex() != 0) {
                    id_setor = produtos.retornaIdSetor(comboTipoEditarCadastro.getSelectedItem().toString());
                }
                
                Class_Troca_Virgula_Por_Ponto troca = new Class_Troca_Virgula_Por_Ponto();
                
                produtos.edita(Integer.valueOf(txtCodigoProdutoEditarCadastro.getText()), txtNomeProdutoEditarCadastro.getText(), id_setor,
                    troca.trocaVirgulaPorPonto(txtPorcentagemEditarCadastro.getText()), troca.trocaVirgulaPorPonto(txtValorVendaEditarCadastro.getText()));
                refreshList();
                editar_produtos.setVisible(false);
                
            }
        }
        
    }//GEN-LAST:event_btnSalvarEditarActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        
        if (lista_produtos.getSelectedIndex() < 0) 
        {
            JOptionPane.showMessageDialog(null, "Selecione um produto para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            carregaEditar();
            editar_produtos.setBounds(0, 0, 480, 460);
            editar_produtos.setLocationRelativeTo(null);
            editar_produtos.setVisible(true);
            txtCodigoProdutoEditarCadastro.grabFocus();
        }
        
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void btnSairEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEditarActionPerformed
        
        editar_produtos.setVisible(false);
        
    }//GEN-LAST:event_btnSairEditarActionPerformed

    private void btnSairCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastrarActionPerformed
        
        cadastro_produtos.setVisible(false);
        
    }//GEN-LAST:event_btnSairCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        limparCamposNovoCadastro();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        
        if(!txtCodigoProduto.getText().equals(""))
        {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o produto "+txtNomeProduto.getText()+"?", "Atenção", JOptionPane.YES_NO_OPTION)==0)
            {
                Class_produtos produtos = new Class_produtos();
                produtos.exclui(Integer.valueOf(txtCodigoProduto.getText()));
                refreshList();
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Produtos   ");
        painel_principal.remove(index);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        
        this.add(txtPesquisa);
        txtPesquisa.setBounds(20, 90, 180, 30);
        txtPesquisa.setVisible(true);
        txtPesquisa.setText("");
        txtPesquisa.grabFocus();
        lblProdutosCadastrados.setVisible(false);
        
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        
        refreshPesquisa(txtPesquisa.getText());
        
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void qtd_caixa_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtd_caixa_produtoKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890", evt);
        
    }//GEN-LAST:event_qtd_caixa_produtoKeyTyped

    private void qtd_caixa_produto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtd_caixa_produto2KeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890", evt);
        
    }//GEN-LAST:event_qtd_caixa_produto2KeyTyped

    private void txtValorVendaEditarCadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorVendaEditarCadastroKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_txtValorVendaEditarCadastroKeyTyped

    private void txtCodigoProdutoNovoCadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoNovoCadastroKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890", evt);
        
    }//GEN-LAST:event_txtCodigoProdutoNovoCadastroKeyTyped

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        if (!lblProdutosCadastrados.isVisible()) {
            txtPesquisa.setVisible(false);
            lblProdutosCadastrados.setVisible(true);
            refreshList();
        }
        
    }//GEN-LAST:event_formMousePressed

    private void btnSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetoresActionPerformed
        
        Class_produtos produtos = new Class_produtos();
        list_setores.setModel(produtos.carregaSetores(""));
        setores_produtos.setBounds(0, 0, 510, 380);
        setores_produtos.setLocationRelativeTo(null);
        setores_produtos.setVisible(true);
        
    }//GEN-LAST:event_btnSetoresActionPerformed

    private void btnCadastrarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSetoresActionPerformed
        
        String nome = null;
        nome = JOptionPane.showInputDialog(null, "Digite o nome do setor", "Novo cadastro", JOptionPane.PLAIN_MESSAGE);
        if (nome == null || nome.equals("")) {
        } else {
            Class_Consumir_Letras cons = new Class_Consumir_Letras();
            nome = cons.retiraLetrasEPontos(nome);
            
            if (nome.length() == 0) {
                JOptionPane.showMessageDialog(null, "É preciso digitar caracteres para cadastrar o setor!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                Class_produtos produtos = new Class_produtos();
                if (produtos.verificaNomeRepetidoSetor(nome) == true) {
                    JOptionPane.showMessageDialog(null, "Este nome já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    produtos.cadastraSetor(nome);
                    list_setores.setModel(produtos.carregaSetores(""));
                }
            }
        }
        
    }//GEN-LAST:event_btnCadastrarSetoresActionPerformed

    private void btnEditarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSetoresActionPerformed
        
        Object nome = list_setores.getSelectedValue();
        if (nome == null) {
            JOptionPane.showMessageDialog(null, "Selecione o setor para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            String novo_nome = null;
            novo_nome = JOptionPane.showInputDialog(null, "Digite o novo nome do setor", "Editar setor", JOptionPane.PLAIN_MESSAGE);
            if (novo_nome == null || novo_nome.equals("")) {
            } else {
                Class_Consumir_Letras cons = new Class_Consumir_Letras();
                novo_nome = cons.retiraLetrasEPontos(novo_nome);

                if (novo_nome.length() == 0) {
                    JOptionPane.showMessageDialog(null, "É preciso digitar caracteres para editar o setor!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    Class_produtos produtos = new Class_produtos();
                    if (produtos.verificaNomeRepetidoSetor(novo_nome) == true) {
                        JOptionPane.showMessageDialog(null, "Este nome já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    } else {
                        produtos.editaSetor(nome.toString(), novo_nome);
                        list_setores.setModel(produtos.carregaSetores(""));
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnEditarSetoresActionPerformed

    private void btnExcluirSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSetoresActionPerformed
        
        Object nome = list_setores.getSelectedValue();
        if (nome == null) {
            JOptionPane.showMessageDialog(null, "Selecione o setor para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_produtos produtos = new Class_produtos();
            int id_setor = produtos.retornaIdSetor(nome.toString());
            if (produtos.verificaProdutoVinculadoAoSetor(id_setor) == true) {
                JOptionPane.showMessageDialog(null, "Este setor está vinculado a um produto e não poderá ser excluído!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else if (produtos.verificaSetorPadrao(nome.toString()) == true) {
                JOptionPane.showMessageDialog(null, "Este é um setor padrão e não poderá ser excluído!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    produtos.excluiSetor(id_setor);
                    list_setores.setModel(produtos.carregaSetores(""));
                }
            }
        }
        
    }//GEN-LAST:event_btnExcluirSetoresActionPerformed

    private void btnSairSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairSetoresActionPerformed
        
        setores_produtosMousePressed(null);
        setores_produtos.dispose();
        
    }//GEN-LAST:event_btnSairSetoresActionPerformed

    private void btnPesquisarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSetoresActionPerformed
        
        if (lblSetoresCadastrados.isVisible()) {
            setores_produtos.add(txtPesquisaSetor);
            txtPesquisaSetor.setBounds(20, 80, 140, 30);
            txtPesquisaSetor.setText("");
            txtPesquisaSetor.grabFocus();
            lblSetoresCadastrados.setVisible(false);
        }
        
    }//GEN-LAST:event_btnPesquisarSetoresActionPerformed

    private void txtPesquisaSetorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaSetorKeyReleased
        
        Class_produtos produtos = new Class_produtos();
        list_setores.setModel(produtos.carregaSetores(txtPesquisaSetor.getText()));
        
    }//GEN-LAST:event_txtPesquisaSetorKeyReleased

    private void setores_produtosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setores_produtosMousePressed
        
        if (!lblSetoresCadastrados.isVisible()) {
            setores_produtos.remove(txtPesquisaSetor);
            lblSetoresCadastrados.setVisible(true);
            Class_produtos produtos = new Class_produtos();
            list_setores.setModel(produtos.carregaSetores(""));
        }
        
    }//GEN-LAST:event_setores_produtosMousePressed

    private void txtPorcentagemVendaNovoCadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemVendaNovoCadastroKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_txtPorcentagemVendaNovoCadastroKeyTyped

    private void txtPorcentagemEditarCadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemEditarCadastroKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_txtPorcentagemEditarCadastroKeyTyped

    private void txtPorcentagemEditarCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemEditarCadastroKeyReleased
        
        if (!txtPorcentagemEditarCadastro.getText().isEmpty()) {
            Class_Troca_Virgula_Por_Ponto troca = new Class_Troca_Virgula_Por_Ponto();
            float valor_compra = troca.trocaVirgulaPorPonto(txtValorCompraEditarCadastro.getText());
            float porcentagem = troca.trocaVirgulaPorPonto(txtPorcentagemEditarCadastro.getText());
            float valor_venda = ((valor_compra * porcentagem) / 100) + valor_compra;
            DecimalFormat dffloat = new DecimalFormat("##,###.00");
            txtValorVendaEditarCadastro.setText(dffloat.format(valor_venda));
            if (txtValorVendaEditarCadastro.getText().equals(",00")) {
                txtValorVendaEditarCadastro.setText("0,00");
            } else {
                txtPorcentagemEditarCadastro.setText("0");
            }
        }        
        
    }//GEN-LAST:event_txtPorcentagemEditarCadastroKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarSetores;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnEditarSetores;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnExcluirSetores;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPesquisarSetores;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSairCadastrar;
    private javax.swing.JButton btnSairEditar;
    private javax.swing.JButton btnSairSetores;
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JButton btnSetores;
    private javax.swing.JDialog cadastro_produtos;
    private javax.swing.JComboBox comboTipoEditarCadastro;
    private javax.swing.JComboBox comboTipoNovoCadastro;
    private javax.swing.JDialog editar_produtos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblProdutosCadastrados;
    private javax.swing.JLabel lblSetoresCadastrados;
    private javax.swing.JList list_setores;
    private javax.swing.JList lista_produtos;
    private javax.swing.JDialog setores_produtos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtCodigoProdutoEditarCadastro;
    private javax.swing.JTextField txtCodigoProdutoNovoCadastro;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNomeProdutoEditarCadastro;
    private javax.swing.JTextField txtNovaProdutoNovoCadastro;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPesquisaSetor;
    private javax.swing.JTextField txtPorcentagemEditarCadastro;
    private javax.swing.JTextField txtPorcentagemVenda;
    private javax.swing.JTextField txtPorcentagemVendaNovoCadastro;
    private javax.swing.JTextField txtTipoProduto;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtValorCompraEditarCadastro;
    private javax.swing.JTextField txtValorVenda;
    private javax.swing.JTextField txtValorVendaEditarCadastro;
    // End of variables declaration//GEN-END:variables
}
