
package produtos;

import principal.Class_Consumir_Letras;
import principal.Class_Verifica_Menu_Aberto;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

public class Painel_Produtos extends javax.swing.JPanel {

    protected JTabbedPane painel_principal;
    
    public Painel_Produtos(JTabbedPane painelPrincipal) {
        initComponents();
        
        this.painel_principal = painelPrincipal;
    }
    
    public void refreshList(){
        Class_produtos carrega = new Class_produtos();
        lista_produtos.setModel(carrega.carregaLista());
    }
    
    public void refreshCampos() {
        Class_produtos produtos = new Class_produtos();
        produtos.carregaProduto((String) lista_produtos.getSelectedValue());
        codigo_produto1.setText(produtos.getCodigo());
        nome_produto1.setText(produtos.getDescricao());
        tipo_produto1.setText(produtos.getTipo());
        valor_venda_produto1.setText(produtos.getValor_Venda());
    }
    
    public void carregaEditar(){
        Class_produtos produtos = new Class_produtos();
        produtos.carregaProduto((String) lista_produtos.getSelectedValue());
        codigo_produto2.setText(produtos.getCodigo());
        nome_produto2.setText(produtos.getDescricao());
        produtos.carregaSetoresComboBox(comboTipoEditar);
        comboTipoEditar.setSelectedItem(produtos.getTipo());
        valor_venda_produto2.setText(produtos.getValor_Venda().replace("R$ ", ""));
        codigo_produto2.grabFocus();
    }
    
    public void refreshPesquisa(String nome){
        Class_produtos carrega = new Class_produtos();
        DefaultListModel lista = carrega.pesquisa(nome);
        lista_produtos.setModel(lista);
    }
    
    public void limparCamposNovoCadastro() {
        nome_produto.setText("");
        comboTipoCadastrar.setSelectedIndex(0);
        valor_venda_produto.setText("");
        codigo_produto.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastro_produtos = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        codigo_produto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nome_produto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        valor_venda_produto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnSalvarCadastro = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSairCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboTipoCadastrar = new javax.swing.JComboBox();
        editar_produtos = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        codigo_produto2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        nome_produto2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        valor_venda_produto2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnSalvarEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSairEditar = new javax.swing.JButton();
        comboTipoEditar = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        setores_produtos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        lblSetoresCadastrados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_setores = new javax.swing.JList();
        btnCadastrarSetores = new javax.swing.JButton();
        btnEditarSetores = new javax.swing.JButton();
        btnExcluirSetores = new javax.swing.JButton();
        btnSairSetores = new javax.swing.JButton();
        btnPesquisarSetores = new javax.swing.JButton();
        txtPesquisaSetor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_produtos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        lblProdutosCadastrados = new javax.swing.JLabel();
        btnNovoProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        codigo_produto1 = new javax.swing.JTextField();
        nome_produto1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tipo_produto1 = new javax.swing.JTextField();
        valor_venda_produto1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSetores = new javax.swing.JButton();

        cadastro_produtos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cadastro_produtos.setTitle("Novo cadastro");
        cadastro_produtos.setModal(true);
        cadastro_produtos.setResizable(false);
        cadastro_produtos.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Codigo");
        cadastro_produtos.getContentPane().add(jLabel15);
        jLabel15.setBounds(110, 100, 45, 17);

        codigo_produto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigo_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_produtoActionPerformed(evt);
            }
        });
        codigo_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_produtoKeyTyped(evt);
            }
        });
        cadastro_produtos.getContentPane().add(codigo_produto);
        codigo_produto.setBounds(170, 90, 170, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Nome");
        cadastro_produtos.getContentPane().add(jLabel17);
        jLabel17.setBounds(120, 140, 44, 17);

        nome_produto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cadastro_produtos.getContentPane().add(nome_produto);
        nome_produto.setBounds(170, 130, 170, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText(" Tipo ");
        cadastro_produtos.getContentPane().add(jLabel18);
        jLabel18.setBounds(120, 180, 36, 17);

        valor_venda_produto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valor_venda_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_venda_produtoKeyTyped(evt);
            }
        });
        cadastro_produtos.getContentPane().add(valor_venda_produto);
        valor_venda_produto.setBounds(170, 210, 170, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Valor de venda");
        cadastro_produtos.getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 220, 104, 17);

        btnSalvarCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarCadastro.setText("Salvar");
        btnSalvarCadastro.setToolTipText("Salvar o cadastro do produto");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });
        cadastro_produtos.getContentPane().add(btnSalvarCadastro);
        btnSalvarCadastro.setBounds(40, 300, 100, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Limpar 16px.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar os dados e recomeçar o cadastro");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        cadastro_produtos.getContentPane().add(btnLimpar);
        btnLimpar.setBounds(150, 300, 100, 30);

        btnSairCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairCadastrar.setText("Sair");
        btnSairCadastrar.setToolTipText("Cancelar o cadastro do produto");
        btnSairCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastrarActionPerformed(evt);
            }
        });
        cadastro_produtos.getContentPane().add(btnSairCadastrar);
        btnSairCadastrar.setBounds(260, 300, 100, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 24px.png"))); // NOI18N
        jLabel3.setText("Cadastrar novo produto");
        cadastro_produtos.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 30, 397, 29);

        comboTipoCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboTipoCadastrar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        cadastro_produtos.getContentPane().add(comboTipoCadastrar);
        comboTipoCadastrar.setBounds(170, 170, 170, 30);

        editar_produtos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editar_produtos.setTitle("Alteração de dados");
        editar_produtos.setModal(true);
        editar_produtos.setResizable(false);
        editar_produtos.getContentPane().setLayout(null);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Codigo");
        editar_produtos.getContentPane().add(jLabel25);
        jLabel25.setBounds(120, 100, 53, 17);

        codigo_produto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_produtos.getContentPane().add(codigo_produto2);
        codigo_produto2.setBounds(180, 90, 160, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Nome ");
        editar_produtos.getContentPane().add(jLabel26);
        jLabel26.setBounds(130, 140, 40, 17);

        nome_produto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editar_produtos.getContentPane().add(nome_produto2);
        nome_produto2.setBounds(180, 130, 160, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText(" Tipo ");
        editar_produtos.getContentPane().add(jLabel28);
        jLabel28.setBounds(130, 180, 36, 17);

        valor_venda_produto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valor_venda_produto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_venda_produto2KeyTyped(evt);
            }
        });
        editar_produtos.getContentPane().add(valor_venda_produto2);
        valor_venda_produto2.setBounds(180, 210, 160, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Valor de venda");
        editar_produtos.getContentPane().add(jLabel30);
        jLabel30.setBounds(70, 220, 104, 17);

        btnSalvarEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar 16px.png"))); // NOI18N
        btnSalvarEditar.setText("Salvar");
        btnSalvarEditar.setToolTipText("Salvar alterações");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });
        editar_produtos.getContentPane().add(btnSalvarEditar);
        btnSalvarEditar.setBounds(100, 300, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 24px.png"))); // NOI18N
        jLabel4.setText("Editar produto");
        editar_produtos.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 30, 400, 29);

        btnSairEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairEditar.setText("Sair");
        btnSairEditar.setToolTipText("Cancelar alterações");
        btnSairEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEditarActionPerformed(evt);
            }
        });
        editar_produtos.getContentPane().add(btnSairEditar);
        btnSairEditar.setBounds(210, 300, 100, 30);

        comboTipoEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboTipoEditar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        editar_produtos.getContentPane().add(comboTipoEditar);
        comboTipoEditar.setBounds(180, 170, 160, 30);

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisa.setText("jTextField1");
        txtPesquisa.setToolTipText("Digite para procurar um produto específico");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        setores_produtos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setores_produtos.setTitle("Gerenciamento de setores de produtos");
        setores_produtos.setModal(true);
        setores_produtos.setResizable(false);
        setores_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setores_produtosMousePressed(evt);
            }
        });
        setores_produtos.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Categoria 24px.png"))); // NOI18N
        jLabel2.setText("Gerenciamento de setores de produtos");
        setores_produtos.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 500, 30);

        lblSetoresCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSetoresCadastrados.setText("Setores cadastrados");
        setores_produtos.getContentPane().add(lblSetoresCadastrados);
        lblSetoresCadastrados.setBounds(20, 90, 150, 17);

        list_setores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        list_setores.setSelectionBackground(new java.awt.Color(204, 255, 255));
        list_setores.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(list_setores);

        setores_produtos.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 110, 200, 210);

        btnCadastrarSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnCadastrarSetores.setText("Cadastrar setor");
        btnCadastrarSetores.setToolTipText("Cadastrar novo setor");
        btnCadastrarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnCadastrarSetores);
        btnCadastrarSetores.setBounds(270, 110, 210, 30);

        btnEditarSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnEditarSetores.setText("Editar setor");
        btnEditarSetores.setToolTipText("Editar o nome do setor");
        btnEditarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnEditarSetores);
        btnEditarSetores.setBounds(270, 150, 210, 30);

        btnExcluirSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirSetores.setText("Excluir setor");
        btnExcluirSetores.setToolTipText("Excluir um setor");
        btnExcluirSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnExcluirSetores);
        btnExcluirSetores.setBounds(270, 190, 210, 30);

        btnSairSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSairSetores.setText("Sair");
        btnSairSetores.setToolTipText("Sair da tela de cadastro de setores");
        btnSairSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnSairSetores);
        btnSairSetores.setBounds(270, 230, 210, 30);

        btnPesquisarSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        btnPesquisarSetores.setToolTipText("Clique para pesquisar um setor específico");
        btnPesquisarSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSetoresActionPerformed(evt);
            }
        });
        setores_produtos.getContentPane().add(btnPesquisarSetores);
        btnPesquisarSetores.setBounds(180, 80, 40, 30);

        txtPesquisaSetor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisaSetor.setToolTipText("Digite para pesquisar um setor");
        txtPesquisaSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaSetorKeyReleased(evt);
            }
        });

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        lista_produtos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_produtos.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_produtos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_produtos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_produtosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_produtos);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 230, 260);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 24px.png"))); // NOI18N
        jLabel1.setText("Manutenção do cadastro de produtos");
        add(jLabel1);
        jLabel1.setBounds(0, 40, 600, 29);

        lblProdutosCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProdutosCadastrados.setText("Produtos cadastrados");
        add(lblProdutosCadastrados);
        lblProdutosCadastrados.setBounds(20, 100, 160, 17);

        btnNovoProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnNovoProduto.setText("Novo");
        btnNovoProduto.setToolTipText("Cadastrar um novo produto");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });
        add(btnNovoProduto);
        btnNovoProduto.setBounds(80, 420, 100, 30);

        btnEditarProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnEditarProduto.setText("Editar");
        btnEditarProduto.setToolTipText("Alterar as informações de um produto");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });
        add(btnEditarProduto);
        btnEditarProduto.setBounds(190, 420, 100, 30);

        btnExcluirProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.setToolTipText("Excluir um produto");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });
        add(btnExcluirProduto);
        btnExcluirProduto.setBounds(300, 420, 100, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Codigo ");
        add(jLabel19);
        jLabel19.setBounds(350, 130, 50, 17);

        codigo_produto1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigo_produto1.setEnabled(false);
        add(codigo_produto1);
        codigo_produto1.setBounds(410, 120, 160, 30);

        nome_produto1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome_produto1.setEnabled(false);
        add(nome_produto1);
        nome_produto1.setBounds(410, 160, 160, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Nome");
        add(jLabel20);
        jLabel20.setBounds(360, 170, 36, 17);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("  Tipo ");
        add(jLabel22);
        jLabel22.setBounds(360, 210, 40, 17);

        tipo_produto1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipo_produto1.setEnabled(false);
        add(tipo_produto1);
        tipo_produto1.setBounds(410, 200, 160, 30);

        valor_venda_produto1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valor_venda_produto1.setEnabled(false);
        add(valor_venda_produto1);
        valor_venda_produto1.setBounds(410, 240, 160, 30);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Valor de venda");
        add(jLabel24);
        jLabel24.setBounds(300, 250, 104, 17);

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Fechar a tela de cadastro de produtos");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        add(btnSair);
        btnSair.setBounds(410, 420, 100, 30);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        btnPesquisa.setToolTipText("Clique para procurar um produto específico");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        add(btnPesquisa);
        btnPesquisa.setBounds(210, 90, 40, 30);

        btnSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Categoria 16px.png"))); // NOI18N
        btnSetores.setText("Gerenciar setores");
        btnSetores.setToolTipText("Clique para cadastrar os setores dos produtos");
        btnSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetoresActionPerformed(evt);
            }
        });
        add(btnSetores);
        btnSetores.setBounds(370, 350, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_produtoActionPerformed

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        
        if(codigo_produto.getText().equals("") || nome_produto.getText().equals("") ||
                valor_venda_produto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            int flagCodigo = 0, flagNome = 0;
            Class_produtos produtos = new Class_produtos();
            
            //aqui eu verifico se o produto que estou tentando adicionar está usando o mesmo código que outros produtos que estão ativos
            if (produtos.verificaCodigoProdutosAtivos(codigo_produto.getText()) == false) 
            {
                flagCodigo = 1;
            }
            
            if (flagCodigo == 0) 
            {
                JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este código! Escolha outro código!", "Atenção", JOptionPane.WARNING_MESSAGE);
                codigo_produto.grabFocus();
                codigo_produto.selectAll();
            }
            else
            {
                if (produtos.verificaNomeProdutos(nome_produto.getText()) == true) 
                {
                    JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este nome! Escolha outro nome!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    nome_produto.grabFocus();
                    nome_produto.selectAll();
                } 
                else 
                {
                    flagNome = 1;
                }

                if(flagCodigo == 1 && flagNome == 1)
                {
                    //aqui eu verifico se o produto que estou tentando adicionar está usando o mesmo código que outros produtos que já foram excluidos
                    //se o produto já foi excluido e tem o mesmo código, eu o excluo e crio outro
                    if (produtos.verificaCodigoProdutosExcluidos(codigo_produto.getText()) == true)
                    {
                        produtos.excluiDefinitivo(codigo_produto.getText());
                    }
                    
                    int id_setor = 0;
                    if (comboTipoCadastrar.getSelectedIndex() != 0) {
                        id_setor = produtos.retornaIdSetor(comboTipoCadastrar.getSelectedItem().toString());
                    }
                    
                    produtos.Cadastra(Integer.valueOf(codigo_produto.getText()), nome_produto.getText(), id_setor,
                            valor_venda_produto.getText());
                    
                    refreshList();
                    
                    cadastro_produtos.dispose();
                }
            }
            
        }
    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        
        Class_produtos produtos = new Class_produtos();
        produtos.carregaSetoresComboBox(comboTipoCadastrar);
        
        limparCamposNovoCadastro();
        
        codigo_produto.setText(String.valueOf(produtos.retornaMaiorIdProduto()+1));
        
        cadastro_produtos.setBounds(0, 0, 410, 400);
        cadastro_produtos.setLocationRelativeTo(null);  
        cadastro_produtos.setVisible(true);
        codigo_produto.grabFocus();
        
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void lista_produtosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_produtosValueChanged
        
        refreshCampos();
        
    }//GEN-LAST:event_lista_produtosValueChanged

    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed
        
        if(codigo_produto2.getText().equals("") || nome_produto2.getText().equals("") ||
                valor_venda_produto2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nao pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        else {
            int flagCodigo = 0, flagNome = 0;
            Class_produtos produtos = new Class_produtos();
            if (codigo_produto1.getText().equals(codigo_produto2.getText()) == false) 
            {
                if (produtos.verificaCodigoProdutosAtivos(codigo_produto2.getText()) == true) 
                {
                    JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este código! Escolha outro código!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    codigo_produto2.grabFocus();
                    codigo_produto2.selectAll();
                }
                else
                {
                    flagCodigo = 1;
                }
            }
            else
            {
                flagCodigo = 1;
            }
            
            if (nome_produto1.getText().equals(nome_produto2.getText()) == false)
            {
                if (produtos.verificaNomeProdutos(nome_produto2.getText()) == true) 
                {
                    JOptionPane.showMessageDialog(null,"Já existe um produto cadastrado com este nome! Escolha outro nome!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    nome_produto2.grabFocus();
                    nome_produto2.selectAll();
                } 
                else 
                {
                    flagNome = 1;
                }
            }
            else
            {
                flagNome = 1;
            }
            
            if (flagCodigo == 1 && flagNome == 1) 
            {
                
                int id_setor = 0;
                if (comboTipoEditar.getSelectedIndex() != 0) {
                    id_setor = produtos.retornaIdSetor(comboTipoEditar.getSelectedItem().toString());
                }
                
                produtos.edita(Integer.valueOf(codigo_produto2.getText()), nome_produto2.getText(), id_setor,
                    valor_venda_produto2.getText());
                JOptionPane.showMessageDialog(null,"Produto editado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                refreshList();
                editar_produtos.setVisible(false);
                
            }
        }
    }//GEN-LAST:event_btnSalvarEditarActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        
        if (lista_produtos.getSelectedIndex() < 0) 
        {
            JOptionPane.showMessageDialog(null, "Selecione um produto para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            carregaEditar();
            editar_produtos.setBounds(0, 0, 410, 400);
            editar_produtos.setLocationRelativeTo(null);
            editar_produtos.setVisible(true);
            codigo_produto2.grabFocus();
        }
        
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void btnSairEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEditarActionPerformed
        
        editar_produtos.setVisible(false);
        
    }//GEN-LAST:event_btnSairEditarActionPerformed

    private void btnSairCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastrarActionPerformed
        
        cadastro_produtos.setVisible(false);
        
    }//GEN-LAST:event_btnSairCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        limparCamposNovoCadastro();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        
        if(!codigo_produto1.getText().equals(""))
        {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o produto "+nome_produto1.getText()+"?", "Atenção", JOptionPane.YES_NO_OPTION)==0)
            {
                Class_produtos produtos = new Class_produtos();
                produtos.exclui(Integer.valueOf(codigo_produto1.getText()));
                refreshList();
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Produtos   ");
        painel_principal.remove(index);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        
        this.add(txtPesquisa);
        txtPesquisa.setBounds(20, 90, 180, 30);
        txtPesquisa.setVisible(true);
        txtPesquisa.setText("");
        txtPesquisa.grabFocus();
        lblProdutosCadastrados.setVisible(false);
        
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        
        refreshPesquisa(txtPesquisa.getText());
        
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void qtd_caixa_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtd_caixa_produtoKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890", evt);
        
    }//GEN-LAST:event_qtd_caixa_produtoKeyTyped

    private void valor_venda_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_venda_produtoKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_valor_venda_produtoKeyTyped

    private void qtd_caixa_produto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtd_caixa_produto2KeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890", evt);
        
    }//GEN-LAST:event_qtd_caixa_produto2KeyTyped

    private void valor_venda_produto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_venda_produto2KeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_valor_venda_produto2KeyTyped

    private void codigo_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_produtoKeyTyped
        
        Class_Consumir_Letras consome = new Class_Consumir_Letras();
        consome.consome("1234567890", evt);
        
    }//GEN-LAST:event_codigo_produtoKeyTyped

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        if (!lblProdutosCadastrados.isVisible()) {
            txtPesquisa.setVisible(false);
            lblProdutosCadastrados.setVisible(true);
            refreshList();
        }
        
    }//GEN-LAST:event_formMousePressed

    private void btnSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetoresActionPerformed
        
        Class_produtos produtos = new Class_produtos();
        list_setores.setModel(produtos.carregaSetores(""));
        setores_produtos.setBounds(0, 0, 510, 380);
        setores_produtos.setLocationRelativeTo(null);
        setores_produtos.setVisible(true);
        
    }//GEN-LAST:event_btnSetoresActionPerformed

    private void btnCadastrarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSetoresActionPerformed
        
        String nome = null;
        nome = JOptionPane.showInputDialog(null, "Digite o nome do setor", "Novo cadastro", JOptionPane.PLAIN_MESSAGE);
        if (nome == null || nome.equals("")) {
        } else {
            Class_Consumir_Letras cons = new Class_Consumir_Letras();
            nome = cons.retiraLetrasEPontos(nome);
            
            if (nome.length() == 0) {
                JOptionPane.showMessageDialog(null, "É preciso digitar caracteres para cadastrar o setor!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                Class_produtos produtos = new Class_produtos();
                if (produtos.verificaNomeRepetidoSetor(nome) == true) {
                    JOptionPane.showMessageDialog(null, "Este nome já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    produtos.cadastraSetor(nome);
                    list_setores.setModel(produtos.carregaSetores(""));
                }
            }
        }
        
    }//GEN-LAST:event_btnCadastrarSetoresActionPerformed

    private void btnEditarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSetoresActionPerformed
        
        Object nome = list_setores.getSelectedValue();
        if (nome == null) {
            JOptionPane.showMessageDialog(null, "Selecione o setor para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            String novo_nome = null;
            novo_nome = JOptionPane.showInputDialog(null, "Digite o novo nome do setor", "Editar setor", JOptionPane.PLAIN_MESSAGE);
            if (novo_nome == null || novo_nome.equals("")) {
            } else {
                Class_Consumir_Letras cons = new Class_Consumir_Letras();
                novo_nome = cons.retiraLetrasEPontos(novo_nome);

                if (novo_nome.length() == 0) {
                    JOptionPane.showMessageDialog(null, "É preciso digitar caracteres para editar o setor!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    Class_produtos produtos = new Class_produtos();
                    if (produtos.verificaNomeRepetidoSetor(novo_nome) == true) {
                        JOptionPane.showMessageDialog(null, "Este nome já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    } else {
                        produtos.editaSetor(nome.toString(), novo_nome);
                        list_setores.setModel(produtos.carregaSetores(""));
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnEditarSetoresActionPerformed

    private void btnExcluirSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSetoresActionPerformed
        
        Object nome = list_setores.getSelectedValue();
        if (nome == null) {
            JOptionPane.showMessageDialog(null, "Selecione o setor para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_produtos produtos = new Class_produtos();
            int id_setor = produtos.retornaIdSetor(nome.toString());
            if (produtos.verificaProdutoVinculadoAoSetor(id_setor) == true) {
                JOptionPane.showMessageDialog(null, "Este setor está vinculado a um produto e não poderá ser excluído!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else if (produtos.verificaSetorPadrao(nome.toString()) == true) {
                JOptionPane.showMessageDialog(null, "Este é um setor padrão e não poderá ser excluído!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    produtos.excluiSetor(id_setor);
                    list_setores.setModel(produtos.carregaSetores(""));
                }
            }
        }
        
    }//GEN-LAST:event_btnExcluirSetoresActionPerformed

    private void btnSairSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairSetoresActionPerformed
        
        setores_produtosMousePressed(null);
        setores_produtos.dispose();
        
    }//GEN-LAST:event_btnSairSetoresActionPerformed

    private void btnPesquisarSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSetoresActionPerformed
        
        if (lblSetoresCadastrados.isVisible()) {
            setores_produtos.add(txtPesquisaSetor);
            txtPesquisaSetor.setBounds(20, 80, 140, 30);
            txtPesquisaSetor.setText("");
            txtPesquisaSetor.grabFocus();
            lblSetoresCadastrados.setVisible(false);
        }
        
    }//GEN-LAST:event_btnPesquisarSetoresActionPerformed

    private void txtPesquisaSetorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaSetorKeyReleased
        
        Class_produtos produtos = new Class_produtos();
        list_setores.setModel(produtos.carregaSetores(txtPesquisaSetor.getText()));
        
    }//GEN-LAST:event_txtPesquisaSetorKeyReleased

    private void setores_produtosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setores_produtosMousePressed
        
        if (!lblSetoresCadastrados.isVisible()) {
            setores_produtos.remove(txtPesquisaSetor);
            lblSetoresCadastrados.setVisible(true);
            Class_produtos produtos = new Class_produtos();
            list_setores.setModel(produtos.carregaSetores(""));
        }
        
    }//GEN-LAST:event_setores_produtosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarSetores;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnEditarSetores;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnExcluirSetores;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPesquisarSetores;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSairCadastrar;
    private javax.swing.JButton btnSairEditar;
    private javax.swing.JButton btnSairSetores;
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JButton btnSetores;
    private javax.swing.JDialog cadastro_produtos;
    private javax.swing.JTextField codigo_produto;
    private javax.swing.JTextField codigo_produto1;
    private javax.swing.JTextField codigo_produto2;
    private javax.swing.JComboBox comboTipoCadastrar;
    private javax.swing.JComboBox comboTipoEditar;
    private javax.swing.JDialog editar_produtos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblProdutosCadastrados;
    private javax.swing.JLabel lblSetoresCadastrados;
    private javax.swing.JList list_setores;
    private javax.swing.JList lista_produtos;
    private javax.swing.JTextField nome_produto;
    private javax.swing.JTextField nome_produto1;
    private javax.swing.JTextField nome_produto2;
    private javax.swing.JDialog setores_produtos;
    private javax.swing.JTextField tipo_produto1;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPesquisaSetor;
    private javax.swing.JTextField valor_venda_produto;
    private javax.swing.JTextField valor_venda_produto1;
    private javax.swing.JTextField valor_venda_produto2;
    // End of variables declaration//GEN-END:variables
}
