
package barsystems.Caixa;

import barsystems.Principal;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

public class Painel_Caixa extends javax.swing.JPanel {

    public Painel_Caixa(Principal principal, JTabbedPane tabelaPrincipal) {
        initComponents();
    }
    
    public void refreshMovimentacaoCaixa() {
        
        Class_Caixa caixa = new Class_Caixa();
        caixa.carregaMovimentacoesCaixa((DefaultTableModel) tabelaMovimentacoesCaixa.getModel());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMovimentacoesCaixa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15.png"))); // NOI18N
        jLabel1.setText("Gerenciamento de caixa por usuário");
        add(jLabel1);
        jLabel1.setBounds(0, 30, 930, 29);

        tabelaMovimentacoesCaixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaMovimentacoesCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Forma Pagto", "Parcelas", "Valor", "Tipo", "Data", "Cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMovimentacoesCaixa.setToolTipText("Movimentações do caixa");
        tabelaMovimentacoesCaixa.setRowHeight(25);
        jScrollPane1.setViewportView(tabelaMovimentacoesCaixa);
        if (tabelaMovimentacoesCaixa.getColumnModel().getColumnCount() > 0) {
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(0).setPreferredWidth(250);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(1).setPreferredWidth(180);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(2).setPreferredWidth(60);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(3).setPreferredWidth(70);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(5).setPreferredWidth(120);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 890, 300);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15 (1).png"))); // NOI18N
        jButton1.setText("Abrir caixa");
        add(jButton1);
        jButton1.setBounds(20, 80, 170, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/plus24.png"))); // NOI18N
        jButton2.setText("Novo lançamento");
        add(jButton2);
        jButton2.setBounds(180, 450, 190, 30);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        jButton3.setText("Alterar lancaçamento");
        add(jButton3);
        jButton3.setBounds(380, 450, 190, 30);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/prohibition9.png"))); // NOI18N
        jButton4.setText("Excluir lançamento");
        add(jButton4);
        jButton4.setBounds(580, 450, 190, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMovimentacoesCaixa;
    // End of variables declaration//GEN-END:variables
}
