/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barsystems;

import barsystems.Centros_Custo.Painel_Caixa;
import barsystems.Centros_Custo.Painel_Centros_Custo;
import barsystems.Configuracoes.Painel_Configuracoes;
import barsystems.Financeiro.Painel_Financeiro;
import barsystems.Login.Frm_Login;
import barsystems.Venda.Painel_Venda;
import barsystems.compras.Painel_compra;
import barsystems.estoque.Class_estoque;
import barsystems.estoque.Painel_estoque;
import barsystems.fornecedores.Painel_Fornecedores;
import barsystems.produtos.Painel_Produtos;
import barsystems.usuarios.Painel_Usuarios;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class Principal extends javax.swing.JFrame {

    protected String nome_usuario;
    protected int id_usuario;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    public Principal(int id_usuario, String nome_usuario) {
        initComponents();
        
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
        
        menuItemCentrosCustoActionPerformed(null);
        menuItemVendaActionPerformed(null);
    }
    
    public void gerarTamanhoTela() {
        
        
        
    }
    
    /**
     * Este método vai verificar se um determinado menu já está aberto, para não o abrirmos novamente
     * @param Aba Nome da aba queserá verificada se já está aberta
     * @return Se retornar >= 0 quer dizer que o menu já foi aberto e o valor de retorno é o index no painel
     */
    public int verificaMenuAberto(String Aba) {
        
        String nomeAba;
        int flag = -1;
        for (int i = 0; i < painel_principal.getTabCount(); i++)
        {
            nomeAba = painel_principal.getTitleAt(i);
            if (nomeAba.equals(Aba))
            {
                flag = i;
                i = painel_principal.getTabCount();
            }
        }
        
        return flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConfiguracoes = new javax.swing.JMenu();
        menuItemConfiguracoesSistema = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        menuItemCadastroUsuarios = new javax.swing.JMenuItem();
        menuItemCadastroProdutos = new javax.swing.JMenuItem();
        menuItemCadastroFornecedores = new javax.swing.JMenuItem();
        menuItemCadastroMesas = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuItemCentrosEstoque = new javax.swing.JMenuItem();
        menuItemCompras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemVenda = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemCentrosCusto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuItemTrocarUsuario = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BarSystem - Sistema gerenciador de bares e restaurantes - Versão 0.1.1");
        setExtendedState(MAXIMIZED_BOTH);
        setName("Principal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painel_principal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuBar1.setToolTipText("");

        menuConfiguracoes.setText("Configurações");
        menuConfiguracoes.setToolTipText("");
        menuConfiguracoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemConfiguracoesSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemConfiguracoesSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/three115.png"))); // NOI18N
        menuItemConfiguracoesSistema.setText("Configurações do sistema");
        menuItemConfiguracoesSistema.setToolTipText("Alterar as configurações do sistema");
        menuItemConfiguracoesSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConfiguracoesSistemaActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(menuItemConfiguracoesSistema);

        jMenuBar1.add(menuConfiguracoes);

        menuCadastros.setText("Cadastros");
        menuCadastros.setToolTipText("");
        menuCadastros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadastros.setName("menu_Produto"); // NOI18N

        menuItemCadastroUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/business60.png"))); // NOI18N
        menuItemCadastroUsuarios.setText("Usuários");
        menuItemCadastroUsuarios.setToolTipText("Cadastrar usuários");
        menuItemCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroUsuariosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroUsuarios);

        menuItemCadastroProdutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/hot51.png"))); // NOI18N
        menuItemCadastroProdutos.setText("Produtos");
        menuItemCadastroProdutos.setToolTipText("Cadastrar produtos");
        menuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroProdutosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroProdutos);

        menuItemCadastroFornecedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/grocery10.png"))); // NOI18N
        menuItemCadastroFornecedores.setText("Fornecedores");
        menuItemCadastroFornecedores.setToolTipText("Cadastrar fornecedores");
        menuItemCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroFornecedoresActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroFornecedores);

        menuItemCadastroMesas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/restaurant2.png"))); // NOI18N
        menuItemCadastroMesas.setText("Mesas");
        menuItemCadastroMesas.setToolTipText("Cadastrar mesas");
        menuCadastros.add(menuItemCadastroMesas);

        jMenuBar1.add(menuCadastros);

        menuEstoque.setText("Estoque");
        menuEstoque.setToolTipText("");
        menuEstoque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemCentrosEstoque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCentrosEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/boxes2.png"))); // NOI18N
        menuItemCentrosEstoque.setText("Centros de estoque");
        menuItemCentrosEstoque.setToolTipText("Cadastrar e controlar centros de estoque");
        menuItemCentrosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCentrosEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemCentrosEstoque);

        menuItemCompras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/add17.png"))); // NOI18N
        menuItemCompras.setText("Compras");
        menuItemCompras.setToolTipText("Realizar uma compra");
        menuItemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemComprasActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemCompras);

        jMenuBar1.add(menuEstoque);

        jMenu4.setText("Bar");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuItemVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/covered16.png"))); // NOI18N
        menuItemVenda.setText("Venda");
        menuItemVenda.setToolTipText("Realizar uma venda");
        menuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemVenda);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Relatórios");
        jMenu6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenu7.setText("Auditoria");
        jMenu7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem18.setText("Clientes");
        jMenu7.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem19.setText("Produtos");
        jMenu7.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem20.setText("Fornecedores");
        jMenu7.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem21.setText("Estoque");
        jMenu7.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem22.setText("Vendas");
        jMenu7.add(jMenuItem22);

        jMenuItem23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem23.setText("Financeiros");
        jMenu7.add(jMenuItem23);

        jMenu6.add(jMenu7);

        jMenu2.setText("Clientes");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setText("Relação de clientes");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setText("Dados de um cliente específico");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem4.setText("Clientes inadimplentes");
        jMenu2.add(jMenuItem4);

        jMenu6.add(jMenu2);

        jMenu8.setText("Fornecedores");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem5.setText("Relação de fornecedores");
        jMenu8.add(jMenuItem5);

        jMenuItem11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem11.setText("Dados de um fornecedor específico");
        jMenu8.add(jMenuItem11);

        jMenu6.add(jMenu8);

        jMenu3.setText("Estoque");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem6.setText("Quantidade em estoque");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem7.setText("Produtos em falta");
        jMenu3.add(jMenuItem7);

        jMenuItem9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem9.setText("Relação de compras");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem10.setText("Compras agendadas");
        jMenu3.add(jMenuItem10);

        jMenu6.add(jMenu3);

        jMenu5.setText("Vendas");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem8.setText("Vendas no bar");
        jMenu5.add(jMenuItem8);

        jMenu6.add(jMenu5);

        jMenu9.setText("Financeiro");
        jMenu9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem12.setText("Movimentação dos caixas");
        jMenu9.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem13.setText("Movimentação das contas bancárias");
        jMenu9.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem14.setText("Balancete");
        jMenu9.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem15.setText("Demonstrativo de resultados e estatísticas");
        jMenu9.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem16.setText("Receitas");
        jMenu9.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem17.setText("Despesas");
        jMenu9.add(jMenuItem17);

        jMenu6.add(jMenu9);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("Financeiro");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemCentrosCusto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15 (1).png"))); // NOI18N
        menuItemCentrosCusto.setText("Centros de custo");
        menuItemCentrosCusto.setToolTipText("Gerenciar caixa");
        menuItemCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCentrosCustoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCentrosCusto);

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coin12.png"))); // NOI18N
        jMenuItem1.setText("Sistema financeiro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        menuSistema.setText("Sistema");
        menuSistema.setToolTipText("");
        menuSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemTrocarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/group12.png"))); // NOI18N
        menuItemTrocarUsuario.setText("Trocar de usuário");
        menuItemTrocarUsuario.setToolTipText("Abre a tela de login para escolher um usuário");
        menuItemTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrocarUsuarioActionPerformed(evt);
            }
        });
        menuSistema.add(menuItemTrocarUsuario);

        menuItemSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.setToolTipText("Sair do sistema");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuItemSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemConfiguracoesSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConfiguracoesSistemaActionPerformed
        
        int index = verificaMenuAberto("Configurações do sistema   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Configuracoes conf = new Painel_Configuracoes(this, painel_principal);
            painel_principal.addTab("Configurações do sistema   ", new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/three115.png")), conf, "Configure o sistema ao seu estilo de trabalho!");
            conf.setBounds(0, 0, 500, 500);
            conf.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemConfiguracoesSistemaActionPerformed

    private void menuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroProdutosActionPerformed
        
        int index = verificaMenuAberto("Produtos   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Produtos cadastraProdutos = new Painel_Produtos(this, painel_principal);
            painel_principal.addTab("Produtos   ", new ImageIcon(getClass().getResource("/barsystems/imagens/hot51.png")), cadastraProdutos, "Cadastre seus produtos!");
            cadastraProdutos.setBounds(0, 0, 500, 500);
            cadastraProdutos.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
            cadastraProdutos.refreshList();
        }
        
    }//GEN-LAST:event_menuItemCadastroProdutosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Class_Fechar_Sistema exit = new Class_Fechar_Sistema();
        exit.fecharSistema();
        
    }//GEN-LAST:event_formWindowClosing

    private void menuItemCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroFornecedoresActionPerformed
        
        int index = verificaMenuAberto("Fornecedores");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Fornecedores cadastraFornecedores = new Painel_Fornecedores(this, painel_principal);
            painel_principal.add("Fornecedores", cadastraFornecedores);
            cadastraFornecedores.setBounds(0, 0, 500, 500);
            cadastraFornecedores.setVisible(true);
            // select the last tab
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
            cadastraFornecedores.refreshList();
        }
        
    }//GEN-LAST:event_menuItemCadastroFornecedoresActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        
        Class_Fechar_Sistema exit = new Class_Fechar_Sistema();
        exit.fecharSistema();
        
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemCentrosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCentrosEstoqueActionPerformed
        
        Painel_estoque estoque = new Painel_estoque();
        painel_principal.add(estoque);
        estoque.setBounds(0, 0, 500, 500);
        estoque.setVisible(true);
        estoque.refreshList();
        
    }//GEN-LAST:event_menuItemCentrosEstoqueActionPerformed

    private void menuItemTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrocarUsuarioActionPerformed
        
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente trocar de usuário?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) 
        {
            Frm_Login login = new Frm_Login();
            login.setVisible(true);

            this.dispose();
        }
        
    }//GEN-LAST:event_menuItemTrocarUsuarioActionPerformed

    private void menuItemCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroUsuariosActionPerformed
        
        int index = verificaMenuAberto("Usuários");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Usuarios usuarios = new Painel_Usuarios(this, painel_principal);
            painel_principal.add("Usuários", usuarios);
            usuarios.setBounds(0, 0, 500, 500);
            usuarios.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
            usuarios.refreshList();
        }
        
    }//GEN-LAST:event_menuItemCadastroUsuariosActionPerformed

    private void menuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaActionPerformed
        
        int index = verificaMenuAberto("Vendas   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Venda venda = new Painel_Venda(this, painel_principal);
            painel_principal.addTab("Vendas   ", new ImageIcon(getClass().getResource("/barsystems/imagens/covered16.png")),venda, "Gerencie mesas e venda produtos!");
            venda.setBounds(0, 0, 1000, 700);
            venda.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemVendaActionPerformed

    private void menuItemCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCentrosCustoActionPerformed
        
        int index = verificaMenuAberto("Centros de custo   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Centros_Custo centros_custo = new Painel_Centros_Custo(this, painel_principal, this.id_usuario, this.nome_usuario);
            painel_principal.addTab("Centros de custo   ", new ImageIcon(getClass().getResource("/barsystems/imagens/coins15 (1).png")), centros_custo, "Gerencie os seus recebimentos!");
            centros_custo.setBounds(0, 0, 1000, 700);
            centros_custo.adicionaCentrosCusto();
            centros_custo.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemCentrosCustoActionPerformed

    private void menuItemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemComprasActionPerformed
        Painel_compra compra = new Painel_compra();
        compra.refreshCombo_Fornecedor();
        compra.refreshFormaPagamento();
        painel_principal.add(compra);
        compra.setBounds(0, 0, 500, 500);
        compra.setVisible(true);
        compra.refreshTable();
    }//GEN-LAST:event_menuItemComprasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        int index = verificaMenuAberto("Sistema financeiro   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Financeiro financeiro = new Painel_Financeiro(this, painel_principal, this.id_usuario, this.nome_usuario);
            painel_principal.addTab("Sistema financeiro   ", new ImageIcon(getClass().getResource("/barsystems/imagens/coin12.png")), financeiro, "Gerencie e configure o sistema financeiro!");
            financeiro.setBounds(0, 0, 1000, 700);
            financeiro.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuItemCadastroFornecedores;
    private javax.swing.JMenuItem menuItemCadastroMesas;
    private javax.swing.JMenuItem menuItemCadastroProdutos;
    private javax.swing.JMenuItem menuItemCadastroUsuarios;
    private javax.swing.JMenuItem menuItemCentrosCusto;
    private javax.swing.JMenuItem menuItemCentrosEstoque;
    private javax.swing.JMenuItem menuItemCompras;
    private javax.swing.JMenuItem menuItemConfiguracoesSistema;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemTrocarUsuario;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JTabbedPane painel_principal;
    // End of variables declaration//GEN-END:variables
}
