
package mesas;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import principal.Class_Consumir_Letras;
import principal.Class_Verifica_Menu_Aberto;

public class Painel_Mesas extends javax.swing.JPanel {
    
    JTabbedPane painel_principal;
    protected int id_usuario;
    protected String nome_usuario;

    public Painel_Mesas() {
        initComponents();
    }
    
    public Painel_Mesas(JTabbedPane painel_principal, int id_usuario, String nome_usuario) {
        initComponents();
        
        this.painel_principal = painel_principal;
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
    }
    
    public void refreshList() {
        Class_Mesas mesas = new Class_Mesas();
        list_mesas.setModel(mesas.refreshList(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_mesas = new javax.swing.JList();
        lblMesasCadastradas = new javax.swing.JLabel();
        btnCadastrarMesa = new javax.swing.JButton();
        btnEditarMesa = new javax.swing.JButton();
        btnExcluirMesa = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisa.setToolTipText("Digite para pesquisar uma mesa");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Mesa 24px.png"))); // NOI18N
        jLabel1.setText("Manutenção do cadastro de mesas");
        add(jLabel1);
        jLabel1.setBounds(0, 30, 470, 30);

        list_mesas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        list_mesas.setSelectionBackground(new java.awt.Color(204, 255, 255));
        list_mesas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(list_mesas);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 180, 220);

        lblMesasCadastradas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMesasCadastradas.setText("Mesas cadastradas");
        add(lblMesasCadastradas);
        lblMesasCadastradas.setBounds(20, 90, 123, 17);

        btnCadastrarMesa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar 16px.png"))); // NOI18N
        btnCadastrarMesa.setText("Cadastrar mesa");
        btnCadastrarMesa.setToolTipText("Cadastrar uma nova mesa para vendas");
        btnCadastrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMesaActionPerformed(evt);
            }
        });
        add(btnCadastrarMesa);
        btnCadastrarMesa.setBounds(260, 110, 190, 30);

        btnEditarMesa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar 16px.png"))); // NOI18N
        btnEditarMesa.setText("Editar mesa");
        btnEditarMesa.setToolTipText("Trocar o número de uma mesa");
        btnEditarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMesaActionPerformed(evt);
            }
        });
        add(btnEditarMesa);
        btnEditarMesa.setBounds(260, 150, 190, 30);

        btnExcluirMesa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir 16px.png"))); // NOI18N
        btnExcluirMesa.setText("Excluir mesa");
        btnExcluirMesa.setToolTipText("Excluir o cadastro de uma mesa");
        btnExcluirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMesaActionPerformed(evt);
            }
        });
        add(btnExcluirMesa);
        btnExcluirMesa.setBounds(260, 190, 190, 30);

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair02 16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Sair da tela de manutenção do cadastro das mesas");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        add(btnSair);
        btnSair.setBounds(260, 230, 190, 30);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisar 16px.png"))); // NOI18N
        btnPesquisa.setToolTipText("Clique para pesquisar uma mesa específica");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        add(btnPesquisa);
        btnPesquisa.setBounds(160, 80, 40, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMesaActionPerformed
        
        String numero = null;
        numero = JOptionPane.showInputDialog(null, "Digite o número da mesa", "Novo cadastro", JOptionPane.PLAIN_MESSAGE);
        if (numero == null || numero.equals("")) {
        } else {
            Class_Consumir_Letras cons = new Class_Consumir_Letras();
            numero = cons.retiraLetrasEPontos(numero);
            if (numero.length() == 0) {
                JOptionPane.showMessageDialog(null, "É preciso digitar números para cadastrar a mesa!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                Class_Mesas mesas = new Class_Mesas();
                if (mesas.verificaNumeroRepetidoMesa(Integer.valueOf(numero)) == true) {
                    JOptionPane.showMessageDialog(null, "Esta mesa já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    mesas.cadastraMesa(Integer.valueOf(numero));
                    list_mesas.setModel(mesas.refreshList(""));
                }
            }
        }
        
    }//GEN-LAST:event_btnCadastrarMesaActionPerformed

    private void btnEditarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMesaActionPerformed
        
        Object numero = list_mesas.getSelectedValue();
        if (numero == null) {
            JOptionPane.showMessageDialog(null, "Selecione a mesa para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            String novo_numero = null;
            novo_numero = JOptionPane.showInputDialog(null, "Digite o novo número da mesa", "Editar cadastro", JOptionPane.PLAIN_MESSAGE);
            if (novo_numero == null || novo_numero.equals("")) {
            } else {
                Class_Consumir_Letras cons = new Class_Consumir_Letras();
                novo_numero = cons.retiraLetrasEPontos(novo_numero);
                if (novo_numero.length() == 0) {
                    JOptionPane.showMessageDialog(null, "É preciso digitar números para editar a mesa!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    Class_Mesas mesas = new Class_Mesas();
                    if (mesas.verificaNumeroRepetidoMesa(Integer.valueOf(novo_numero)) == true) {
                        JOptionPane.showMessageDialog(null, "Esta mesa já existe!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    } else {
                        mesas.editaMesa(Integer.valueOf(numero.toString()), Integer.valueOf(novo_numero));
                        list_mesas.setModel(mesas.refreshList(""));
                    }
                }                 
            }  
        }
        
    }//GEN-LAST:event_btnEditarMesaActionPerformed

    private void btnExcluirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMesaActionPerformed
        
        Object numero = list_mesas.getSelectedValue();
        if (numero == null) {
            JOptionPane.showMessageDialog(null, "Selecione a mesa para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_Mesas mesas = new Class_Mesas();
            int mesa = Integer.valueOf(numero.toString());
            int id_mesa = mesas.retornaIdMesa(mesa);
            if (mesas.verificaMesaPadrao(mesa) == true) {
                JOptionPane.showMessageDialog(null, "Esta é uma mesa padrão e não poderá ser excluída!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    mesas.excluiMesa(id_mesa);
                    list_mesas.setModel(mesas.refreshList(""));
                }
            }
        }
        
    }//GEN-LAST:event_btnExcluirMesaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(this.painel_principal, "Mesas   ");
        this.painel_principal.remove(index);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        
        if (lblMesasCadastradas.isVisible()) {
            this.add(txtPesquisa);
            txtPesquisa.setBounds(20, 80, 120, 30);
            txtPesquisa.setText("");
            txtPesquisa.grabFocus();
            lblMesasCadastradas.setVisible(false);
        }
        
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        
        Class_Mesas mesas = new Class_Mesas();
        list_mesas.setModel(mesas.refreshList(txtPesquisa.getText()));
        
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
        if (!lblMesasCadastradas.isVisible()) {
            this.remove(txtPesquisa);
            lblMesasCadastradas.setVisible(true);
            Class_Mesas mesas = new Class_Mesas();
            list_mesas.setModel(mesas.refreshList(""));
            this.repaint();
        }
        
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarMesa;
    private javax.swing.JButton btnEditarMesa;
    private javax.swing.JButton btnExcluirMesa;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMesasCadastradas;
    private javax.swing.JList list_mesas;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
