/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barsystems.estoque;



import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Lucas
 */
public class Painel_estoque extends javax.swing.JPanel {
    
    /**
     * Creates new form Painel_estoque
     */
     public void refreshList(){
        Class_estoque carrega = new Class_estoque();
        DefaultListModel lista = carrega.carregaLista();
        lista_centros.setModel(lista);
    }
     
     public void refreshTransf(String centro){
         Class_estoque carrega = new Class_estoque();
        DefaultListModel lista = carrega.carregaLista();
        lista.removeElement(centro);
        lista_centro2.setModel(lista);
     }
     
    public void refreshTable(String codigo){
        Class_estoque enviar = new Class_estoque();
        tabela_estoque.setModel(enviar.carregaTabela(codigo));
    }
    
    public void refreshTransferencia(){
        int linha;
        linha = tabela_estoque.getSelectedRow();
        TableModel modelo = tabela_estoque.getModel();
        
        produto.setText((String) modelo.getValueAt(linha,0));
        centro_estoque.setText((String)lista_centros.getSelectedValue());
        radio_button.add(caixas);
        radio_button.add(unidades);
        String unidade, qtd_por_caixa;
        float result;
        unidade = (String) modelo.getValueAt(linha,2);
        qtd_por_caixa = (String) modelo.getValueAt(linha,1);
        result = Integer.parseInt(unidade) / Integer.parseInt(qtd_por_caixa);
        String qtd_de_caixa;
        qntd_por_caixa = Integer.parseInt(qtd_por_caixa);
        qtd_de_caixa = String.valueOf(result);
        quant_caixa.setText(qtd_de_caixa);
        quant_unidade.setText((String) modelo.getValueAt(linha,2));
        refreshTransf((String)lista_centros.getSelectedValue());
    }
    
    public Painel_estoque() {
        initComponents();
    }
    
    protected int qntd_por_caixa;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subir_produto = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        centro_estoque = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quant_caixa = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        quant_unidade = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        caixas = new javax.swing.JRadioButton();
        unidades = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_centro2 = new javax.swing.JList();
        produto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        radio_button = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_centros = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_estoque = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_produto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_fornecedor = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_cod_compra = new javax.swing.JLabel();

        subir_produto.setModal(true);
        subir_produto.getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Este produto esta no(a): ");
        subir_produto.getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 50, 158, 30);

        centro_estoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        centro_estoque.setForeground(new java.awt.Color(0, 0, 204));
        centro_estoque.setText("centroestoque");
        subir_produto.getContentPane().add(centro_estoque);
        centro_estoque.setBounds(180, 50, 115, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Quantidade em caixas:");
        subir_produto.getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 80, 150, 30);

        quant_caixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quant_caixa.setText("caixas");
        subir_produto.getContentPane().add(quant_caixa);
        quant_caixa.setBounds(180, 80, 40, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Quantidade em unidades: ");
        subir_produto.getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 120, 170, 20);

        quant_unidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quant_unidade.setText("unidades");
        subir_produto.getContentPane().add(quant_unidade);
        quant_unidade.setBounds(190, 110, 60, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Transferir: ");
        subir_produto.getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 150, 80, 17);
        subir_produto.getContentPane().add(quantidade);
        quantidade.setBounds(90, 140, 60, 30);

        caixas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        caixas.setText("caixas");
        caixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixasActionPerformed(evt);
            }
        });
        subir_produto.getContentPane().add(caixas);
        caixas.setBounds(160, 140, 65, 25);

        unidades.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        unidades.setText("unidades");
        subir_produto.getContentPane().add(unidades);
        unidades.setBounds(160, 170, 83, 25);

        lista_centro2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lista_centro2);

        subir_produto.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(260, 140, 160, 130);

        produto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        subir_produto.getContentPane().add(produto);
        produto.setBounds(10, 20, 130, 30);

        jButton2.setText("Transferir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        subir_produto.getContentPane().add(jButton2);
        jButton2.setBounds(260, 280, 160, 60);

        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Estoque");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2);
        jLabel2.setBounds(0, 20, 700, 29);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Centros de estoque");
        add(jLabel1);
        jLabel1.setBounds(10, 60, 170, 20);

        lista_centros.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista_centros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_centrosMouseClicked(evt);
            }
        });
        lista_centros.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_centrosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_centros);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 160, 90);

        tabela_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade por caixa", "Quantidade em unidade", "Valor compra unidade", "Valor venda unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_estoqueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_estoque);

        add(jScrollPane2);
        jScrollPane2.setBounds(180, 80, 770, 210);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Produtos em centro de estoque");
        add(jLabel3);
        jLabel3.setBounds(180, 60, 210, 20);

        jButton1.setText("Subir Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(10, 180, 160, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Detalhes do produto:");
        add(jLabel4);
        jLabel4.setBounds(190, 300, 140, 20);

        lbl_produto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(lbl_produto);
        lbl_produto.setBounds(330, 300, 340, 20);

        jLabel10.setText("Ultima compra:");
        add(jLabel10);
        jLabel10.setBounds(190, 330, 110, 14);

        jLabel11.setText("Codigo da compra:");
        add(jLabel11);
        jLabel11.setBounds(190, 360, 120, 14);

        jLabel12.setText("Fornecedor: ");
        add(jLabel12);
        jLabel12.setBounds(190, 390, 100, 14);

        lbl_fornecedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_fornecedor.setText("      ");
        add(lbl_fornecedor);
        lbl_fornecedor.setBounds(300, 390, 310, 17);

        lbl_data.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_data.setText("    ");
        add(lbl_data);
        lbl_data.setBounds(310, 330, 220, 17);

        lbl_cod_compra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_cod_compra.setText("     ");
        add(lbl_cod_compra);
        lbl_cod_compra.setBounds(320, 360, 210, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void lista_centrosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_centrosValueChanged
       Class_estoque resolve = new Class_estoque();
       String codigo = resolve.getCodigo((String) lista_centros.getSelectedValue());
       refreshTable(codigo);
    }//GEN-LAST:event_lista_centrosValueChanged

    private void lista_centrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_centrosMouseClicked
        Class_estoque resolve = new Class_estoque();
        String codigo = resolve.getCodigo((String) lista_centros.getSelectedValue());
        refreshTable(codigo);
    }//GEN-LAST:event_lista_centrosMouseClicked

    private void caixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int linha;
        linha = tabela_estoque.getSelectedRow();
        TableModel modelo = tabela_estoque.getModel();
        
        if( tabela_estoque.getSelectedRowCount() == 0 ){
            JOptionPane.showMessageDialog(null,"Selecione um produto na tabela ao lado");
        }else{
            refreshTransferencia();
            subir_produto.setBounds(0, 0, 450, 330);
            subir_produto.setLocationRelativeTo(null);
            subir_produto.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabela_estoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_estoqueMouseClicked
        int linha;
        linha = tabela_estoque.getSelectedRow();
        TableModel modelo = tabela_estoque.getModel();
        Class_estoque detalhes = new Class_estoque();
        detalhes.carregaDetalhes((String) modelo.getValueAt(linha,0));
        lbl_produto.setText((String) modelo.getValueAt(linha,0));
        lbl_data.setText(detalhes.getData().toString());
        lbl_cod_compra.setText(detalhes.getCodigo_compra());
        lbl_fornecedor.setText(detalhes.getFornecedor());
    }//GEN-LAST:event_tabela_estoqueMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean c1 = true, c2 = true, c3 = true;
        Class_estoque transfere  = new Class_estoque();
       if(quantidade.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Digite uma quantidade");
           c1 = false;
       }
       if(caixas.isSelected() == false && unidades.isSelected() == false){
           JOptionPane.showMessageDialog(null, "Selecione quantidade ou unidade");
           c2 = false;
       }           
       if(lista_centro2.isSelectionEmpty()){
           JOptionPane.showMessageDialog(null, "Selecione um centro de estoque para enviar");
           c3 = false;
       } 
       if(c1 && c2 && c3){
                if(caixas.isSelected()){
                    if( !(qntd_por_caixa*Integer.parseInt(quantidade.getText()) > Integer.parseInt(quant_unidade.getText())) ){
                 transfere.transferencia((String)lista_centro2.getSelectedValue(), 
                 produto.getText(), 
                 Integer.parseInt(quantidade.getText()), 
                 "Caixa", 
                 qntd_por_caixa,
                 centro_estoque.getText());
                 refreshTransferencia();
                    }else
                        JOptionPane.showMessageDialog(null, "Quantidade maior que o estoque");
                } else if(unidades.isSelected()){
                    if( !(Integer.parseInt(quantidade.getText()) > Integer.parseInt(quant_unidade.getText())) ){
                     transfere.transferencia((String)lista_centro2.getSelectedValue(), 
                     produto.getText(), 
                     Integer.parseInt(quantidade.getText()), 
                     "Unidade", 
                     qntd_por_caixa,
                     centro_estoque.getText());
                     refreshTransferencia();
                }else
                        JOptionPane.showMessageDialog(null, "Quantidade maior que o estoque");
            }
       }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton caixas;
    private javax.swing.JLabel centro_estoque;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_cod_compra;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_fornecedor;
    private javax.swing.JLabel lbl_produto;
    private javax.swing.JList lista_centro2;
    private javax.swing.JList lista_centros;
    private javax.swing.JLabel produto;
    private javax.swing.JLabel quant_caixa;
    private javax.swing.JLabel quant_unidade;
    private javax.swing.JTextField quantidade;
    private javax.swing.ButtonGroup radio_button;
    private javax.swing.JDialog subir_produto;
    private javax.swing.JTable tabela_estoque;
    private javax.swing.JRadioButton unidades;
    // End of variables declaration//GEN-END:variables
}
