
package barsystems.Centros_Custo;

import barsystems.Class_Consumir_Letras;
import barsystems.Class_Manipular_Data;
import barsystems.Financeiro.Class_Receitas;
import barsystems.formasPagamento.Class_Formas_Pagto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Painel_Caixa extends javax.swing.JPanel {
    
    protected String nome_usuario, nome_caixa;
    protected int id_centro_custo, id_usuario;

    public Painel_Caixa(int id_centro_custo, String nome_caixa, int id_usuario, String nome_usuario) {
        initComponents();
        
        this.nome_caixa = nome_caixa;
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
        this.id_centro_custo = id_centro_custo;
        
        lblTituloCaixa.setText("Gerenciamento do "+this.nome_caixa+": Usuário "+this.nome_usuario);
        
        refreshMovimentacaoCaixa();
    }
    
    public void refreshMovimentacaoCaixa() {
        
        Class_Caixa caixa = new Class_Caixa();
        int id_caixa = caixa.getIdCaixa(id_centro_custo);
        if (caixa.verificaCaixaAberto(id_caixa) == true) 
        {
            caixa.carregaMovimentacoesCaixa((DefaultTableModel) tabelaMovimentacoesCaixa.getModel(), id_caixa);
            btnAbrirFecharCaixa.setText("Fechar caixa");
        } 
        else 
        {
            btnAbrirFecharCaixa.setText("Abrir caixa");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo_Lancamento = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescricaoNovoLancamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboTipoNovoLancamento = new javax.swing.JComboBox();
        comboFormaNovoLancamento = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValorNovoLancamento = new javax.swing.JTextField();
        btnSalvarNovoLancamento = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSairNovoLancamento = new javax.swing.JButton();
        comboParcelasNovoLancamento = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtDataLanNovoLancamento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHoraNovoLancamento = new javax.swing.JFormattedTextField();
        lblTituloCaixa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMovimentacoesCaixa = new javax.swing.JTable();
        btnAbrirFecharCaixa = new javax.swing.JButton();
        btnNovoLancamento = new javax.swing.JButton();
        btnAlterarLancamento = new javax.swing.JButton();
        btnExcluirLancamento = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        Novo_Lancamento.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Novo_Lancamento.setTitle("Lançamento avulso no caixa");
        Novo_Lancamento.setModal(true);
        Novo_Lancamento.setResizable(false);
        Novo_Lancamento.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15.png"))); // NOI18N
        jLabel1.setText("Lançamento avulso no caixa");
        Novo_Lancamento.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 671, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descrição do lançamento");
        Novo_Lancamento.getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 140, 170, 17);

        txtDescricaoNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_Lancamento.getContentPane().add(txtDescricaoNovoLancamento);
        txtDescricaoNovoLancamento.setBounds(220, 130, 410, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText(" Forma de pagamento");
        Novo_Lancamento.getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 150, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText(" Tipo de lançamento");
        Novo_Lancamento.getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 100, 140, 17);

        comboTipoNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboTipoNovoLancamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receita", "Despesa" }));
        Novo_Lancamento.getContentPane().add(comboTipoNovoLancamento);
        comboTipoNovoLancamento.setBounds(220, 90, 170, 30);

        comboFormaNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_Lancamento.getContentPane().add(comboFormaNovoLancamento);
        comboFormaNovoLancamento.setBounds(220, 170, 410, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Número de parcelas");
        Novo_Lancamento.getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 220, 130, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Valor do lançamento");
        Novo_Lancamento.getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 220, 140, 17);

        txtValorNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorNovoLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorNovoLancamentoKeyTyped(evt);
            }
        });
        Novo_Lancamento.getContentPane().add(txtValorNovoLancamento);
        txtValorNovoLancamento.setBounds(460, 210, 170, 30);

        btnSalvarNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btnSalvarNovoLancamento.setText("Salvar");
        btnSalvarNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNovoLancamentoActionPerformed(evt);
            }
        });
        Novo_Lancamento.getContentPane().add(btnSalvarNovoLancamento);
        btnSalvarNovoLancamento.setBounds(170, 320, 100, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        Novo_Lancamento.getContentPane().add(btnLimpar);
        btnLimpar.setBounds(280, 320, 100, 30);

        btnSairNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairNovoLancamento.setText("Sair");
        btnSairNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairNovoLancamentoActionPerformed(evt);
            }
        });
        Novo_Lancamento.getContentPane().add(btnSairNovoLancamento);
        btnSairNovoLancamento.setBounds(390, 320, 100, 30);

        comboParcelasNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboParcelasNovoLancamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        Novo_Lancamento.getContentPane().add(comboParcelasNovoLancamento);
        comboParcelasNovoLancamento.setBounds(220, 210, 60, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Data do lançamento");
        Novo_Lancamento.getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 260, 127, 17);

        try {
            txtDataLanNovoLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataLanNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_Lancamento.getContentPane().add(txtDataLanNovoLancamento);
        txtDataLanNovoLancamento.setBounds(220, 250, 150, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Hora do lançamento");
        Novo_Lancamento.getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 260, 130, 17);

        try {
            txtHoraNovoLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_Lancamento.getContentPane().add(txtHoraNovoLancamento);
        txtHoraNovoLancamento.setBounds(549, 250, 80, 30);

        setLayout(null);

        lblTituloCaixa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTituloCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15.png"))); // NOI18N
        lblTituloCaixa.setText("Gerenciamento de caixa por usuário");
        add(lblTituloCaixa);
        lblTituloCaixa.setBounds(0, 30, 930, 29);

        tabelaMovimentacoesCaixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaMovimentacoesCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Forma Pagto", "Parcelas", "Valor", "Tipo", "Data", "Responsável", "Cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMovimentacoesCaixa.setToolTipText("Movimentações do caixa");
        tabelaMovimentacoesCaixa.setRowHeight(25);
        tabelaMovimentacoesCaixa.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tabelaMovimentacoesCaixa.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabelaMovimentacoesCaixa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaMovimentacoesCaixa);
        if (tabelaMovimentacoesCaixa.getColumnModel().getColumnCount() > 0) {
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(0).setPreferredWidth(250);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(1).setPreferredWidth(180);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(2).setPreferredWidth(60);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(3).setPreferredWidth(70);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(5).setPreferredWidth(120);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(6).setPreferredWidth(90);
            tabelaMovimentacoesCaixa.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 980, 300);

        btnAbrirFecharCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAbrirFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15 (1).png"))); // NOI18N
        btnAbrirFecharCaixa.setText("Abrir caixa");
        btnAbrirFecharCaixa.setToolTipText("Abra e feche o caixa clicando neste botão");
        btnAbrirFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirFecharCaixaActionPerformed(evt);
            }
        });
        add(btnAbrirFecharCaixa);
        btnAbrirFecharCaixa.setBounds(20, 80, 170, 30);

        btnNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/plus24.png"))); // NOI18N
        btnNovoLancamento.setText("Novo lançamento");
        btnNovoLancamento.setToolTipText("Faça lançamentos de receita e despesa no caixa");
        btnNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLancamentoActionPerformed(evt);
            }
        });
        add(btnNovoLancamento);
        btnNovoLancamento.setBounds(170, 460, 180, 30);

        btnAlterarLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlterarLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnAlterarLancamento.setText("Alterar lançamento");
        btnAlterarLancamento.setToolTipText("Altere as informações de algum lançamento");
        add(btnAlterarLancamento);
        btnAlterarLancamento.setBounds(360, 460, 180, 30);

        btnExcluirLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/prohibition9.png"))); // NOI18N
        btnExcluirLancamento.setText("Excluir lançamento");
        btnExcluirLancamento.setToolTipText("Exclua lançamentos indesejados");
        add(btnExcluirLancamento);
        btnExcluirLancamento.setBounds(550, 460, 180, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/printer11.png"))); // NOI18N
        jButton1.setToolTipText("Imprima a movimentação deste caixa");
        add(jButton1);
        jButton1.setBounds(190, 80, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNovoLancamentoActionPerformed
        
        String forma = comboFormaNovoLancamento.getSelectedItem().toString();
        if (txtDescricaoNovoLancamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite a descrição do lançamento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtDescricaoNovoLancamento.grabFocus();
        } else if (txtValorNovoLancamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o valor do lançamento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtValorNovoLancamento.grabFocus();
        } else {
            //Retornando o id da forma de pagamento
            Class_Formas_Pagto formas = new Class_Formas_Pagto();
            int id_forma_pagto = formas.retornaIdFormaPagamento(forma);
            //Adicionando a movimentação
            Class_Caixa caixa = new Class_Caixa();
            int id_caixa = caixa.getIdCaixa(id_centro_custo);
            Class_Manipular_Data data = new Class_Manipular_Data();
            String data_pagamento = data.retornaDataFormatoMySQL(txtDataLanNovoLancamento.getText(), txtHoraNovoLancamento.getText());
            caixa.registraMovimentacaoCaixa(id_caixa, txtDescricaoNovoLancamento.getText(), id_forma_pagto, 1, txtValorNovoLancamento.getText(), comboTipoNovoLancamento.getSelectedItem().toString(), id_usuario, data_pagamento);
            caixa.carregaMovimentacoesCaixa((DefaultTableModel) tabelaMovimentacoesCaixa.getModel(), id_caixa);
            if (comboTipoNovoLancamento.getSelectedItem().toString().equals("Receita")) {
                int id_movimentacao_caixa = caixa.getIdUltimaMovimentacaoCaixa();
                
                Class_Receitas receitas = new Class_Receitas();
                receitas.cadastraReceita(txtDescricaoNovoLancamento.getText(), 0, "", "Entrada no caixa", forma, 
                        txtValorNovoLancamento.getText(), "0", "0", 
                        Integer.valueOf(comboParcelasNovoLancamento.getSelectedItem().toString()), id_movimentacao_caixa, 
                        data_pagamento, data_pagamento);
            } else {
                
            }
        }
        
    }//GEN-LAST:event_btnSalvarNovoLancamentoActionPerformed

    private void btnAbrirFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirFecharCaixaActionPerformed
        
        if (btnAbrirFecharCaixa.getText().equals("Abrir caixa"))
        {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente abrir o caixa?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                String valor = JOptionPane.showInputDialog(null, "Informe o valor de abertura", "Atenção", JOptionPane.PLAIN_MESSAGE);
                if (valor.isEmpty()) {
                    valor = "0,00";
                }
                
                Class_Consumir_Letras cons = new Class_Consumir_Letras();
                valor = cons.retiraLetras(valor);
                
                Class_Formas_Pagto formas = new Class_Formas_Pagto();
                int id_forma_pagamento = formas.retornaIdFormaPagamento("Dinheiro");

                Class_Caixa caixa = new Class_Caixa();
                caixa.abrirCaixa(id_centro_custo);
                int id_caixa = caixa.getIdCaixa(id_centro_custo);
                Class_Manipular_Data data = new Class_Manipular_Data();
                String data_pagamento = data.retornaDataFormatoMySQL(txtDataLanNovoLancamento.getText(), txtHoraNovoLancamento.getText());
                caixa.registraMovimentacaoCaixa(id_caixa, "Abertura do caixa", id_forma_pagamento, 1, valor, "Abertura", id_usuario, data_pagamento);
                caixa.carregaMovimentacoesCaixa((DefaultTableModel) tabelaMovimentacoesCaixa.getModel(), id_caixa);
                btnAbrirFecharCaixa.setText("Fechar caixa");
            }
        }
        else
        {

        }

    }//GEN-LAST:event_btnAbrirFecharCaixaActionPerformed

    private void btnNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLancamentoActionPerformed

        if (btnAbrirFecharCaixa.getText().equals("Abrir caixa")) {
            JOptionPane.showMessageDialog(null, "Abra uma caixa para fazer um lançamento!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_Formas_Pagto formas = new Class_Formas_Pagto();
            formas.carregaFormasPagamento(comboFormaNovoLancamento);
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            txtDataLanNovoLancamento.setText(sdf.format(new Date()));
            sdf.applyPattern("HH:mm");
            txtHoraNovoLancamento.setText(sdf.format(new Date()));
            Novo_Lancamento.setBounds(0, 0, 690, 410);
            Novo_Lancamento.setLocationRelativeTo(null);
            Novo_Lancamento.setVisible(true);
        }

    }//GEN-LAST:event_btnNovoLancamentoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        comboTipoNovoLancamento.setSelectedIndex(0);
        txtDescricaoNovoLancamento.setText("");
        comboFormaNovoLancamento.setSelectedIndex(0);
        comboParcelasNovoLancamento.setSelectedIndex(0);
        txtValorNovoLancamento.setText("");
        txtDescricaoNovoLancamento.grabFocus();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairNovoLancamentoActionPerformed
        
        Novo_Lancamento.dispose();
        
    }//GEN-LAST:event_btnSairNovoLancamentoActionPerformed

    private void txtValorNovoLancamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorNovoLancamentoKeyTyped
        
        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        cons.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_txtValorNovoLancamentoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Novo_Lancamento;
    private javax.swing.JButton btnAbrirFecharCaixa;
    private javax.swing.JButton btnAlterarLancamento;
    private javax.swing.JButton btnExcluirLancamento;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovoLancamento;
    private javax.swing.JButton btnSairNovoLancamento;
    private javax.swing.JButton btnSalvarNovoLancamento;
    private javax.swing.JComboBox comboFormaNovoLancamento;
    private javax.swing.JComboBox comboParcelasNovoLancamento;
    private javax.swing.JComboBox comboTipoNovoLancamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloCaixa;
    private javax.swing.JTable tabelaMovimentacoesCaixa;
    private javax.swing.JFormattedTextField txtDataLanNovoLancamento;
    private javax.swing.JTextField txtDescricaoNovoLancamento;
    private javax.swing.JFormattedTextField txtHoraNovoLancamento;
    private javax.swing.JTextField txtValorNovoLancamento;
    // End of variables declaration//GEN-END:variables
}
