/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barsystems.fornecedores;

import barsystems.produtos.Class_produtos;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class Painel_Fornecedores extends javax.swing.JPanel {

    private String id_fornecedor;
    /**
     * Creates new form Painel_Fornecedores
     */
    public Painel_Fornecedores() {
        initComponents();
    }
    
    public void setId_fornecedor(String id){
        id_fornecedor = id;
    }
    public String getId_fornecedor(){
        return id_fornecedor;
    }
    
    public void refreshList(){
        Class_Fornecedores carrega = new Class_Fornecedores();
        DefaultListModel lista = carrega.carregaLista();
        lista_produtos.setModel(lista);
    }
    
    public void refreshCampos(){
        Class_Fornecedores seleciona = new Class_Fornecedores();
        seleciona.carregaFornecedor((String) lista_produtos.getSelectedValue());
        nome_fornecedor.setText(seleciona.getRazao_social());
        fantasia_fornecedor.setText(seleciona.getNome_fantasia());
        cnpj_fornecedor.setText(seleciona.getCnpj());
        cidade_fornecedor.setText(seleciona.getCidade());
        estado_fornecedor.setText(seleciona.getEstado());
        endereco_fornecedor.setText(seleciona.getEndereco());
        bairro_fornecedor.setText(seleciona.getBairro());
        telefone_fornecedor.setText(seleciona.getTelefone());
        email_fornecedor.setText(seleciona.getEmail());
        inscricao_fornecedor2.setText(seleciona.getInscricao_estadual());
        obs_fornecedor.setText(seleciona.getObservacoes());
        setId_fornecedor(seleciona.getId_fornecedor());
    }
    
    public void carregaEditar(){
        Class_Fornecedores seleciona = new Class_Fornecedores();
        seleciona.carregaFornecedor((String) lista_produtos.getSelectedValue());
        nome_fornecedor2.setText(seleciona.getRazao_social());
        fantasia_fornecedor2.setText(seleciona.getNome_fantasia());
        cnpj_fornecedor2.setText(seleciona.getCnpj());
        cidade_fornecedor2.setText(seleciona.getCidade());
        estado_fornecedor2.setText(seleciona.getEstado());
        endereco_fornecedor2.setText(seleciona.getEndereco());
        bairro_fornecedor2.setText(seleciona.getBairro());
        telefone_fornecedor2.setText(seleciona.getTelefone());
        email_fornecedor2.setText(seleciona.getEmail());
        inscricao_fornecedor3.setText(seleciona.getInscricao_estadual());
        obs_fornecedor2.setText(seleciona.getObservacoes());
    }
    
    public void refreshPesquisa(String nome){
        Class_Fornecedores carrega = new Class_Fornecedores();
        DefaultListModel lista = carrega.pesquisa(nome);
        lista_produtos.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo_fornecedor = new javax.swing.JDialog();
        email_fornecedor1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        telefone_fornecedor1 = new javax.swing.JTextField();
        bairro_fornecedor1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        endereco_fornecedor1 = new javax.swing.JTextField();
        cidade_fornecedor1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        estado_fornecedor1 = new javax.swing.JTextField();
        cnpj_fornecedor1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fantasia_fornecedor1 = new javax.swing.JTextField();
        nome_fornecedor1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        inscricao_fornecedor1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        obs_fornecedor1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        edita_fornecedor = new javax.swing.JDialog();
        email_fornecedor2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        telefone_fornecedor2 = new javax.swing.JTextField();
        bairro_fornecedor2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        endereco_fornecedor2 = new javax.swing.JTextField();
        cidade_fornecedor2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        estado_fornecedor2 = new javax.swing.JTextField();
        cnpj_fornecedor2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        fantasia_fornecedor2 = new javax.swing.JTextField();
        nome_fornecedor2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        inscricao_fornecedor3 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        obs_fornecedor2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        lbl_fornecedores = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pesquisa_fornecedor = new javax.swing.JTextField();
        pesquisa_fornecedores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_produtos = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        email_fornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telefone_fornecedor = new javax.swing.JTextField();
        bairro_fornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endereco_fornecedor = new javax.swing.JTextField();
        cidade_fornecedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estado_fornecedor = new javax.swing.JTextField();
        cnpj_fornecedor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fantasia_fornecedor = new javax.swing.JTextField();
        nome_fornecedor = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        obs_fornecedor = new javax.swing.JTextField();
        inscricao_fornecedor2 = new javax.swing.JTextField();

        Novo_fornecedor.setModal(true);

        email_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Telefone:");

        telefone_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_fornecedor1ActionPerformed(evt);
            }
        });

        bairro_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Bairro:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Endereco:");

        endereco_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereco_fornecedor1ActionPerformed(evt);
            }
        });

        cidade_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Cidade:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Estado:");

        estado_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("CNPJ:");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Nome Fantasia:");

        fantasia_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantasia_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Nome: ");

        inscricao_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscricao_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Inscricao Estadual:");

        obs_fornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obs_fornecedor1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Observacoes:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cadastrar novo fornecedor");

        jButton8.setText("Salvar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Limpar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cancelar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Novo_fornecedorLayout = new javax.swing.GroupLayout(Novo_fornecedor.getContentPane());
        Novo_fornecedor.getContentPane().setLayout(Novo_fornecedorLayout);
        Novo_fornecedorLayout.setHorizontalGroup(
            Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Novo_fornecedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(6, 6, 6)
                        .addComponent(nome_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fantasia_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(12, 12, 12)
                        .addComponent(cnpj_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(11, 11, 11)
                        .addComponent(cidade_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(estado_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(endereco_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(bairro_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(telefone_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(email_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(inscricao_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(obs_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(Novo_fornecedorLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton8)
                .addGap(6, 6, 6)
                .addComponent(jButton9)
                .addGap(6, 6, 6)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Novo_fornecedorLayout.setVerticalGroup(
            Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Novo_fornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(36, 36, 36)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(nome_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fantasia_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(cnpj_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cidade_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(estado_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(endereco_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(bairro_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(telefone_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(email_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(inscricao_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(obs_fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Novo_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jButton8))
                    .addComponent(jButton10))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        edita_fornecedor.setModal(true);

        email_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fornecedor2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Email:");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Telefone:");

        telefone_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_fornecedor2ActionPerformed(evt);
            }
        });

        bairro_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro_fornecedor2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Bairro:");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Endereco:");

        endereco_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereco_fornecedor2ActionPerformed(evt);
            }
        });

        cidade_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_fornecedor2ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Cidade:");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Estado:");

        estado_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_fornecedor2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("CNPJ:");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Nome Fantasia:");

        fantasia_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantasia_fornecedor2ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Nome: ");

        inscricao_fornecedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscricao_fornecedor3ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("Inscricao Estadual:");

        obs_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obs_fornecedor2ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Observacoes:");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Editar fornecedor");

        jButton11.setText("Editar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Limpar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edita_fornecedorLayout = new javax.swing.GroupLayout(edita_fornecedor.getContentPane());
        edita_fornecedor.getContentPane().setLayout(edita_fornecedorLayout);
        edita_fornecedorLayout.setHorizontalGroup(
            edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edita_fornecedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(6, 6, 6)
                        .addComponent(nome_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fantasia_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(12, 12, 12)
                        .addComponent(cnpj_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(11, 11, 11)
                        .addComponent(cidade_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel30)
                        .addGap(2, 2, 2)
                        .addComponent(estado_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(5, 5, 5)
                        .addComponent(endereco_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(8, 8, 8)
                        .addComponent(bairro_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(10, 10, 10)
                        .addComponent(telefone_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(12, 12, 12)
                        .addComponent(email_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(6, 6, 6)
                        .addComponent(inscricao_fornecedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(edita_fornecedorLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(obs_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(edita_fornecedorLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton11)
                .addGap(6, 6, 6)
                .addComponent(jButton12)
                .addGap(6, 6, 6)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        edita_fornecedorLayout.setVerticalGroup(
            edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edita_fornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGap(36, 36, 36)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(nome_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fantasia_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(cnpj_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(cidade_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(estado_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(endereco_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(bairro_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(telefone_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(email_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(inscricao_fornecedor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(obs_fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edita_fornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton12)
                        .addComponent(jButton11))
                    .addComponent(jButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLayout(null);

        lbl_fornecedores.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_fornecedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fornecedores.setText("Fornecedores");
        add(lbl_fornecedores);
        lbl_fornecedores.setBounds(0, 10, 630, 50);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Fornecedores cadastrados");
        add(jLabel2);
        jLabel2.setBounds(20, 60, 180, 17);

        pesquisa_fornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesquisa_fornecedorKeyTyped(evt);
            }
        });
        add(pesquisa_fornecedor);
        pesquisa_fornecedor.setBounds(20, 80, 160, 30);

        pesquisa_fornecedores.setText("Pesquisar");
        pesquisa_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_fornecedoresActionPerformed(evt);
            }
        });
        add(pesquisa_fornecedores);
        pesquisa_fornecedores.setBounds(190, 80, 130, 30);

        lista_produtos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_produtosMouseClicked(evt);
            }
        });
        lista_produtos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_produtosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_produtos);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 295, 330);

        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(330, 420, 80, 30);

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(410, 420, 80, 30);

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(490, 420, 80, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        email_fornecedor.setEnabled(false);
        email_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(email_fornecedor);
        email_fornecedor.setBounds(60, 220, 235, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 220, 38, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Telefone:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 190, 60, 17);

        telefone_fornecedor.setEnabled(false);
        telefone_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(telefone_fornecedor);
        telefone_fornecedor.setBounds(90, 190, 174, 20);

        bairro_fornecedor.setEnabled(false);
        bairro_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(bairro_fornecedor);
        bairro_fornecedor.setBounds(70, 160, 192, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Bairro:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 160, 42, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Endereco:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 130, 65, 17);

        endereco_fornecedor.setEnabled(false);
        endereco_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereco_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(endereco_fornecedor);
        endereco_fornecedor.setBounds(90, 130, 208, 20);

        cidade_fornecedor.setEnabled(false);
        cidade_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(cidade_fornecedor);
        cidade_fornecedor.setBounds(80, 100, 125, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Cidade:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 100, 49, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Estado:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(210, 100, 48, 17);

        estado_fornecedor.setEnabled(false);
        estado_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(estado_fornecedor);
        estado_fornecedor.setBounds(260, 100, 37, 20);

        cnpj_fornecedor.setEnabled(false);
        jPanel2.add(cnpj_fornecedor);
        cnpj_fornecedor.setBounds(70, 70, 125, 20);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("CNPJ:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 70, 38, 17);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Nome Fantasia:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(20, 40, 99, 17);

        fantasia_fornecedor.setEnabled(false);
        fantasia_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantasia_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(fantasia_fornecedor);
        fantasia_fornecedor.setBounds(130, 40, 125, 20);

        nome_fornecedor.setEnabled(false);
        jPanel2.add(nome_fornecedor);
        nome_fornecedor.setBounds(70, 10, 125, 20);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Nome: ");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 10, 44, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Inscricao Estadual:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 250, 119, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Observacoes:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 280, 100, 17);

        obs_fornecedor.setEnabled(false);
        obs_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obs_fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(obs_fornecedor);
        obs_fornecedor.setBounds(110, 280, 150, 20);

        inscricao_fornecedor2.setEnabled(false);
        inscricao_fornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscricao_fornecedor2ActionPerformed(evt);
            }
        });
        jPanel2.add(inscricao_fornecedor2);
        inscricao_fornecedor2.setBounds(140, 250, 140, 20);

        add(jPanel2);
        jPanel2.setBounds(320, 100, 300, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisa_fornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisa_fornecedorKeyTyped
       refreshPesquisa(pesquisa_fornecedor.getText());
    }//GEN-LAST:event_pesquisa_fornecedorKeyTyped

    private void pesquisa_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_fornecedoresActionPerformed
        refreshPesquisa(pesquisa_fornecedor.getText());
    }//GEN-LAST:event_pesquisa_fornecedoresActionPerformed

    private void lista_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_produtosMouseClicked
        refreshCampos();
    }//GEN-LAST:event_lista_produtosMouseClicked

    private void lista_produtosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_produtosValueChanged
        refreshCampos();
    }//GEN-LAST:event_lista_produtosValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Novo_fornecedor.setBounds(0, 0, 400, 530);
        Novo_fornecedor.setLocationRelativeTo(null);
        Novo_fornecedor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        carregaEditar();
        edita_fornecedor.setBounds(0, 0, 400, 530);
        edita_fornecedor.setLocationRelativeTo(null);
        edita_fornecedor.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(!nome_fornecedor.getText().equals("")){
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o fornecedor "+nome_fornecedor.getText()+"?", "Atenção", JOptionPane.YES_NO_OPTION)==0){
                Class_Fornecedores exclui = new Class_Fornecedores();
                exclui.exclui(getId_fornecedor());
                refreshList();
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void telefone_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_fornecedorActionPerformed

    private void bairro_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro_fornecedorActionPerformed

    private void endereco_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereco_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereco_fornecedorActionPerformed

    private void estado_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_fornecedorActionPerformed

    private void cidade_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_fornecedorActionPerformed

    private void fantasia_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantasia_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fantasia_fornecedorActionPerformed

    private void email_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fornecedorActionPerformed

    private void email_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fornecedor1ActionPerformed

    private void telefone_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_fornecedor1ActionPerformed

    private void bairro_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro_fornecedor1ActionPerformed

    private void endereco_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereco_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereco_fornecedor1ActionPerformed

    private void cidade_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_fornecedor1ActionPerformed

    private void estado_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_fornecedor1ActionPerformed

    private void fantasia_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantasia_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fantasia_fornecedor1ActionPerformed

    private void inscricao_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscricao_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscricao_fornecedor1ActionPerformed

    private void obs_fornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obs_fornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obs_fornecedor1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(nome_fornecedor1.getText().equals("") ||
            fantasia_fornecedor1.getText().equals("") ||
            cnpj_fornecedor1.getText().equals("") ||
            cidade_fornecedor1.getText().equals("") ||
            estado_fornecedor1.getText().equals("") ||
            endereco_fornecedor1.getText().equals("") ||
            bairro_fornecedor1.getText().equals("") ||
            telefone_fornecedor1.getText().equals("") ||
            email_fornecedor1.getText().equals("") ||
            inscricao_fornecedor1.getText().equals("") ||
            obs_fornecedor1.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Nao pode haver campos vazios");
        }
        else{
            Class_Fornecedores enviar = new Class_Fornecedores(
            nome_fornecedor1.getText(),
            fantasia_fornecedor1.getText(),
            cnpj_fornecedor1.getText(),
            cidade_fornecedor1.getText(),
            estado_fornecedor1.getText(),
            endereco_fornecedor1.getText(),
            bairro_fornecedor1.getText(),
            telefone_fornecedor1.getText(),
            email_fornecedor1.getText(),
            inscricao_fornecedor1.getText(),
            obs_fornecedor1.getText()
            ); 
        //Instancia classe de cadastrar produtos
            boolean result = enviar.Cadastra();
            if(!result){

                JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!");
                nome_fornecedor1.setText("");
                fantasia_fornecedor1.setText("");
                cnpj_fornecedor1.setText("");
                cidade_fornecedor1.setText("");
                estado_fornecedor1.setText("");
                endereco_fornecedor1.setText("");
                bairro_fornecedor1.setText("");
                telefone_fornecedor1.setText("");
                email_fornecedor1.setText("");
                inscricao_fornecedor1.setText("");
                obs_fornecedor1.setText("");
                if (JOptionPane.showConfirmDialog(null, "Produto cadastrado com sucesso! \n Deseja cadastrar outro?", "Atenção", JOptionPane.YES_NO_OPTION)==0){
                
                }
                else{
                    Novo_fornecedor.setVisible(false);
                    refreshList();
                }
            
            }
            else{
                JOptionPane.showMessageDialog(null, "Falha ao cadastrar produto");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        nome_fornecedor1.setText("");
        fantasia_fornecedor1.setText("");
        cnpj_fornecedor1.setText("");
        cidade_fornecedor1.setText("");
        estado_fornecedor1.setText("");
        endereco_fornecedor1.setText("");
        bairro_fornecedor1.setText("");
        telefone_fornecedor1.setText("");
        email_fornecedor1.setText("");
        inscricao_fornecedor1.setText("");
        obs_fornecedor1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Novo_fornecedor.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void obs_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obs_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obs_fornecedorActionPerformed

    private void inscricao_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscricao_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscricao_fornecedor2ActionPerformed

    private void email_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fornecedor2ActionPerformed

    private void telefone_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_fornecedor2ActionPerformed

    private void bairro_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro_fornecedor2ActionPerformed

    private void endereco_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereco_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereco_fornecedor2ActionPerformed

    private void cidade_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_fornecedor2ActionPerformed

    private void estado_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_fornecedor2ActionPerformed

    private void fantasia_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantasia_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fantasia_fornecedor2ActionPerformed

    private void inscricao_fornecedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscricao_fornecedor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscricao_fornecedor3ActionPerformed

    private void obs_fornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obs_fornecedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obs_fornecedor2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(nome_fornecedor2.getText().equals("") ||
            fantasia_fornecedor2.getText().equals("") ||
            cnpj_fornecedor2.getText().equals("") ||
            cidade_fornecedor2.getText().equals("") ||
            estado_fornecedor2.getText().equals("") ||
            endereco_fornecedor2.getText().equals("") ||
            bairro_fornecedor2.getText().equals("") ||
            telefone_fornecedor2.getText().equals("") ||
            email_fornecedor2.getText().equals("") ||
            inscricao_fornecedor3.getText().equals("") ||
            obs_fornecedor2.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Nao pode haver campos vazios");
        }
        else{
            Class_Fornecedores editar = new Class_Fornecedores();
           boolean result = editar.edita(
            nome_fornecedor2.getText(),
            fantasia_fornecedor2.getText(),
            cnpj_fornecedor2.getText(),
            cidade_fornecedor2.getText(),
            estado_fornecedor2.getText(),
            endereco_fornecedor2.getText(),
            bairro_fornecedor2.getText(),
            telefone_fornecedor2.getText(),
            email_fornecedor2.getText(),
            inscricao_fornecedor3.getText(),
            obs_fornecedor2.getText(),
            getId_fornecedor()
            ); 
        //Instancia classe de cadastrar produtos
            if(result){
            JOptionPane.showMessageDialog(null,"Produto editado com sucesso!");
            refreshList();
            edita_fornecedor.setVisible(false);
        }
        else{
                JOptionPane.showMessageDialog(null, "Falha ao editar produto");
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         nome_fornecedor2.setText("");
        fantasia_fornecedor2.setText("");
        cnpj_fornecedor2.setText("");
        cidade_fornecedor2.setText("");
        estado_fornecedor2.setText("");
        endereco_fornecedor2.setText("");
        bairro_fornecedor2.setText("");
        telefone_fornecedor2.setText("");
        email_fornecedor2.setText("");
        inscricao_fornecedor3.setText("");
        obs_fornecedor2.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        edita_fornecedor.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Novo_fornecedor;
    private javax.swing.JTextField bairro_fornecedor;
    private javax.swing.JTextField bairro_fornecedor1;
    private javax.swing.JTextField bairro_fornecedor2;
    private javax.swing.JTextField cidade_fornecedor;
    private javax.swing.JTextField cidade_fornecedor1;
    private javax.swing.JTextField cidade_fornecedor2;
    private javax.swing.JTextField cnpj_fornecedor;
    private javax.swing.JTextField cnpj_fornecedor1;
    private javax.swing.JTextField cnpj_fornecedor2;
    private javax.swing.JDialog edita_fornecedor;
    private javax.swing.JTextField email_fornecedor;
    private javax.swing.JTextField email_fornecedor1;
    private javax.swing.JTextField email_fornecedor2;
    private javax.swing.JTextField endereco_fornecedor;
    private javax.swing.JTextField endereco_fornecedor1;
    private javax.swing.JTextField endereco_fornecedor2;
    private javax.swing.JTextField estado_fornecedor;
    private javax.swing.JTextField estado_fornecedor1;
    private javax.swing.JTextField estado_fornecedor2;
    private javax.swing.JTextField fantasia_fornecedor;
    private javax.swing.JTextField fantasia_fornecedor1;
    private javax.swing.JTextField fantasia_fornecedor2;
    private javax.swing.JTextField inscricao_fornecedor1;
    private javax.swing.JTextField inscricao_fornecedor2;
    private javax.swing.JTextField inscricao_fornecedor3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fornecedores;
    private javax.swing.JList lista_produtos;
    private javax.swing.JTextField nome_fornecedor;
    private javax.swing.JTextField nome_fornecedor1;
    private javax.swing.JTextField nome_fornecedor2;
    private javax.swing.JTextField obs_fornecedor;
    private javax.swing.JTextField obs_fornecedor1;
    private javax.swing.JTextField obs_fornecedor2;
    private javax.swing.JTextField pesquisa_fornecedor;
    private javax.swing.JButton pesquisa_fornecedores;
    private javax.swing.JTextField telefone_fornecedor;
    private javax.swing.JTextField telefone_fornecedor1;
    private javax.swing.JTextField telefone_fornecedor2;
    // End of variables declaration//GEN-END:variables
}
