/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barsystems.fornecedores;

import barsystems.Principal;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Lucas
 */
public class Painel_Fornecedores extends javax.swing.JPanel {

    private String id_fornecedor;
    protected JTabbedPane painelPrincipal;
    protected Principal principal;
    
    /**
     * Creates new form Painel_Fornecedores
     */
    public Painel_Fornecedores(Principal principal, JTabbedPane painelPrincipal) {
        initComponents();
        
        this.principal = principal;
        this.painelPrincipal = painelPrincipal;
    }
    
    public void setId_fornecedor(String id){
        id_fornecedor = id;
    }
    public String getId_fornecedor(){
        return id_fornecedor;
    }
    
    public void refreshList(){
        Class_Fornecedores carrega = new Class_Fornecedores();
        DefaultListModel lista = carrega.carregaLista();
        lista_fornecedores.setModel(lista);
    }
    
    public void refreshCampos(){
        Class_Fornecedores seleciona = new Class_Fornecedores();
        seleciona.carregaFornecedor((String) lista_fornecedores.getSelectedValue());
        nome_fornecedor.setText(seleciona.getRazao_social());
        fantasia_fornecedor.setText(seleciona.getNome_fantasia());
        cnpj_fornecedor.setText(seleciona.getCnpj());
        cidade_fornecedor.setText(seleciona.getCidade());
        estado_fornecedor.setText(seleciona.getEstado());
        endereco_fornecedor.setText(seleciona.getEndereco());
        bairro_fornecedor.setText(seleciona.getBairro());
        telefone_fornecedor.setText(seleciona.getTelefone());
        email_fornecedor.setText(seleciona.getEmail());
        inscricao_fornecedor2.setText(seleciona.getInscricao_estadual());
        setId_fornecedor(seleciona.getId_fornecedor());
    }
    
    public void carregaEditar(){
        Class_Fornecedores seleciona = new Class_Fornecedores();
        seleciona.carregaFornecedor((String) lista_fornecedores.getSelectedValue());
        nome_fornecedor2.setText(seleciona.getRazao_social());
        fantasia_fornecedor2.setText(seleciona.getNome_fantasia());
        cnpj_fornecedor2.setText(seleciona.getCnpj());
        cidade_fornecedor2.setText(seleciona.getCidade());
        estado_fornecedor2.setText(seleciona.getEstado());
        endereco_fornecedor2.setText(seleciona.getEndereco());
        bairro_fornecedor2.setText(seleciona.getBairro());
        telefone_fornecedor2.setText(seleciona.getTelefone());
        email_fornecedor2.setText(seleciona.getEmail());
        inscricao_fornecedor3.setText(seleciona.getInscricao_estadual());
        obs_fornecedor2.setText(seleciona.getObservacoes());
    }
    
    public void refreshPesquisa(String nome){
        Class_Fornecedores carrega = new Class_Fornecedores();
        DefaultListModel lista = carrega.pesquisa(nome);
        lista_fornecedores.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo_fornecedor = new javax.swing.JDialog();
        email_fornecedor1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        telefone_fornecedor1 = new javax.swing.JTextField();
        bairro_fornecedor1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        endereco_fornecedor1 = new javax.swing.JTextField();
        cidade_fornecedor1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        estado_fornecedor1 = new javax.swing.JTextField();
        cnpj_fornecedor1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fantasia_fornecedor1 = new javax.swing.JTextField();
        nome_fornecedor1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        inscricao_fornecedor1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        obs_fornecedor1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        edita_fornecedor = new javax.swing.JDialog();
        email_fornecedor2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        telefone_fornecedor2 = new javax.swing.JTextField();
        bairro_fornecedor2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        endereco_fornecedor2 = new javax.swing.JTextField();
        cidade_fornecedor2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        estado_fornecedor2 = new javax.swing.JTextField();
        cnpj_fornecedor2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        fantasia_fornecedor2 = new javax.swing.JTextField();
        nome_fornecedor2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        inscricao_fornecedor3 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        obs_fornecedor2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        lbl_fornecedores = new javax.swing.JLabel();
        lblFornecedoresCadastrados = new javax.swing.JLabel();
        pesquisa_fornecedores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_fornecedores = new javax.swing.JList();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        nome_fornecedor = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fantasia_fornecedor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cnpj_fornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        estado_fornecedor = new javax.swing.JTextField();
        cidade_fornecedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endereco_fornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bairro_fornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefone_fornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email_fornecedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inscricao_fornecedor2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnObservacoes = new javax.swing.JButton();
        btnFecharTela = new javax.swing.JButton();

        Novo_fornecedor.setTitle("Novo cadastro");
        Novo_fornecedor.setModal(true);
        Novo_fornecedor.setResizable(false);
        Novo_fornecedor.getContentPane().setLayout(null);

        email_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(email_fornecedor1);
        email_fornecedor1.setBounds(160, 360, 290, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Email");
        Novo_fornecedor.getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 370, 38, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Telefone");
        Novo_fornecedor.getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 330, 60, 17);

        telefone_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(telefone_fornecedor1);
        telefone_fornecedor1.setBounds(160, 320, 290, 30);

        bairro_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(bairro_fornecedor1);
        bairro_fornecedor1.setBounds(160, 280, 290, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("  Bairro");
        Novo_fornecedor.getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 290, 50, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText(" Endereço");
        Novo_fornecedor.getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 250, 65, 17);

        endereco_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(endereco_fornecedor1);
        endereco_fornecedor1.setBounds(160, 240, 290, 30);

        cidade_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(cidade_fornecedor1);
        cidade_fornecedor1.setBounds(160, 200, 200, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Cidade");
        Novo_fornecedor.getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 210, 45, 17);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("UF");
        Novo_fornecedor.getContentPane().add(jLabel15);
        jLabel15.setBounds(380, 210, 20, 17);

        estado_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(estado_fornecedor1);
        estado_fornecedor1.setBounds(410, 200, 40, 30);

        cnpj_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(cnpj_fornecedor1);
        cnpj_fornecedor1.setBounds(160, 160, 120, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("CNPJ");
        Novo_fornecedor.getContentPane().add(jLabel23);
        jLabel23.setBounds(110, 170, 34, 17);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Nome Fantasia");
        Novo_fornecedor.getContentPane().add(jLabel24);
        jLabel24.setBounds(50, 130, 95, 17);

        fantasia_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(fantasia_fornecedor1);
        fantasia_fornecedor1.setBounds(160, 120, 290, 30);

        nome_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(nome_fornecedor1);
        nome_fornecedor1.setBounds(160, 80, 290, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Razão Social");
        Novo_fornecedor.getContentPane().add(jLabel25);
        jLabel25.setBounds(60, 90, 82, 17);

        inscricao_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(inscricao_fornecedor1);
        inscricao_fornecedor1.setBounds(330, 160, 120, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("I.E.");
        Novo_fornecedor.getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 170, 30, 17);

        obs_fornecedor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_fornecedor.getContentPane().add(obs_fornecedor1);
        obs_fornecedor1.setBounds(160, 400, 290, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Observacoes");
        Novo_fornecedor.getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 410, 90, 17);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/cargo3 (1).png"))); // NOI18N
        jLabel18.setText("Cadastrar novo fornecedor");
        Novo_fornecedor.getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 30, 580, 29);

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar o cadastro do fornecedor");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        Novo_fornecedor.getContentPane().add(btnSalvar);
        btnSalvar.setBounds(140, 470, 100, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar os campos e recomeçar o cadastro");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        Novo_fornecedor.getContentPane().add(btnLimpar);
        btnLimpar.setBounds(250, 470, 100, 30);

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Cancelar cadastro do fornecedor");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        Novo_fornecedor.getContentPane().add(btnSair);
        btnSair.setBounds(360, 470, 100, 30);

        edita_fornecedor.setTitle("Alteração de dados");
        edita_fornecedor.setModal(true);
        edita_fornecedor.setResizable(false);
        edita_fornecedor.getContentPane().setLayout(null);
        edita_fornecedor.getContentPane().add(email_fornecedor2);
        email_fornecedor2.setBounds(180, 360, 290, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Email");
        edita_fornecedor.getContentPane().add(jLabel19);
        jLabel19.setBounds(130, 370, 38, 17);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Telefone");
        edita_fornecedor.getContentPane().add(jLabel26);
        jLabel26.setBounds(110, 330, 56, 17);
        edita_fornecedor.getContentPane().add(telefone_fornecedor2);
        telefone_fornecedor2.setBounds(180, 320, 290, 30);
        edita_fornecedor.getContentPane().add(bairro_fornecedor2);
        bairro_fornecedor2.setBounds(180, 280, 290, 30);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("  Bairro");
        edita_fornecedor.getContentPane().add(jLabel27);
        jLabel27.setBounds(120, 290, 50, 17);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText(" Endereço");
        edita_fornecedor.getContentPane().add(jLabel28);
        jLabel28.setBounds(100, 250, 65, 17);
        edita_fornecedor.getContentPane().add(endereco_fornecedor2);
        endereco_fornecedor2.setBounds(180, 240, 290, 30);
        edita_fornecedor.getContentPane().add(cidade_fornecedor2);
        cidade_fornecedor2.setBounds(180, 200, 200, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Cidade");
        edita_fornecedor.getContentPane().add(jLabel29);
        jLabel29.setBounds(120, 210, 45, 17);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("UF");
        edita_fornecedor.getContentPane().add(jLabel30);
        jLabel30.setBounds(400, 210, 20, 17);
        edita_fornecedor.getContentPane().add(estado_fornecedor2);
        estado_fornecedor2.setBounds(430, 200, 40, 30);
        edita_fornecedor.getContentPane().add(cnpj_fornecedor2);
        cnpj_fornecedor2.setBounds(180, 160, 110, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("CNPJ");
        edita_fornecedor.getContentPane().add(jLabel31);
        jLabel31.setBounds(130, 170, 38, 17);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Nome Fantasia");
        edita_fornecedor.getContentPane().add(jLabel32);
        jLabel32.setBounds(70, 130, 95, 17);
        edita_fornecedor.getContentPane().add(fantasia_fornecedor2);
        fantasia_fornecedor2.setBounds(180, 120, 290, 30);
        edita_fornecedor.getContentPane().add(nome_fornecedor2);
        nome_fornecedor2.setBounds(180, 80, 290, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Razão Social");
        edita_fornecedor.getContentPane().add(jLabel33);
        jLabel33.setBounds(80, 90, 90, 17);
        edita_fornecedor.getContentPane().add(inscricao_fornecedor3);
        inscricao_fornecedor3.setBounds(350, 160, 120, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("I.E.");
        edita_fornecedor.getContentPane().add(jLabel34);
        jLabel34.setBounds(320, 170, 30, 17);
        edita_fornecedor.getContentPane().add(obs_fornecedor2);
        obs_fornecedor2.setBounds(180, 400, 290, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Observacoes");
        edita_fornecedor.getContentPane().add(jLabel35);
        jLabel35.setBounds(80, 410, 90, 17);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/cargo3 (1).png"))); // NOI18N
        jLabel36.setText("Editar fornecedor");
        edita_fornecedor.getContentPane().add(jLabel36);
        jLabel36.setBounds(0, 30, 580, 29);

        jButton11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        jButton11.setText("Salvar");
        jButton11.setToolTipText("Finalizar a edição das informações do fornecedor");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        edita_fornecedor.getContentPane().add(jButton11);
        jButton11.setBounds(190, 460, 100, 30);

        jButton13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        jButton13.setText("Sair");
        jButton13.setToolTipText("Cancelar edição das informações do fornecedor");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        edita_fornecedor.getContentPane().add(jButton13);
        jButton13.setBounds(300, 460, 100, 30);

        txtPesquisa.setText("jTextField1");
        txtPesquisa.setToolTipText("Digite para procurar um produto específico");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        lbl_fornecedores.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_fornecedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/cargo3 (1).png"))); // NOI18N
        lbl_fornecedores.setText("Manutenção do cadastro de fornecedores");
        add(lbl_fornecedores);
        lbl_fornecedores.setBounds(0, 30, 760, 30);

        lblFornecedoresCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFornecedoresCadastrados.setText("Fornecedores cadastrados");
        add(lblFornecedoresCadastrados);
        lblFornecedoresCadastrados.setBounds(20, 100, 180, 17);

        pesquisa_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/magnifier12.png"))); // NOI18N
        pesquisa_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_fornecedoresActionPerformed(evt);
            }
        });
        add(pesquisa_fornecedores);
        pesquisa_fornecedores.setBounds(260, 90, 40, 30);

        lista_fornecedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_fornecedores.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_fornecedores.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_fornecedoresMouseClicked(evt);
            }
        });
        lista_fornecedores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_fornecedoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_fornecedores);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 280, 310);

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/plus24.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Cadastrar novo fornecedor");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        add(btnNovo);
        btnNovo.setBounds(170, 480, 100, 30);

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar as informações de um fornecedor");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        add(btnAlterar);
        btnAlterar.setBounds(280, 480, 100, 30);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/prohibition9.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir o cadastro de um fornecedor");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        add(btnExcluir);
        btnExcluir.setBounds(390, 480, 100, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Razão Social");
        add(jLabel20);
        jLabel20.setBounds(350, 130, 90, 17);

        nome_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome_fornecedor.setEnabled(false);
        add(nome_fornecedor);
        nome_fornecedor.setBounds(450, 120, 290, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Nome Fantasia");
        add(jLabel21);
        jLabel21.setBounds(340, 170, 99, 17);

        fantasia_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fantasia_fornecedor.setEnabled(false);
        add(fantasia_fornecedor);
        fantasia_fornecedor.setBounds(450, 160, 290, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("CNPJ");
        add(jLabel22);
        jLabel22.setBounds(400, 210, 34, 17);

        cnpj_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cnpj_fornecedor.setEnabled(false);
        add(cnpj_fornecedor);
        cnpj_fornecedor.setBounds(450, 200, 120, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("UF");
        add(jLabel3);
        jLabel3.setBounds(670, 250, 20, 17);

        estado_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        estado_fornecedor.setEnabled(false);
        add(estado_fornecedor);
        estado_fornecedor.setBounds(700, 240, 40, 30);

        cidade_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cidade_fornecedor.setEnabled(false);
        add(cidade_fornecedor);
        cidade_fornecedor.setBounds(450, 240, 200, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Cidade");
        add(jLabel1);
        jLabel1.setBounds(390, 250, 49, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Endereço");
        add(jLabel4);
        jLabel4.setBounds(370, 290, 80, 17);

        endereco_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        endereco_fornecedor.setEnabled(false);
        add(endereco_fornecedor);
        endereco_fornecedor.setBounds(450, 280, 290, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText(" Bairro");
        add(jLabel5);
        jLabel5.setBounds(390, 330, 42, 17);

        bairro_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bairro_fornecedor.setEnabled(false);
        add(bairro_fornecedor);
        bairro_fornecedor.setBounds(450, 320, 290, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Telefone");
        add(jLabel6);
        jLabel6.setBounds(380, 410, 56, 17);

        telefone_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        telefone_fornecedor.setEnabled(false);
        add(telefone_fornecedor);
        telefone_fornecedor.setBounds(450, 400, 120, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Email");
        add(jLabel7);
        jLabel7.setBounds(400, 370, 34, 17);

        email_fornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email_fornecedor.setEnabled(false);
        add(email_fornecedor);
        email_fornecedor.setBounds(450, 360, 290, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("I.E.");
        add(jLabel8);
        jLabel8.setBounds(590, 210, 20, 17);

        inscricao_fornecedor2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inscricao_fornecedor2.setEnabled(false);
        add(inscricao_fornecedor2);
        inscricao_fornecedor2.setBounds(620, 200, 120, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Observações");
        add(jLabel9);
        jLabel9.setBounds(600, 410, 90, 17);

        btnObservacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/magnifier12.png"))); // NOI18N
        btnObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObservacoesActionPerformed(evt);
            }
        });
        add(btnObservacoes);
        btnObservacoes.setBounds(700, 400, 40, 30);

        btnFecharTela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFecharTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnFecharTela.setText("Sair");
        btnFecharTela.setToolTipText("Sair da tela de cadastro de fornecedores");
        btnFecharTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharTelaActionPerformed(evt);
            }
        });
        add(btnFecharTela);
        btnFecharTela.setBounds(500, 480, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisa_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_fornecedoresActionPerformed
        
        this.add(txtPesquisa);
        txtPesquisa.setBounds(20, 90, 180, 30);
        txtPesquisa.setVisible(true);
        txtPesquisa.setText("");
        txtPesquisa.grabFocus();
        lblFornecedoresCadastrados.setVisible(false);
        
    }//GEN-LAST:event_pesquisa_fornecedoresActionPerformed

    private void lista_fornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_fornecedoresMouseClicked
        refreshCampos();
    }//GEN-LAST:event_lista_fornecedoresMouseClicked

    private void lista_fornecedoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_fornecedoresValueChanged
        refreshCampos();
    }//GEN-LAST:event_lista_fornecedoresValueChanged

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        Novo_fornecedor.setBounds(0, 0, 580, 570);
        Novo_fornecedor.setLocationRelativeTo(null);
        Novo_fornecedor.setVisible(true);
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        if(!nome_fornecedor.getText().equals(""))
        {
            carregaEditar();
            edita_fornecedor.setBounds(0, 0, 580, 570);
            edita_fornecedor.setLocationRelativeTo(null);
            edita_fornecedor.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor para alterar as informações!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       
        if(!nome_fornecedor.getText().equals(""))
        {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o fornecedor "+nome_fornecedor.getText()+"?", "Atenção", JOptionPane.YES_NO_OPTION)==0)
            {
                Class_Fornecedores exclui = new Class_Fornecedores();
                exclui.exclui(getId_fornecedor());
                refreshList();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if(nome_fornecedor1.getText().equals("") ||
            fantasia_fornecedor1.getText().equals("") ||
            cnpj_fornecedor1.getText().equals("") ||
            cidade_fornecedor1.getText().equals("") ||
            estado_fornecedor1.getText().equals("") ||
            endereco_fornecedor1.getText().equals("") ||
            bairro_fornecedor1.getText().equals("") ||
            telefone_fornecedor1.getText().equals("") ||
            email_fornecedor1.getText().equals("") ||
            inscricao_fornecedor1.getText().equals("") ||
            obs_fornecedor1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Nao pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Class_Fornecedores enviar = new Class_Fornecedores(
            nome_fornecedor1.getText(),
            fantasia_fornecedor1.getText(),
            cnpj_fornecedor1.getText(),
            cidade_fornecedor1.getText(),
            estado_fornecedor1.getText(),
            endereco_fornecedor1.getText(),
            bairro_fornecedor1.getText(),
            telefone_fornecedor1.getText(),
            email_fornecedor1.getText(),
            inscricao_fornecedor1.getText(),
            obs_fornecedor1.getText()
            ); 
            //Instancia classe de cadastrar produtos
            boolean result = enviar.Cadastra();
            if(!result)
            {
                JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                nome_fornecedor1.setText("");
                fantasia_fornecedor1.setText("");
                cnpj_fornecedor1.setText("");
                cidade_fornecedor1.setText("");
                estado_fornecedor1.setText("");
                endereco_fornecedor1.setText("");
                bairro_fornecedor1.setText("");
                telefone_fornecedor1.setText("");
                email_fornecedor1.setText("");
                inscricao_fornecedor1.setText("");
                obs_fornecedor1.setText("");
 
                Novo_fornecedor.dispose();
                refreshList();            
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falha ao cadastrar Fornecedor!", "Atenção", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       
        nome_fornecedor1.setText("");
        fantasia_fornecedor1.setText("");
        cnpj_fornecedor1.setText("");
        cidade_fornecedor1.setText("");
        estado_fornecedor1.setText("");
        endereco_fornecedor1.setText("");
        bairro_fornecedor1.setText("");
        telefone_fornecedor1.setText("");
        email_fornecedor1.setText("");
        inscricao_fornecedor1.setText("");
        obs_fornecedor1.setText("");
        
        nome_fornecedor1.grabFocus();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        Novo_fornecedor.setVisible(false);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(nome_fornecedor2.getText().equals("") ||
            fantasia_fornecedor2.getText().equals("") ||
            cnpj_fornecedor2.getText().equals("") ||
            cidade_fornecedor2.getText().equals("") ||
            estado_fornecedor2.getText().equals("") ||
            endereco_fornecedor2.getText().equals("") ||
            bairro_fornecedor2.getText().equals("") ||
            telefone_fornecedor2.getText().equals("") ||
            email_fornecedor2.getText().equals("") ||
            inscricao_fornecedor3.getText().equals("") ||
            obs_fornecedor2.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Nao pode haver campos vazios");
        }
        else{
            Class_Fornecedores editar = new Class_Fornecedores();
           boolean result = editar.edita(
            nome_fornecedor2.getText(),
            fantasia_fornecedor2.getText(),
            cnpj_fornecedor2.getText(),
            cidade_fornecedor2.getText(),
            estado_fornecedor2.getText(),
            endereco_fornecedor2.getText(),
            bairro_fornecedor2.getText(),
            telefone_fornecedor2.getText(),
            email_fornecedor2.getText(),
            inscricao_fornecedor3.getText(),
            obs_fornecedor2.getText(),
            getId_fornecedor()
            ); 
        //Instancia classe de cadastrar produtos
            if(result){
            JOptionPane.showMessageDialog(null,"Produto editado com sucesso!");
            refreshList();
            edita_fornecedor.setVisible(false);
        }
        else{
                JOptionPane.showMessageDialog(null, "Falha ao editar produto");
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
        edita_fornecedor.setVisible(false);
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObservacoesActionPerformed
        
        if (lista_fornecedores.getSelectedIndex() < 0)
        {
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor para visualizar as observações!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Class_Fornecedores seleciona = new Class_Fornecedores();
            seleciona.carregaFornecedor((String) lista_fornecedores.getSelectedValue());
            String observacoes = seleciona.getObservacoes();
            if (observacoes.equals("")) {
                JOptionPane.showMessageDialog(this, "Não foi adicionada nenhuma observação.", "Observações do fornecedor", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, observacoes, "Observações do fornecedor", JOptionPane.PLAIN_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnObservacoesActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased

        refreshPesquisa(txtPesquisa.getText());

    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        if (!lblFornecedoresCadastrados.isVisible()) {
            txtPesquisa.setVisible(false);
            lblFornecedoresCadastrados.setVisible(true);
            refreshList();
        }
        
    }//GEN-LAST:event_formMousePressed

    private void btnFecharTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharTelaActionPerformed
        
        int index = principal.verificaMenuAberto("Fornecedores");
        painelPrincipal.remove(index);
        
    }//GEN-LAST:event_btnFecharTelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Novo_fornecedor;
    private javax.swing.JTextField bairro_fornecedor;
    private javax.swing.JTextField bairro_fornecedor1;
    private javax.swing.JTextField bairro_fornecedor2;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFecharTela;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnObservacoes;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cidade_fornecedor;
    private javax.swing.JTextField cidade_fornecedor1;
    private javax.swing.JTextField cidade_fornecedor2;
    private javax.swing.JTextField cnpj_fornecedor;
    private javax.swing.JTextField cnpj_fornecedor1;
    private javax.swing.JTextField cnpj_fornecedor2;
    private javax.swing.JDialog edita_fornecedor;
    private javax.swing.JTextField email_fornecedor;
    private javax.swing.JTextField email_fornecedor1;
    private javax.swing.JTextField email_fornecedor2;
    private javax.swing.JTextField endereco_fornecedor;
    private javax.swing.JTextField endereco_fornecedor1;
    private javax.swing.JTextField endereco_fornecedor2;
    private javax.swing.JTextField estado_fornecedor;
    private javax.swing.JTextField estado_fornecedor1;
    private javax.swing.JTextField estado_fornecedor2;
    private javax.swing.JTextField fantasia_fornecedor;
    private javax.swing.JTextField fantasia_fornecedor1;
    private javax.swing.JTextField fantasia_fornecedor2;
    private javax.swing.JTextField inscricao_fornecedor1;
    private javax.swing.JTextField inscricao_fornecedor2;
    private javax.swing.JTextField inscricao_fornecedor3;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFornecedoresCadastrados;
    private javax.swing.JLabel lbl_fornecedores;
    private javax.swing.JList lista_fornecedores;
    private javax.swing.JTextField nome_fornecedor;
    private javax.swing.JTextField nome_fornecedor1;
    private javax.swing.JTextField nome_fornecedor2;
    private javax.swing.JTextField obs_fornecedor1;
    private javax.swing.JTextField obs_fornecedor2;
    private javax.swing.JButton pesquisa_fornecedores;
    private javax.swing.JTextField telefone_fornecedor;
    private javax.swing.JTextField telefone_fornecedor1;
    private javax.swing.JTextField telefone_fornecedor2;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
